package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAttendanceManuallyId generated by hbm2java
 */
public class TbAttendanceManuallyId implements java.io.Serializable {

	private int autoId;
	private String vemployeeId;
	private String vfingerId;
	private String vemployeeName;
	private String vdesignationId;
	private String vsectionId;
	private Date dattFromDate;
	private Date inTime;
	private Date dattToDate;
	private Date outTime;
	private String vreason;
	private String vpermitBy;
	private String userName;
	private String userIp;
	private Date entryTime;

	public TbAttendanceManuallyId() {
	}

	public TbAttendanceManuallyId(int autoId) {
		this.autoId = autoId;
	}

	public TbAttendanceManuallyId(int autoId, String vemployeeId,
			String vfingerId, String vemployeeName, String vdesignationId,
			String vsectionId, Date dattFromDate, Date inTime, Date dattToDate,
			Date outTime, String vreason, String vpermitBy, String userName,
			String userIp, Date entryTime) {
		this.autoId = autoId;
		this.vemployeeId = vemployeeId;
		this.vfingerId = vfingerId;
		this.vemployeeName = vemployeeName;
		this.vdesignationId = vdesignationId;
		this.vsectionId = vsectionId;
		this.dattFromDate = dattFromDate;
		this.inTime = inTime;
		this.dattToDate = dattToDate;
		this.outTime = outTime;
		this.vreason = vreason;
		this.vpermitBy = vpermitBy;
		this.userName = userName;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVfingerId() {
		return this.vfingerId;
	}

	public void setVfingerId(String vfingerId) {
		this.vfingerId = vfingerId;
	}

	public String getVemployeeName() {
		return this.vemployeeName;
	}

	public void setVemployeeName(String vemployeeName) {
		this.vemployeeName = vemployeeName;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public Date getDattFromDate() {
		return this.dattFromDate;
	}

	public void setDattFromDate(Date dattFromDate) {
		this.dattFromDate = dattFromDate;
	}

	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	public Date getDattToDate() {
		return this.dattToDate;
	}

	public void setDattToDate(Date dattToDate) {
		this.dattToDate = dattToDate;
	}

	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	public String getVreason() {
		return this.vreason;
	}

	public void setVreason(String vreason) {
		this.vreason = vreason;
	}

	public String getVpermitBy() {
		return this.vpermitBy;
	}

	public void setVpermitBy(String vpermitBy) {
		this.vpermitBy = vpermitBy;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbAttendanceManuallyId))
			return false;
		TbAttendanceManuallyId castOther = (TbAttendanceManuallyId) other;

		return (this.getAutoId() == castOther.getAutoId())
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVfingerId() == castOther.getVfingerId()) || (this
						.getVfingerId() != null
						&& castOther.getVfingerId() != null && this
						.getVfingerId().equals(castOther.getVfingerId())))
				&& ((this.getVemployeeName() == castOther.getVemployeeName()) || (this
						.getVemployeeName() != null
						&& castOther.getVemployeeName() != null && this
						.getVemployeeName()
						.equals(castOther.getVemployeeName())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getDattFromDate() == castOther.getDattFromDate()) || (this
						.getDattFromDate() != null
						&& castOther.getDattFromDate() != null && this
						.getDattFromDate().equals(castOther.getDattFromDate())))
				&& ((this.getInTime() == castOther.getInTime()) || (this
						.getInTime() != null && castOther.getInTime() != null && this
						.getInTime().equals(castOther.getInTime())))
				&& ((this.getDattToDate() == castOther.getDattToDate()) || (this
						.getDattToDate() != null
						&& castOther.getDattToDate() != null && this
						.getDattToDate().equals(castOther.getDattToDate())))
				&& ((this.getOutTime() == castOther.getOutTime()) || (this
						.getOutTime() != null && castOther.getOutTime() != null && this
						.getOutTime().equals(castOther.getOutTime())))
				&& ((this.getVreason() == castOther.getVreason()) || (this
						.getVreason() != null && castOther.getVreason() != null && this
						.getVreason().equals(castOther.getVreason())))
				&& ((this.getVpermitBy() == castOther.getVpermitBy()) || (this
						.getVpermitBy() != null
						&& castOther.getVpermitBy() != null && this
						.getVpermitBy().equals(castOther.getVpermitBy())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAutoId();
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37 * result
				+ (getVfingerId() == null ? 0 : this.getVfingerId().hashCode());
		result = 37
				* result
				+ (getVemployeeName() == null ? 0 : this.getVemployeeName()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getDattFromDate() == null ? 0 : this.getDattFromDate()
						.hashCode());
		result = 37 * result
				+ (getInTime() == null ? 0 : this.getInTime().hashCode());
		result = 37
				* result
				+ (getDattToDate() == null ? 0 : this.getDattToDate()
						.hashCode());
		result = 37 * result
				+ (getOutTime() == null ? 0 : this.getOutTime().hashCode());
		result = 37 * result
				+ (getVreason() == null ? 0 : this.getVreason().hashCode());
		result = 37 * result
				+ (getVpermitBy() == null ? 0 : this.getVpermitBy().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
