package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbAttendanceManually generated by hbm2java
 */
public class TbAttendanceManually implements java.io.Serializable {

	private TbAttendanceManuallyId id;

	public TbAttendanceManually() {
	}

	public TbAttendanceManually(TbAttendanceManuallyId id) {
		this.id = id;
	}

	public TbAttendanceManuallyId getId() {
		return this.id;
	}

	public void setId(TbAttendanceManuallyId id) {
		this.id = id;
	}

}
