package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbAttendenceRecord generated by hbm2java
 */
public class TbAttendenceRecord implements java.io.Serializable {

	private TbAttendenceRecordId id;

	public TbAttendenceRecord() {
	}

	public TbAttendenceRecord(TbAttendenceRecordId id) {
		this.id = id;
	}

	public TbAttendenceRecordId getId() {
		return this.id;
	}

	public void setId(TbAttendenceRecordId id) {
		this.id = id;
	}

}
