package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAuthentication generated by hbm2java
 */
public class TbAuthentication implements java.io.Serializable {

	private int sl;
	private Integer userId;
	private String menuId;
	private Date insertTime;
	private Integer createBy;
	private String menuCaption;

	public TbAuthentication() {
	}

	public TbAuthentication(int sl) {
		this.sl = sl;
	}

	public TbAuthentication(int sl, Integer userId, String menuId,
			Date insertTime, Integer createBy, String menuCaption) {
		this.sl = sl;
		this.userId = userId;
		this.menuId = menuId;
		this.insertTime = insertTime;
		this.createBy = createBy;
		this.menuCaption = menuCaption;
	}

	public int getSl() {
		return this.sl;
	}

	public void setSl(int sl) {
		this.sl = sl;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public String getMenuCaption() {
		return this.menuCaption;
	}

	public void setMenuCaption(String menuCaption) {
		this.menuCaption = menuCaption;
	}

}
