package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbBonusDetailsId generated by hbm2java
 */
public class TbBonusDetailsId implements java.io.Serializable {

	private int iautoId;
	private Date dgenerateDate;
	private String igenerateType;
	private String vsectionId;
	private String vemployeeId;
	private String vdesignationId;
	private Integer iyear;
	private Integer imonth;
	private String vmonth;
	private BigDecimal mbasic;
	private BigDecimal mbasicBonusPercent;
	private BigDecimal mbasicBonusAmount;
	private BigDecimal mgross;
	private BigDecimal mgrossBonusPercent;
	private BigDecimal mgrossBonusAmount;
	private BigDecimal mrevenueStamp;
	private String vreligion;
	private String voccasion;
	private String vbankId;
	private String vbankBranchId;
	private String vaccountNo;
	private String vuserId;
	private String vuserIp;
	private String dentryTime;

	public TbBonusDetailsId() {
	}

	public TbBonusDetailsId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbBonusDetailsId(int iautoId, Date dgenerateDate,
			String igenerateType, String vsectionId, String vemployeeId,
			String vdesignationId, Integer iyear, Integer imonth,
			String vmonth, BigDecimal mbasic, BigDecimal mbasicBonusPercent,
			BigDecimal mbasicBonusAmount, BigDecimal mgross,
			BigDecimal mgrossBonusPercent, BigDecimal mgrossBonusAmount,
			BigDecimal mrevenueStamp, String vreligion, String voccasion,
			String vbankId, String vbankBranchId, String vaccountNo,
			String vuserId, String vuserIp, String dentryTime) {
		this.iautoId = iautoId;
		this.dgenerateDate = dgenerateDate;
		this.igenerateType = igenerateType;
		this.vsectionId = vsectionId;
		this.vemployeeId = vemployeeId;
		this.vdesignationId = vdesignationId;
		this.iyear = iyear;
		this.imonth = imonth;
		this.vmonth = vmonth;
		this.mbasic = mbasic;
		this.mbasicBonusPercent = mbasicBonusPercent;
		this.mbasicBonusAmount = mbasicBonusAmount;
		this.mgross = mgross;
		this.mgrossBonusPercent = mgrossBonusPercent;
		this.mgrossBonusAmount = mgrossBonusAmount;
		this.mrevenueStamp = mrevenueStamp;
		this.vreligion = vreligion;
		this.voccasion = voccasion;
		this.vbankId = vbankId;
		this.vbankBranchId = vbankBranchId;
		this.vaccountNo = vaccountNo;
		this.vuserId = vuserId;
		this.vuserIp = vuserIp;
		this.dentryTime = dentryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public Date getDgenerateDate() {
		return this.dgenerateDate;
	}

	public void setDgenerateDate(Date dgenerateDate) {
		this.dgenerateDate = dgenerateDate;
	}

	public String getIgenerateType() {
		return this.igenerateType;
	}

	public void setIgenerateType(String igenerateType) {
		this.igenerateType = igenerateType;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public Integer getIyear() {
		return this.iyear;
	}

	public void setIyear(Integer iyear) {
		this.iyear = iyear;
	}

	public Integer getImonth() {
		return this.imonth;
	}

	public void setImonth(Integer imonth) {
		this.imonth = imonth;
	}

	public String getVmonth() {
		return this.vmonth;
	}

	public void setVmonth(String vmonth) {
		this.vmonth = vmonth;
	}

	public BigDecimal getMbasic() {
		return this.mbasic;
	}

	public void setMbasic(BigDecimal mbasic) {
		this.mbasic = mbasic;
	}

	public BigDecimal getMbasicBonusPercent() {
		return this.mbasicBonusPercent;
	}

	public void setMbasicBonusPercent(BigDecimal mbasicBonusPercent) {
		this.mbasicBonusPercent = mbasicBonusPercent;
	}

	public BigDecimal getMbasicBonusAmount() {
		return this.mbasicBonusAmount;
	}

	public void setMbasicBonusAmount(BigDecimal mbasicBonusAmount) {
		this.mbasicBonusAmount = mbasicBonusAmount;
	}

	public BigDecimal getMgross() {
		return this.mgross;
	}

	public void setMgross(BigDecimal mgross) {
		this.mgross = mgross;
	}

	public BigDecimal getMgrossBonusPercent() {
		return this.mgrossBonusPercent;
	}

	public void setMgrossBonusPercent(BigDecimal mgrossBonusPercent) {
		this.mgrossBonusPercent = mgrossBonusPercent;
	}

	public BigDecimal getMgrossBonusAmount() {
		return this.mgrossBonusAmount;
	}

	public void setMgrossBonusAmount(BigDecimal mgrossBonusAmount) {
		this.mgrossBonusAmount = mgrossBonusAmount;
	}

	public BigDecimal getMrevenueStamp() {
		return this.mrevenueStamp;
	}

	public void setMrevenueStamp(BigDecimal mrevenueStamp) {
		this.mrevenueStamp = mrevenueStamp;
	}

	public String getVreligion() {
		return this.vreligion;
	}

	public void setVreligion(String vreligion) {
		this.vreligion = vreligion;
	}

	public String getVoccasion() {
		return this.voccasion;
	}

	public void setVoccasion(String voccasion) {
		this.voccasion = voccasion;
	}

	public String getVbankId() {
		return this.vbankId;
	}

	public void setVbankId(String vbankId) {
		this.vbankId = vbankId;
	}

	public String getVbankBranchId() {
		return this.vbankBranchId;
	}

	public void setVbankBranchId(String vbankBranchId) {
		this.vbankBranchId = vbankBranchId;
	}

	public String getVaccountNo() {
		return this.vaccountNo;
	}

	public void setVaccountNo(String vaccountNo) {
		this.vaccountNo = vaccountNo;
	}

	public String getVuserId() {
		return this.vuserId;
	}

	public void setVuserId(String vuserId) {
		this.vuserId = vuserId;
	}

	public String getVuserIp() {
		return this.vuserIp;
	}

	public void setVuserIp(String vuserIp) {
		this.vuserIp = vuserIp;
	}

	public String getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(String dentryTime) {
		this.dentryTime = dentryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbBonusDetailsId))
			return false;
		TbBonusDetailsId castOther = (TbBonusDetailsId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getDgenerateDate() == castOther.getDgenerateDate()) || (this
						.getDgenerateDate() != null
						&& castOther.getDgenerateDate() != null && this
						.getDgenerateDate()
						.equals(castOther.getDgenerateDate())))
				&& ((this.getIgenerateType() == castOther.getIgenerateType()) || (this
						.getIgenerateType() != null
						&& castOther.getIgenerateType() != null && this
						.getIgenerateType()
						.equals(castOther.getIgenerateType())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getIyear() == castOther.getIyear()) || (this
						.getIyear() != null && castOther.getIyear() != null && this
						.getIyear().equals(castOther.getIyear())))
				&& ((this.getImonth() == castOther.getImonth()) || (this
						.getImonth() != null && castOther.getImonth() != null && this
						.getImonth().equals(castOther.getImonth())))
				&& ((this.getVmonth() == castOther.getVmonth()) || (this
						.getVmonth() != null && castOther.getVmonth() != null && this
						.getVmonth().equals(castOther.getVmonth())))
				&& ((this.getMbasic() == castOther.getMbasic()) || (this
						.getMbasic() != null && castOther.getMbasic() != null && this
						.getMbasic().equals(castOther.getMbasic())))
				&& ((this.getMbasicBonusPercent() == castOther
						.getMbasicBonusPercent()) || (this
						.getMbasicBonusPercent() != null
						&& castOther.getMbasicBonusPercent() != null && this
						.getMbasicBonusPercent().equals(
								castOther.getMbasicBonusPercent())))
				&& ((this.getMbasicBonusAmount() == castOther
						.getMbasicBonusAmount()) || (this
						.getMbasicBonusAmount() != null
						&& castOther.getMbasicBonusAmount() != null && this
						.getMbasicBonusAmount().equals(
								castOther.getMbasicBonusAmount())))
				&& ((this.getMgross() == castOther.getMgross()) || (this
						.getMgross() != null && castOther.getMgross() != null && this
						.getMgross().equals(castOther.getMgross())))
				&& ((this.getMgrossBonusPercent() == castOther
						.getMgrossBonusPercent()) || (this
						.getMgrossBonusPercent() != null
						&& castOther.getMgrossBonusPercent() != null && this
						.getMgrossBonusPercent().equals(
								castOther.getMgrossBonusPercent())))
				&& ((this.getMgrossBonusAmount() == castOther
						.getMgrossBonusAmount()) || (this
						.getMgrossBonusAmount() != null
						&& castOther.getMgrossBonusAmount() != null && this
						.getMgrossBonusAmount().equals(
								castOther.getMgrossBonusAmount())))
				&& ((this.getMrevenueStamp() == castOther.getMrevenueStamp()) || (this
						.getMrevenueStamp() != null
						&& castOther.getMrevenueStamp() != null && this
						.getMrevenueStamp()
						.equals(castOther.getMrevenueStamp())))
				&& ((this.getVreligion() == castOther.getVreligion()) || (this
						.getVreligion() != null
						&& castOther.getVreligion() != null && this
						.getVreligion().equals(castOther.getVreligion())))
				&& ((this.getVoccasion() == castOther.getVoccasion()) || (this
						.getVoccasion() != null
						&& castOther.getVoccasion() != null && this
						.getVoccasion().equals(castOther.getVoccasion())))
				&& ((this.getVbankId() == castOther.getVbankId()) || (this
						.getVbankId() != null && castOther.getVbankId() != null && this
						.getVbankId().equals(castOther.getVbankId())))
				&& ((this.getVbankBranchId() == castOther.getVbankBranchId()) || (this
						.getVbankBranchId() != null
						&& castOther.getVbankBranchId() != null && this
						.getVbankBranchId()
						.equals(castOther.getVbankBranchId())))
				&& ((this.getVaccountNo() == castOther.getVaccountNo()) || (this
						.getVaccountNo() != null
						&& castOther.getVaccountNo() != null && this
						.getVaccountNo().equals(castOther.getVaccountNo())))
				&& ((this.getVuserId() == castOther.getVuserId()) || (this
						.getVuserId() != null && castOther.getVuserId() != null && this
						.getVuserId().equals(castOther.getVuserId())))
				&& ((this.getVuserIp() == castOther.getVuserIp()) || (this
						.getVuserIp() != null && castOther.getVuserIp() != null && this
						.getVuserIp().equals(castOther.getVuserIp())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37
				* result
				+ (getDgenerateDate() == null ? 0 : this.getDgenerateDate()
						.hashCode());
		result = 37
				* result
				+ (getIgenerateType() == null ? 0 : this.getIgenerateType()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37 * result
				+ (getIyear() == null ? 0 : this.getIyear().hashCode());
		result = 37 * result
				+ (getImonth() == null ? 0 : this.getImonth().hashCode());
		result = 37 * result
				+ (getVmonth() == null ? 0 : this.getVmonth().hashCode());
		result = 37 * result
				+ (getMbasic() == null ? 0 : this.getMbasic().hashCode());
		result = 37
				* result
				+ (getMbasicBonusPercent() == null ? 0 : this
						.getMbasicBonusPercent().hashCode());
		result = 37
				* result
				+ (getMbasicBonusAmount() == null ? 0 : this
						.getMbasicBonusAmount().hashCode());
		result = 37 * result
				+ (getMgross() == null ? 0 : this.getMgross().hashCode());
		result = 37
				* result
				+ (getMgrossBonusPercent() == null ? 0 : this
						.getMgrossBonusPercent().hashCode());
		result = 37
				* result
				+ (getMgrossBonusAmount() == null ? 0 : this
						.getMgrossBonusAmount().hashCode());
		result = 37
				* result
				+ (getMrevenueStamp() == null ? 0 : this.getMrevenueStamp()
						.hashCode());
		result = 37 * result
				+ (getVreligion() == null ? 0 : this.getVreligion().hashCode());
		result = 37 * result
				+ (getVoccasion() == null ? 0 : this.getVoccasion().hashCode());
		result = 37 * result
				+ (getVbankId() == null ? 0 : this.getVbankId().hashCode());
		result = 37
				* result
				+ (getVbankBranchId() == null ? 0 : this.getVbankBranchId()
						.hashCode());
		result = 37
				* result
				+ (getVaccountNo() == null ? 0 : this.getVaccountNo()
						.hashCode());
		result = 37 * result
				+ (getVuserId() == null ? 0 : this.getVuserId().hashCode());
		result = 37 * result
				+ (getVuserIp() == null ? 0 : this.getVuserIp().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		return result;
	}

}
