package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbBonusDetails generated by hbm2java
 */
public class TbBonusDetails implements java.io.Serializable {

	private TbBonusDetailsId id;

	public TbBonusDetails() {
	}

	public TbBonusDetails(TbBonusDetailsId id) {
		this.id = id;
	}

	public TbBonusDetailsId getId() {
		return this.id;
	}

	public void setId(TbBonusDetailsId id) {
		this.id = id;
	}

}
