package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbDeleteProximityIdId generated by hbm2java
 */
public class TbDeleteProximityIdId implements java.io.Serializable {

	private int iautoId;
	private Date ddate;
	private String vemployeeId;
	private String vproximityId;
	private String vdesignationId;
	private String vsectionId;
	private String vreason;
	private String userName;
	private String userIp;
	private Date dentryTime;

	public TbDeleteProximityIdId() {
	}

	public TbDeleteProximityIdId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbDeleteProximityIdId(int iautoId, Date ddate, String vemployeeId,
			String vproximityId, String vdesignationId, String vsectionId,
			String vreason, String userName, String userIp, Date dentryTime) {
		this.iautoId = iautoId;
		this.ddate = ddate;
		this.vemployeeId = vemployeeId;
		this.vproximityId = vproximityId;
		this.vdesignationId = vdesignationId;
		this.vsectionId = vsectionId;
		this.vreason = vreason;
		this.userName = userName;
		this.userIp = userIp;
		this.dentryTime = dentryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVproximityId() {
		return this.vproximityId;
	}

	public void setVproximityId(String vproximityId) {
		this.vproximityId = vproximityId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVreason() {
		return this.vreason;
	}

	public void setVreason(String vreason) {
		this.vreason = vreason;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(Date dentryTime) {
		this.dentryTime = dentryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDeleteProximityIdId))
			return false;
		TbDeleteProximityIdId castOther = (TbDeleteProximityIdId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getDdate() == castOther.getDdate()) || (this
						.getDdate() != null && castOther.getDdate() != null && this
						.getDdate().equals(castOther.getDdate())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVproximityId() == castOther.getVproximityId()) || (this
						.getVproximityId() != null
						&& castOther.getVproximityId() != null && this
						.getVproximityId().equals(castOther.getVproximityId())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVreason() == castOther.getVreason()) || (this
						.getVreason() != null && castOther.getVreason() != null && this
						.getVreason().equals(castOther.getVreason())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result
				+ (getDdate() == null ? 0 : this.getDdate().hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVproximityId() == null ? 0 : this.getVproximityId()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37 * result
				+ (getVreason() == null ? 0 : this.getVreason().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		return result;
	}

}
