package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbDesignInfoId generated by hbm2java
 */
public class TbDesignInfoId implements java.io.Serializable {

	private int iautoId;
	private String vdesignId;
	private String vdesignName;
	private String vdesignDescription;
	private String userId;
	private String userIp;
	private Date entryTime;

	public TbDesignInfoId() {
	}

	public TbDesignInfoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbDesignInfoId(int iautoId, String vdesignId, String vdesignName,
			String vdesignDescription, String userId, String userIp,
			Date entryTime) {
		this.iautoId = iautoId;
		this.vdesignId = vdesignId;
		this.vdesignName = vdesignName;
		this.vdesignDescription = vdesignDescription;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public String getVdesignId() {
		return this.vdesignId;
	}

	public void setVdesignId(String vdesignId) {
		this.vdesignId = vdesignId;
	}

	public String getVdesignName() {
		return this.vdesignName;
	}

	public void setVdesignName(String vdesignName) {
		this.vdesignName = vdesignName;
	}

	public String getVdesignDescription() {
		return this.vdesignDescription;
	}

	public void setVdesignDescription(String vdesignDescription) {
		this.vdesignDescription = vdesignDescription;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDesignInfoId))
			return false;
		TbDesignInfoId castOther = (TbDesignInfoId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVdesignId() == castOther.getVdesignId()) || (this
						.getVdesignId() != null
						&& castOther.getVdesignId() != null && this
						.getVdesignId().equals(castOther.getVdesignId())))
				&& ((this.getVdesignName() == castOther.getVdesignName()) || (this
						.getVdesignName() != null
						&& castOther.getVdesignName() != null && this
						.getVdesignName().equals(castOther.getVdesignName())))
				&& ((this.getVdesignDescription() == castOther
						.getVdesignDescription()) || (this
						.getVdesignDescription() != null
						&& castOther.getVdesignDescription() != null && this
						.getVdesignDescription().equals(
								castOther.getVdesignDescription())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result
				+ (getVdesignId() == null ? 0 : this.getVdesignId().hashCode());
		result = 37
				* result
				+ (getVdesignName() == null ? 0 : this.getVdesignName()
						.hashCode());
		result = 37
				* result
				+ (getVdesignDescription() == null ? 0 : this
						.getVdesignDescription().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
