package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbDepreciationId generated by hbm2java
 */
public class TbDepreciationId implements java.io.Serializable {

	private String voucherNo;
	private Date date;
	private String assetId;
	private String narration;
	private BigDecimal depreciation;
	private String voucherType;

	public TbDepreciationId() {
	}

	public TbDepreciationId(String voucherNo, Date date, String assetId,
			String narration, BigDecimal depreciation, String voucherType) {
		this.voucherNo = voucherNo;
		this.date = date;
		this.assetId = assetId;
		this.narration = narration;
		this.depreciation = depreciation;
		this.voucherType = voucherType;
	}

	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public BigDecimal getDepreciation() {
		return this.depreciation;
	}

	public void setDepreciation(BigDecimal depreciation) {
		this.depreciation = depreciation;
	}

	public String getVoucherType() {
		return this.voucherType;
	}

	public void setVoucherType(String voucherType) {
		this.voucherType = voucherType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDepreciationId))
			return false;
		TbDepreciationId castOther = (TbDepreciationId) other;

		return ((this.getVoucherNo() == castOther.getVoucherNo()) || (this
				.getVoucherNo() != null && castOther.getVoucherNo() != null && this
				.getVoucherNo().equals(castOther.getVoucherNo())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null && castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getNarration() == castOther.getNarration()) || (this
						.getNarration() != null
						&& castOther.getNarration() != null && this
						.getNarration().equals(castOther.getNarration())))
				&& ((this.getDepreciation() == castOther.getDepreciation()) || (this
						.getDepreciation() != null
						&& castOther.getDepreciation() != null && this
						.getDepreciation().equals(castOther.getDepreciation())))
				&& ((this.getVoucherType() == castOther.getVoucherType()) || (this
						.getVoucherType() != null
						&& castOther.getVoucherType() != null && this
						.getVoucherType().equals(castOther.getVoucherType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVoucherNo() == null ? 0 : this.getVoucherNo().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result
				+ (getNarration() == null ? 0 : this.getNarration().hashCode());
		result = 37
				* result
				+ (getDepreciation() == null ? 0 : this.getDepreciation()
						.hashCode());
		result = 37
				* result
				+ (getVoucherType() == null ? 0 : this.getVoucherType()
						.hashCode());
		return result;
	}

}
