package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbDesignInfo generated by hbm2java
 */
public class TbDesignInfo implements java.io.Serializable {

	private TbDesignInfoId id;

	public TbDesignInfo() {
	}

	public TbDesignInfo(TbDesignInfoId id) {
		this.id = id;
	}

	public TbDesignInfoId getId() {
		return this.id;
	}

	public void setId(TbDesignInfoId id) {
		this.id = id;
	}

}
