package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbDeleteProximityId generated by hbm2java
 */
public class TbDeleteProximityId implements java.io.Serializable {

	private TbDeleteProximityIdId id;

	public TbDeleteProximityId() {
	}

	public TbDeleteProximityId(TbDeleteProximityIdId id) {
		this.id = id;
	}

	public TbDeleteProximityIdId getId() {
		return this.id;
	}

	public void setId(TbDeleteProximityIdId id) {
		this.id = id;
	}

}
