package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbDesignationInfo generated by hbm2java
 */
public class TbDesignationInfo implements java.io.Serializable {

	private int designationId;
	private int autoId;
	private String designationName;
	private String designationNameBangla;
	private String userIp;
	private String userName;
	private Date entryTime;

	public TbDesignationInfo() {
	}

	public TbDesignationInfo(int designationId, int autoId,
			String designationName, String designationNameBangla,
			String userIp, String userName, Date entryTime) {
		this.designationId = designationId;
		this.autoId = autoId;
		this.designationName = designationName;
		this.designationNameBangla = designationNameBangla;
		this.userIp = userIp;
		this.userName = userName;
		this.entryTime = entryTime;
	}

	public int getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(int designationId) {
		this.designationId = designationId;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public String getDesignationNameBangla() {
		return this.designationNameBangla;
	}

	public void setDesignationNameBangla(String designationNameBangla) {
		this.designationNameBangla = designationNameBangla;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
