package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbDivisionTarget generated by hbm2java
 */
public class TbDivisionTarget implements java.io.Serializable {

	private TbDivisionTargetId id;

	public TbDivisionTarget() {
	}

	public TbDivisionTarget(TbDivisionTargetId id) {
		this.id = id;
	}

	public TbDivisionTargetId getId() {
		return this.id;
	}

	public void setId(TbDivisionTargetId id) {
		this.id = id;
	}

}
