package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbDivisionTargetId generated by hbm2java
 */
public class TbDivisionTargetId implements java.io.Serializable {

	private int iautoId;
	private String vdivisionId;
	private String vdivisionName;
	private String vdivisionIncharge;
	private String vtargetQty;
	private Date dtargetDate;
	private String userId;
	private String userIp;
	private String entryTime;

	public TbDivisionTargetId() {
	}

	public TbDivisionTargetId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbDivisionTargetId(int iautoId, String vdivisionId,
			String vdivisionName, String vdivisionIncharge, String vtargetQty,
			Date dtargetDate, String userId, String userIp, String entryTime) {
		this.iautoId = iautoId;
		this.vdivisionId = vdivisionId;
		this.vdivisionName = vdivisionName;
		this.vdivisionIncharge = vdivisionIncharge;
		this.vtargetQty = vtargetQty;
		this.dtargetDate = dtargetDate;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public String getVdivisionId() {
		return this.vdivisionId;
	}

	public void setVdivisionId(String vdivisionId) {
		this.vdivisionId = vdivisionId;
	}

	public String getVdivisionName() {
		return this.vdivisionName;
	}

	public void setVdivisionName(String vdivisionName) {
		this.vdivisionName = vdivisionName;
	}

	public String getVdivisionIncharge() {
		return this.vdivisionIncharge;
	}

	public void setVdivisionIncharge(String vdivisionIncharge) {
		this.vdivisionIncharge = vdivisionIncharge;
	}

	public String getVtargetQty() {
		return this.vtargetQty;
	}

	public void setVtargetQty(String vtargetQty) {
		this.vtargetQty = vtargetQty;
	}

	public Date getDtargetDate() {
		return this.dtargetDate;
	}

	public void setDtargetDate(Date dtargetDate) {
		this.dtargetDate = dtargetDate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public String getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(String entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDivisionTargetId))
			return false;
		TbDivisionTargetId castOther = (TbDivisionTargetId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVdivisionId() == castOther.getVdivisionId()) || (this
						.getVdivisionId() != null
						&& castOther.getVdivisionId() != null && this
						.getVdivisionId().equals(castOther.getVdivisionId())))
				&& ((this.getVdivisionName() == castOther.getVdivisionName()) || (this
						.getVdivisionName() != null
						&& castOther.getVdivisionName() != null && this
						.getVdivisionName()
						.equals(castOther.getVdivisionName())))
				&& ((this.getVdivisionIncharge() == castOther
						.getVdivisionIncharge()) || (this
						.getVdivisionIncharge() != null
						&& castOther.getVdivisionIncharge() != null && this
						.getVdivisionIncharge().equals(
								castOther.getVdivisionIncharge())))
				&& ((this.getVtargetQty() == castOther.getVtargetQty()) || (this
						.getVtargetQty() != null
						&& castOther.getVtargetQty() != null && this
						.getVtargetQty().equals(castOther.getVtargetQty())))
				&& ((this.getDtargetDate() == castOther.getDtargetDate()) || (this
						.getDtargetDate() != null
						&& castOther.getDtargetDate() != null && this
						.getDtargetDate().equals(castOther.getDtargetDate())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37
				* result
				+ (getVdivisionId() == null ? 0 : this.getVdivisionId()
						.hashCode());
		result = 37
				* result
				+ (getVdivisionName() == null ? 0 : this.getVdivisionName()
						.hashCode());
		result = 37
				* result
				+ (getVdivisionIncharge() == null ? 0 : this
						.getVdivisionIncharge().hashCode());
		result = 37
				* result
				+ (getVtargetQty() == null ? 0 : this.getVtargetQty()
						.hashCode());
		result = 37
				* result
				+ (getDtargetDate() == null ? 0 : this.getDtargetDate()
						.hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
