package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbEducation generated by hbm2java
 */
public class TbEducation implements java.io.Serializable {

	private TbEducationId id;

	public TbEducation() {
	}

	public TbEducation(TbEducationId id) {
		this.id = id;
	}

	public TbEducationId getId() {
		return this.id;
	}

	public void setId(TbEducationId id) {
		this.id = id;
	}

}
