package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbEmployeeAttendance generated by hbm2java
 */
public class TbEmployeeAttendance implements java.io.Serializable {

	private TbEmployeeAttendanceId id;

	public TbEmployeeAttendance() {
	}

	public TbEmployeeAttendance(TbEmployeeAttendanceId id) {
		this.id = id;
	}

	public TbEmployeeAttendanceId getId() {
		return this.id;
	}

	public void setId(TbEmployeeAttendanceId id) {
		this.id = id;
	}

}
