package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbEmpLeaveInfo generated by hbm2java
 */
public class TbEmpLeaveInfo implements java.io.Serializable {

	private TbEmpLeaveInfoId id;

	public TbEmpLeaveInfo() {
	}

	public TbEmpLeaveInfo(TbEmpLeaveInfoId id) {
		this.id = id;
	}

	public TbEmpLeaveInfoId getId() {
		return this.id;
	}

	public void setId(TbEmpLeaveInfoId id) {
		this.id = id;
	}

}
