package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbEmpLeaveApplicationDetails generated by hbm2java
 */
public class TbEmpLeaveApplicationDetails implements java.io.Serializable {

	private TbEmpLeaveApplicationDetailsId id;

	public TbEmpLeaveApplicationDetails() {
	}

	public TbEmpLeaveApplicationDetails(TbEmpLeaveApplicationDetailsId id) {
		this.id = id;
	}

	public TbEmpLeaveApplicationDetailsId getId() {
		return this.id;
	}

	public void setId(TbEmpLeaveApplicationDetailsId id) {
		this.id = id;
	}

}
