package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbEmployeeInfo generated by hbm2java
 */
public class TbEmployeeInfo implements java.io.Serializable {

	private String vemployeeId;
	private int iserialNo;
	private String employeeCode;
	private Integer ifingerId;
	private String vproximityId;
	private String vemployeeName;
	private String vemployeeNameBan;
	private String vreligion;
	private String vcontact;
	private String vemail;
	private String vgender;
	private Date ddateOfBirth;
	private String dateOfBirthLocation;
	private String vnationality;
	private String nid;
	private String nidLocation;
	private String vemployeeType;
	private Date dapplicationDate;
	private String applicationDateLocation;
	private Date dinterviewDate;
	private Date djoiningDate;
	private String joiningDateLocation;
	private Date dconfirmationDate;
	private String confirmationDateLocation;
	private String vstatus;
	private Integer istatus;
	private Date dstatusDate;
	private String vdepartmentId;
	private String vsectionId;
	private String vdesignationId;
	private String vfloor;
	private String vline;
	private String vgrade;
	private String imageLocation;
	private String vfatherName;
	private String vmotherName;
	private String vpermanentAddress;
	private String vmailingAddress;
	private String vbloodGroup;
	private String vmeritalStatus;
	private Date dmarriageDate;
	private String vspouseName;
	private String vspouseOccupation;
	private Integer inoOfChild;
	private String vn1name;
	private String vn1relation;
	private String vn2name;
	private String vn2relation;
	private String votherQualification;
	private String vcomputerSkill;
	private BigDecimal mmonthlySalary;
	private String vuserName;
	private Date ddateTime;
	private String vpcIp;
	private String birthImage;
	private String nidImage;
	private String applicationImage;
	private String joiningImage;
	private String confirmImage;
	private String subUnitId;
	private BigDecimal mhouseRent;
	private Integer otStatus;
	private BigDecimal mmedicalAllowance;
	private BigDecimal mconAllowance;
	private BigDecimal mclinical;
	private BigDecimal mspecial;
	private BigDecimal mnonPractice;
	private BigDecimal mothersAllowance;
	private BigDecimal mprovidentFund;
	private BigDecimal mroomCharge;
	private BigDecimal mbreej;
	private BigDecimal mkhichuri;
	private BigDecimal mkfund;
	private Integer bankId;
	private String bankName;
	private Integer bankBranchId;
	private String branchName;
	private String accountNo;
	private Integer userId;
	private String userIp;
	private Date entryTime;

	public TbEmployeeInfo() {
	}

	public TbEmployeeInfo(String vemployeeId, int iserialNo) {
		this.vemployeeId = vemployeeId;
		this.iserialNo = iserialNo;
	}

	public TbEmployeeInfo(String vemployeeId, int iserialNo,
			String employeeCode, Integer ifingerId, String vproximityId,
			String vemployeeName, String vemployeeNameBan, String vreligion,
			String vcontact, String vemail, String vgender, Date ddateOfBirth,
			String dateOfBirthLocation, String vnationality, String nid,
			String nidLocation, String vemployeeType, Date dapplicationDate,
			String applicationDateLocation, Date dinterviewDate,
			Date djoiningDate, String joiningDateLocation,
			Date dconfirmationDate, String confirmationDateLocation,
			String vstatus, Integer istatus, Date dstatusDate,
			String vdepartmentId, String vsectionId, String vdesignationId,
			String vfloor, String vline, String vgrade, String imageLocation,
			String vfatherName, String vmotherName, String vpermanentAddress,
			String vmailingAddress, String vbloodGroup, String vmeritalStatus,
			Date dmarriageDate, String vspouseName, String vspouseOccupation,
			Integer inoOfChild, String vn1name, String vn1relation,
			String vn2name, String vn2relation, String votherQualification,
			String vcomputerSkill, BigDecimal mmonthlySalary, String vuserName,
			Date ddateTime, String vpcIp, String birthImage, String nidImage,
			String applicationImage, String joiningImage, String confirmImage,
			String subUnitId, BigDecimal mhouseRent, Integer otStatus,
			BigDecimal mmedicalAllowance, BigDecimal mconAllowance,
			BigDecimal mclinical, BigDecimal mspecial, BigDecimal mnonPractice,
			BigDecimal mothersAllowance, BigDecimal mprovidentFund,
			BigDecimal mroomCharge, BigDecimal mbreej, BigDecimal mkhichuri,
			BigDecimal mkfund, Integer bankId, String bankName,
			Integer bankBranchId, String branchName, String accountNo,
			Integer userId, String userIp, Date entryTime) {
		this.vemployeeId = vemployeeId;
		this.iserialNo = iserialNo;
		this.employeeCode = employeeCode;
		this.ifingerId = ifingerId;
		this.vproximityId = vproximityId;
		this.vemployeeName = vemployeeName;
		this.vemployeeNameBan = vemployeeNameBan;
		this.vreligion = vreligion;
		this.vcontact = vcontact;
		this.vemail = vemail;
		this.vgender = vgender;
		this.ddateOfBirth = ddateOfBirth;
		this.dateOfBirthLocation = dateOfBirthLocation;
		this.vnationality = vnationality;
		this.nid = nid;
		this.nidLocation = nidLocation;
		this.vemployeeType = vemployeeType;
		this.dapplicationDate = dapplicationDate;
		this.applicationDateLocation = applicationDateLocation;
		this.dinterviewDate = dinterviewDate;
		this.djoiningDate = djoiningDate;
		this.joiningDateLocation = joiningDateLocation;
		this.dconfirmationDate = dconfirmationDate;
		this.confirmationDateLocation = confirmationDateLocation;
		this.vstatus = vstatus;
		this.istatus = istatus;
		this.dstatusDate = dstatusDate;
		this.vdepartmentId = vdepartmentId;
		this.vsectionId = vsectionId;
		this.vdesignationId = vdesignationId;
		this.vfloor = vfloor;
		this.vline = vline;
		this.vgrade = vgrade;
		this.imageLocation = imageLocation;
		this.vfatherName = vfatherName;
		this.vmotherName = vmotherName;
		this.vpermanentAddress = vpermanentAddress;
		this.vmailingAddress = vmailingAddress;
		this.vbloodGroup = vbloodGroup;
		this.vmeritalStatus = vmeritalStatus;
		this.dmarriageDate = dmarriageDate;
		this.vspouseName = vspouseName;
		this.vspouseOccupation = vspouseOccupation;
		this.inoOfChild = inoOfChild;
		this.vn1name = vn1name;
		this.vn1relation = vn1relation;
		this.vn2name = vn2name;
		this.vn2relation = vn2relation;
		this.votherQualification = votherQualification;
		this.vcomputerSkill = vcomputerSkill;
		this.mmonthlySalary = mmonthlySalary;
		this.vuserName = vuserName;
		this.ddateTime = ddateTime;
		this.vpcIp = vpcIp;
		this.birthImage = birthImage;
		this.nidImage = nidImage;
		this.applicationImage = applicationImage;
		this.joiningImage = joiningImage;
		this.confirmImage = confirmImage;
		this.subUnitId = subUnitId;
		this.mhouseRent = mhouseRent;
		this.otStatus = otStatus;
		this.mmedicalAllowance = mmedicalAllowance;
		this.mconAllowance = mconAllowance;
		this.mclinical = mclinical;
		this.mspecial = mspecial;
		this.mnonPractice = mnonPractice;
		this.mothersAllowance = mothersAllowance;
		this.mprovidentFund = mprovidentFund;
		this.mroomCharge = mroomCharge;
		this.mbreej = mbreej;
		this.mkhichuri = mkhichuri;
		this.mkfund = mkfund;
		this.bankId = bankId;
		this.bankName = bankName;
		this.bankBranchId = bankBranchId;
		this.branchName = branchName;
		this.accountNo = accountNo;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public int getIserialNo() {
		return this.iserialNo;
	}

	public void setIserialNo(int iserialNo) {
		this.iserialNo = iserialNo;
	}

	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public Integer getIfingerId() {
		return this.ifingerId;
	}

	public void setIfingerId(Integer ifingerId) {
		this.ifingerId = ifingerId;
	}

	public String getVproximityId() {
		return this.vproximityId;
	}

	public void setVproximityId(String vproximityId) {
		this.vproximityId = vproximityId;
	}

	public String getVemployeeName() {
		return this.vemployeeName;
	}

	public void setVemployeeName(String vemployeeName) {
		this.vemployeeName = vemployeeName;
	}

	public String getVemployeeNameBan() {
		return this.vemployeeNameBan;
	}

	public void setVemployeeNameBan(String vemployeeNameBan) {
		this.vemployeeNameBan = vemployeeNameBan;
	}

	public String getVreligion() {
		return this.vreligion;
	}

	public void setVreligion(String vreligion) {
		this.vreligion = vreligion;
	}

	public String getVcontact() {
		return this.vcontact;
	}

	public void setVcontact(String vcontact) {
		this.vcontact = vcontact;
	}

	public String getVemail() {
		return this.vemail;
	}

	public void setVemail(String vemail) {
		this.vemail = vemail;
	}

	public String getVgender() {
		return this.vgender;
	}

	public void setVgender(String vgender) {
		this.vgender = vgender;
	}

	public Date getDdateOfBirth() {
		return this.ddateOfBirth;
	}

	public void setDdateOfBirth(Date ddateOfBirth) {
		this.ddateOfBirth = ddateOfBirth;
	}

	public String getDateOfBirthLocation() {
		return this.dateOfBirthLocation;
	}

	public void setDateOfBirthLocation(String dateOfBirthLocation) {
		this.dateOfBirthLocation = dateOfBirthLocation;
	}

	public String getVnationality() {
		return this.vnationality;
	}

	public void setVnationality(String vnationality) {
		this.vnationality = vnationality;
	}

	public String getNid() {
		return this.nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	public String getNidLocation() {
		return this.nidLocation;
	}

	public void setNidLocation(String nidLocation) {
		this.nidLocation = nidLocation;
	}

	public String getVemployeeType() {
		return this.vemployeeType;
	}

	public void setVemployeeType(String vemployeeType) {
		this.vemployeeType = vemployeeType;
	}

	public Date getDapplicationDate() {
		return this.dapplicationDate;
	}

	public void setDapplicationDate(Date dapplicationDate) {
		this.dapplicationDate = dapplicationDate;
	}

	public String getApplicationDateLocation() {
		return this.applicationDateLocation;
	}

	public void setApplicationDateLocation(String applicationDateLocation) {
		this.applicationDateLocation = applicationDateLocation;
	}

	public Date getDinterviewDate() {
		return this.dinterviewDate;
	}

	public void setDinterviewDate(Date dinterviewDate) {
		this.dinterviewDate = dinterviewDate;
	}

	public Date getDjoiningDate() {
		return this.djoiningDate;
	}

	public void setDjoiningDate(Date djoiningDate) {
		this.djoiningDate = djoiningDate;
	}

	public String getJoiningDateLocation() {
		return this.joiningDateLocation;
	}

	public void setJoiningDateLocation(String joiningDateLocation) {
		this.joiningDateLocation = joiningDateLocation;
	}

	public Date getDconfirmationDate() {
		return this.dconfirmationDate;
	}

	public void setDconfirmationDate(Date dconfirmationDate) {
		this.dconfirmationDate = dconfirmationDate;
	}

	public String getConfirmationDateLocation() {
		return this.confirmationDateLocation;
	}

	public void setConfirmationDateLocation(String confirmationDateLocation) {
		this.confirmationDateLocation = confirmationDateLocation;
	}

	public String getVstatus() {
		return this.vstatus;
	}

	public void setVstatus(String vstatus) {
		this.vstatus = vstatus;
	}

	public Integer getIstatus() {
		return this.istatus;
	}

	public void setIstatus(Integer istatus) {
		this.istatus = istatus;
	}

	public Date getDstatusDate() {
		return this.dstatusDate;
	}

	public void setDstatusDate(Date dstatusDate) {
		this.dstatusDate = dstatusDate;
	}

	public String getVdepartmentId() {
		return this.vdepartmentId;
	}

	public void setVdepartmentId(String vdepartmentId) {
		this.vdepartmentId = vdepartmentId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public String getVfloor() {
		return this.vfloor;
	}

	public void setVfloor(String vfloor) {
		this.vfloor = vfloor;
	}

	public String getVline() {
		return this.vline;
	}

	public void setVline(String vline) {
		this.vline = vline;
	}

	public String getVgrade() {
		return this.vgrade;
	}

	public void setVgrade(String vgrade) {
		this.vgrade = vgrade;
	}

	public String getImageLocation() {
		return this.imageLocation;
	}

	public void setImageLocation(String imageLocation) {
		this.imageLocation = imageLocation;
	}

	public String getVfatherName() {
		return this.vfatherName;
	}

	public void setVfatherName(String vfatherName) {
		this.vfatherName = vfatherName;
	}

	public String getVmotherName() {
		return this.vmotherName;
	}

	public void setVmotherName(String vmotherName) {
		this.vmotherName = vmotherName;
	}

	public String getVpermanentAddress() {
		return this.vpermanentAddress;
	}

	public void setVpermanentAddress(String vpermanentAddress) {
		this.vpermanentAddress = vpermanentAddress;
	}

	public String getVmailingAddress() {
		return this.vmailingAddress;
	}

	public void setVmailingAddress(String vmailingAddress) {
		this.vmailingAddress = vmailingAddress;
	}

	public String getVbloodGroup() {
		return this.vbloodGroup;
	}

	public void setVbloodGroup(String vbloodGroup) {
		this.vbloodGroup = vbloodGroup;
	}

	public String getVmeritalStatus() {
		return this.vmeritalStatus;
	}

	public void setVmeritalStatus(String vmeritalStatus) {
		this.vmeritalStatus = vmeritalStatus;
	}

	public Date getDmarriageDate() {
		return this.dmarriageDate;
	}

	public void setDmarriageDate(Date dmarriageDate) {
		this.dmarriageDate = dmarriageDate;
	}

	public String getVspouseName() {
		return this.vspouseName;
	}

	public void setVspouseName(String vspouseName) {
		this.vspouseName = vspouseName;
	}

	public String getVspouseOccupation() {
		return this.vspouseOccupation;
	}

	public void setVspouseOccupation(String vspouseOccupation) {
		this.vspouseOccupation = vspouseOccupation;
	}

	public Integer getInoOfChild() {
		return this.inoOfChild;
	}

	public void setInoOfChild(Integer inoOfChild) {
		this.inoOfChild = inoOfChild;
	}

	public String getVn1name() {
		return this.vn1name;
	}

	public void setVn1name(String vn1name) {
		this.vn1name = vn1name;
	}

	public String getVn1relation() {
		return this.vn1relation;
	}

	public void setVn1relation(String vn1relation) {
		this.vn1relation = vn1relation;
	}

	public String getVn2name() {
		return this.vn2name;
	}

	public void setVn2name(String vn2name) {
		this.vn2name = vn2name;
	}

	public String getVn2relation() {
		return this.vn2relation;
	}

	public void setVn2relation(String vn2relation) {
		this.vn2relation = vn2relation;
	}

	public String getVotherQualification() {
		return this.votherQualification;
	}

	public void setVotherQualification(String votherQualification) {
		this.votherQualification = votherQualification;
	}

	public String getVcomputerSkill() {
		return this.vcomputerSkill;
	}

	public void setVcomputerSkill(String vcomputerSkill) {
		this.vcomputerSkill = vcomputerSkill;
	}

	public BigDecimal getMmonthlySalary() {
		return this.mmonthlySalary;
	}

	public void setMmonthlySalary(BigDecimal mmonthlySalary) {
		this.mmonthlySalary = mmonthlySalary;
	}

	public String getVuserName() {
		return this.vuserName;
	}

	public void setVuserName(String vuserName) {
		this.vuserName = vuserName;
	}

	public Date getDdateTime() {
		return this.ddateTime;
	}

	public void setDdateTime(Date ddateTime) {
		this.ddateTime = ddateTime;
	}

	public String getVpcIp() {
		return this.vpcIp;
	}

	public void setVpcIp(String vpcIp) {
		this.vpcIp = vpcIp;
	}

	public String getBirthImage() {
		return this.birthImage;
	}

	public void setBirthImage(String birthImage) {
		this.birthImage = birthImage;
	}

	public String getNidImage() {
		return this.nidImage;
	}

	public void setNidImage(String nidImage) {
		this.nidImage = nidImage;
	}

	public String getApplicationImage() {
		return this.applicationImage;
	}

	public void setApplicationImage(String applicationImage) {
		this.applicationImage = applicationImage;
	}

	public String getJoiningImage() {
		return this.joiningImage;
	}

	public void setJoiningImage(String joiningImage) {
		this.joiningImage = joiningImage;
	}

	public String getConfirmImage() {
		return this.confirmImage;
	}

	public void setConfirmImage(String confirmImage) {
		this.confirmImage = confirmImage;
	}

	public String getSubUnitId() {
		return this.subUnitId;
	}

	public void setSubUnitId(String subUnitId) {
		this.subUnitId = subUnitId;
	}

	public BigDecimal getMhouseRent() {
		return this.mhouseRent;
	}

	public void setMhouseRent(BigDecimal mhouseRent) {
		this.mhouseRent = mhouseRent;
	}

	public Integer getOtStatus() {
		return this.otStatus;
	}

	public void setOtStatus(Integer otStatus) {
		this.otStatus = otStatus;
	}

	public BigDecimal getMmedicalAllowance() {
		return this.mmedicalAllowance;
	}

	public void setMmedicalAllowance(BigDecimal mmedicalAllowance) {
		this.mmedicalAllowance = mmedicalAllowance;
	}

	public BigDecimal getMconAllowance() {
		return this.mconAllowance;
	}

	public void setMconAllowance(BigDecimal mconAllowance) {
		this.mconAllowance = mconAllowance;
	}

	public BigDecimal getMclinical() {
		return this.mclinical;
	}

	public void setMclinical(BigDecimal mclinical) {
		this.mclinical = mclinical;
	}

	public BigDecimal getMspecial() {
		return this.mspecial;
	}

	public void setMspecial(BigDecimal mspecial) {
		this.mspecial = mspecial;
	}

	public BigDecimal getMnonPractice() {
		return this.mnonPractice;
	}

	public void setMnonPractice(BigDecimal mnonPractice) {
		this.mnonPractice = mnonPractice;
	}

	public BigDecimal getMothersAllowance() {
		return this.mothersAllowance;
	}

	public void setMothersAllowance(BigDecimal mothersAllowance) {
		this.mothersAllowance = mothersAllowance;
	}

	public BigDecimal getMprovidentFund() {
		return this.mprovidentFund;
	}

	public void setMprovidentFund(BigDecimal mprovidentFund) {
		this.mprovidentFund = mprovidentFund;
	}

	public BigDecimal getMroomCharge() {
		return this.mroomCharge;
	}

	public void setMroomCharge(BigDecimal mroomCharge) {
		this.mroomCharge = mroomCharge;
	}

	public BigDecimal getMbreej() {
		return this.mbreej;
	}

	public void setMbreej(BigDecimal mbreej) {
		this.mbreej = mbreej;
	}

	public BigDecimal getMkhichuri() {
		return this.mkhichuri;
	}

	public void setMkhichuri(BigDecimal mkhichuri) {
		this.mkhichuri = mkhichuri;
	}

	public BigDecimal getMkfund() {
		return this.mkfund;
	}

	public void setMkfund(BigDecimal mkfund) {
		this.mkfund = mkfund;
	}

	public Integer getBankId() {
		return this.bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Integer getBankBranchId() {
		return this.bankBranchId;
	}

	public void setBankBranchId(Integer bankBranchId) {
		this.bankBranchId = bankBranchId;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
