package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbEmpLeaveApplicationDetailsId generated by hbm2java
 */
public class TbEmpLeaveApplicationDetailsId implements java.io.Serializable {

	private long iautoId;
	private String vleaveId;
	private String vleaveTypeId;
	private String vleaveTypeName;
	private String vfingerId;
	private String vemployeeName;
	private Date dleaveDate;
	private String vpaymentFlag;
	private int iapprovedFlag;
	private String vadjustedType;

	public TbEmpLeaveApplicationDetailsId() {
	}

	public TbEmpLeaveApplicationDetailsId(long iautoId, String vleaveId,
			String vleaveTypeId, String vleaveTypeName, String vfingerId,
			String vemployeeName, Date dleaveDate, String vpaymentFlag,
			int iapprovedFlag, String vadjustedType) {
		this.iautoId = iautoId;
		this.vleaveId = vleaveId;
		this.vleaveTypeId = vleaveTypeId;
		this.vleaveTypeName = vleaveTypeName;
		this.vfingerId = vfingerId;
		this.vemployeeName = vemployeeName;
		this.dleaveDate = dleaveDate;
		this.vpaymentFlag = vpaymentFlag;
		this.iapprovedFlag = iapprovedFlag;
		this.vadjustedType = vadjustedType;
	}

	public long getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(long iautoId) {
		this.iautoId = iautoId;
	}

	public String getVleaveId() {
		return this.vleaveId;
	}

	public void setVleaveId(String vleaveId) {
		this.vleaveId = vleaveId;
	}

	public String getVleaveTypeId() {
		return this.vleaveTypeId;
	}

	public void setVleaveTypeId(String vleaveTypeId) {
		this.vleaveTypeId = vleaveTypeId;
	}

	public String getVleaveTypeName() {
		return this.vleaveTypeName;
	}

	public void setVleaveTypeName(String vleaveTypeName) {
		this.vleaveTypeName = vleaveTypeName;
	}

	public String getVfingerId() {
		return this.vfingerId;
	}

	public void setVfingerId(String vfingerId) {
		this.vfingerId = vfingerId;
	}

	public String getVemployeeName() {
		return this.vemployeeName;
	}

	public void setVemployeeName(String vemployeeName) {
		this.vemployeeName = vemployeeName;
	}

	public Date getDleaveDate() {
		return this.dleaveDate;
	}

	public void setDleaveDate(Date dleaveDate) {
		this.dleaveDate = dleaveDate;
	}

	public String getVpaymentFlag() {
		return this.vpaymentFlag;
	}

	public void setVpaymentFlag(String vpaymentFlag) {
		this.vpaymentFlag = vpaymentFlag;
	}

	public int getIapprovedFlag() {
		return this.iapprovedFlag;
	}

	public void setIapprovedFlag(int iapprovedFlag) {
		this.iapprovedFlag = iapprovedFlag;
	}

	public String getVadjustedType() {
		return this.vadjustedType;
	}

	public void setVadjustedType(String vadjustedType) {
		this.vadjustedType = vadjustedType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbEmpLeaveApplicationDetailsId))
			return false;
		TbEmpLeaveApplicationDetailsId castOther = (TbEmpLeaveApplicationDetailsId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVleaveId() == castOther.getVleaveId()) || (this
						.getVleaveId() != null
						&& castOther.getVleaveId() != null && this
						.getVleaveId().equals(castOther.getVleaveId())))
				&& ((this.getVleaveTypeId() == castOther.getVleaveTypeId()) || (this
						.getVleaveTypeId() != null
						&& castOther.getVleaveTypeId() != null && this
						.getVleaveTypeId().equals(castOther.getVleaveTypeId())))
				&& ((this.getVleaveTypeName() == castOther.getVleaveTypeName()) || (this
						.getVleaveTypeName() != null
						&& castOther.getVleaveTypeName() != null && this
						.getVleaveTypeName().equals(
								castOther.getVleaveTypeName())))
				&& ((this.getVfingerId() == castOther.getVfingerId()) || (this
						.getVfingerId() != null
						&& castOther.getVfingerId() != null && this
						.getVfingerId().equals(castOther.getVfingerId())))
				&& ((this.getVemployeeName() == castOther.getVemployeeName()) || (this
						.getVemployeeName() != null
						&& castOther.getVemployeeName() != null && this
						.getVemployeeName()
						.equals(castOther.getVemployeeName())))
				&& ((this.getDleaveDate() == castOther.getDleaveDate()) || (this
						.getDleaveDate() != null
						&& castOther.getDleaveDate() != null && this
						.getDleaveDate().equals(castOther.getDleaveDate())))
				&& ((this.getVpaymentFlag() == castOther.getVpaymentFlag()) || (this
						.getVpaymentFlag() != null
						&& castOther.getVpaymentFlag() != null && this
						.getVpaymentFlag().equals(castOther.getVpaymentFlag())))
				&& (this.getIapprovedFlag() == castOther.getIapprovedFlag())
				&& ((this.getVadjustedType() == castOther.getVadjustedType()) || (this
						.getVadjustedType() != null
						&& castOther.getVadjustedType() != null && this
						.getVadjustedType()
						.equals(castOther.getVadjustedType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIautoId();
		result = 37 * result
				+ (getVleaveId() == null ? 0 : this.getVleaveId().hashCode());
		result = 37
				* result
				+ (getVleaveTypeId() == null ? 0 : this.getVleaveTypeId()
						.hashCode());
		result = 37
				* result
				+ (getVleaveTypeName() == null ? 0 : this.getVleaveTypeName()
						.hashCode());
		result = 37 * result
				+ (getVfingerId() == null ? 0 : this.getVfingerId().hashCode());
		result = 37
				* result
				+ (getVemployeeName() == null ? 0 : this.getVemployeeName()
						.hashCode());
		result = 37
				* result
				+ (getDleaveDate() == null ? 0 : this.getDleaveDate()
						.hashCode());
		result = 37
				* result
				+ (getVpaymentFlag() == null ? 0 : this.getVpaymentFlag()
						.hashCode());
		result = 37 * result + this.getIapprovedFlag();
		result = 37
				* result
				+ (getVadjustedType() == null ? 0 : this.getVadjustedType()
						.hashCode());
		return result;
	}

}
