package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbEmployeeLeave generated by hbm2java
 */
public class TbEmployeeLeave implements java.io.Serializable {

	private TbEmployeeLeaveId id;

	public TbEmployeeLeave() {
	}

	public TbEmployeeLeave(TbEmployeeLeaveId id) {
		this.id = id;
	}

	public TbEmployeeLeaveId getId() {
		return this.id;
	}

	public void setId(TbEmployeeLeaveId id) {
		this.id = id;
	}

}
