package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbEmployeeLeaveId generated by hbm2java
 */
public class TbEmployeeLeaveId implements java.io.Serializable {

	private int iautoId;
	private Date dapplicationDate;
	private String vemployeeId;
	private String vsectionId;
	private String vdesignationId;
	private Date djoiningDate;
	private String vleaveType;
	private Date dapplyFrom;
	private Date dapplyTo;
	private String vpurposeOfLeave;
	private String vleaveAddress;
	private String vmobileNo;
	private Date dsenctionFrom;
	private Date dsenctionTo;
	private int inoOfDays;
	private Integer inoOfFridays;
	private String vremarks;
	private Integer iapprove;
	private String vuserId;
	private Date dentryTime;
	private String vuserIp;

	public TbEmployeeLeaveId() {
	}

	public TbEmployeeLeaveId(int iautoId, Date dapplicationDate,
			String vemployeeId, String vsectionId, String vdesignationId,
			Date djoiningDate, String vleaveType, Date dapplyFrom,
			Date dapplyTo, String vpurposeOfLeave, String vleaveAddress,
			String vmobileNo, Date dsenctionFrom, Date dsenctionTo,
			int inoOfDays, String vremarks, String vuserId, Date dentryTime,
			String vuserIp) {
		this.iautoId = iautoId;
		this.dapplicationDate = dapplicationDate;
		this.vemployeeId = vemployeeId;
		this.vsectionId = vsectionId;
		this.vdesignationId = vdesignationId;
		this.djoiningDate = djoiningDate;
		this.vleaveType = vleaveType;
		this.dapplyFrom = dapplyFrom;
		this.dapplyTo = dapplyTo;
		this.vpurposeOfLeave = vpurposeOfLeave;
		this.vleaveAddress = vleaveAddress;
		this.vmobileNo = vmobileNo;
		this.dsenctionFrom = dsenctionFrom;
		this.dsenctionTo = dsenctionTo;
		this.inoOfDays = inoOfDays;
		this.vremarks = vremarks;
		this.vuserId = vuserId;
		this.dentryTime = dentryTime;
		this.vuserIp = vuserIp;
	}

	public TbEmployeeLeaveId(int iautoId, Date dapplicationDate,
			String vemployeeId, String vsectionId, String vdesignationId,
			Date djoiningDate, String vleaveType, Date dapplyFrom,
			Date dapplyTo, String vpurposeOfLeave, String vleaveAddress,
			String vmobileNo, Date dsenctionFrom, Date dsenctionTo,
			int inoOfDays, Integer inoOfFridays, String vremarks,
			Integer iapprove, String vuserId, Date dentryTime, String vuserIp) {
		this.iautoId = iautoId;
		this.dapplicationDate = dapplicationDate;
		this.vemployeeId = vemployeeId;
		this.vsectionId = vsectionId;
		this.vdesignationId = vdesignationId;
		this.djoiningDate = djoiningDate;
		this.vleaveType = vleaveType;
		this.dapplyFrom = dapplyFrom;
		this.dapplyTo = dapplyTo;
		this.vpurposeOfLeave = vpurposeOfLeave;
		this.vleaveAddress = vleaveAddress;
		this.vmobileNo = vmobileNo;
		this.dsenctionFrom = dsenctionFrom;
		this.dsenctionTo = dsenctionTo;
		this.inoOfDays = inoOfDays;
		this.inoOfFridays = inoOfFridays;
		this.vremarks = vremarks;
		this.iapprove = iapprove;
		this.vuserId = vuserId;
		this.dentryTime = dentryTime;
		this.vuserIp = vuserIp;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public Date getDapplicationDate() {
		return this.dapplicationDate;
	}

	public void setDapplicationDate(Date dapplicationDate) {
		this.dapplicationDate = dapplicationDate;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public Date getDjoiningDate() {
		return this.djoiningDate;
	}

	public void setDjoiningDate(Date djoiningDate) {
		this.djoiningDate = djoiningDate;
	}

	public String getVleaveType() {
		return this.vleaveType;
	}

	public void setVleaveType(String vleaveType) {
		this.vleaveType = vleaveType;
	}

	public Date getDapplyFrom() {
		return this.dapplyFrom;
	}

	public void setDapplyFrom(Date dapplyFrom) {
		this.dapplyFrom = dapplyFrom;
	}

	public Date getDapplyTo() {
		return this.dapplyTo;
	}

	public void setDapplyTo(Date dapplyTo) {
		this.dapplyTo = dapplyTo;
	}

	public String getVpurposeOfLeave() {
		return this.vpurposeOfLeave;
	}

	public void setVpurposeOfLeave(String vpurposeOfLeave) {
		this.vpurposeOfLeave = vpurposeOfLeave;
	}

	public String getVleaveAddress() {
		return this.vleaveAddress;
	}

	public void setVleaveAddress(String vleaveAddress) {
		this.vleaveAddress = vleaveAddress;
	}

	public String getVmobileNo() {
		return this.vmobileNo;
	}

	public void setVmobileNo(String vmobileNo) {
		this.vmobileNo = vmobileNo;
	}

	public Date getDsenctionFrom() {
		return this.dsenctionFrom;
	}

	public void setDsenctionFrom(Date dsenctionFrom) {
		this.dsenctionFrom = dsenctionFrom;
	}

	public Date getDsenctionTo() {
		return this.dsenctionTo;
	}

	public void setDsenctionTo(Date dsenctionTo) {
		this.dsenctionTo = dsenctionTo;
	}

	public int getInoOfDays() {
		return this.inoOfDays;
	}

	public void setInoOfDays(int inoOfDays) {
		this.inoOfDays = inoOfDays;
	}

	public Integer getInoOfFridays() {
		return this.inoOfFridays;
	}

	public void setInoOfFridays(Integer inoOfFridays) {
		this.inoOfFridays = inoOfFridays;
	}

	public String getVremarks() {
		return this.vremarks;
	}

	public void setVremarks(String vremarks) {
		this.vremarks = vremarks;
	}

	public Integer getIapprove() {
		return this.iapprove;
	}

	public void setIapprove(Integer iapprove) {
		this.iapprove = iapprove;
	}

	public String getVuserId() {
		return this.vuserId;
	}

	public void setVuserId(String vuserId) {
		this.vuserId = vuserId;
	}

	public Date getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(Date dentryTime) {
		this.dentryTime = dentryTime;
	}

	public String getVuserIp() {
		return this.vuserIp;
	}

	public void setVuserIp(String vuserIp) {
		this.vuserIp = vuserIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbEmployeeLeaveId))
			return false;
		TbEmployeeLeaveId castOther = (TbEmployeeLeaveId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getDapplicationDate() == castOther
						.getDapplicationDate()) || (this.getDapplicationDate() != null
						&& castOther.getDapplicationDate() != null && this
						.getDapplicationDate().equals(
								castOther.getDapplicationDate())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getDjoiningDate() == castOther.getDjoiningDate()) || (this
						.getDjoiningDate() != null
						&& castOther.getDjoiningDate() != null && this
						.getDjoiningDate().equals(castOther.getDjoiningDate())))
				&& ((this.getVleaveType() == castOther.getVleaveType()) || (this
						.getVleaveType() != null
						&& castOther.getVleaveType() != null && this
						.getVleaveType().equals(castOther.getVleaveType())))
				&& ((this.getDapplyFrom() == castOther.getDapplyFrom()) || (this
						.getDapplyFrom() != null
						&& castOther.getDapplyFrom() != null && this
						.getDapplyFrom().equals(castOther.getDapplyFrom())))
				&& ((this.getDapplyTo() == castOther.getDapplyTo()) || (this
						.getDapplyTo() != null
						&& castOther.getDapplyTo() != null && this
						.getDapplyTo().equals(castOther.getDapplyTo())))
				&& ((this.getVpurposeOfLeave() == castOther
						.getVpurposeOfLeave()) || (this.getVpurposeOfLeave() != null
						&& castOther.getVpurposeOfLeave() != null && this
						.getVpurposeOfLeave().equals(
								castOther.getVpurposeOfLeave())))
				&& ((this.getVleaveAddress() == castOther.getVleaveAddress()) || (this
						.getVleaveAddress() != null
						&& castOther.getVleaveAddress() != null && this
						.getVleaveAddress()
						.equals(castOther.getVleaveAddress())))
				&& ((this.getVmobileNo() == castOther.getVmobileNo()) || (this
						.getVmobileNo() != null
						&& castOther.getVmobileNo() != null && this
						.getVmobileNo().equals(castOther.getVmobileNo())))
				&& ((this.getDsenctionFrom() == castOther.getDsenctionFrom()) || (this
						.getDsenctionFrom() != null
						&& castOther.getDsenctionFrom() != null && this
						.getDsenctionFrom()
						.equals(castOther.getDsenctionFrom())))
				&& ((this.getDsenctionTo() == castOther.getDsenctionTo()) || (this
						.getDsenctionTo() != null
						&& castOther.getDsenctionTo() != null && this
						.getDsenctionTo().equals(castOther.getDsenctionTo())))
				&& (this.getInoOfDays() == castOther.getInoOfDays())
				&& ((this.getInoOfFridays() == castOther.getInoOfFridays()) || (this
						.getInoOfFridays() != null
						&& castOther.getInoOfFridays() != null && this
						.getInoOfFridays().equals(castOther.getInoOfFridays())))
				&& ((this.getVremarks() == castOther.getVremarks()) || (this
						.getVremarks() != null
						&& castOther.getVremarks() != null && this
						.getVremarks().equals(castOther.getVremarks())))
				&& ((this.getIapprove() == castOther.getIapprove()) || (this
						.getIapprove() != null
						&& castOther.getIapprove() != null && this
						.getIapprove().equals(castOther.getIapprove())))
				&& ((this.getVuserId() == castOther.getVuserId()) || (this
						.getVuserId() != null && castOther.getVuserId() != null && this
						.getVuserId().equals(castOther.getVuserId())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())))
				&& ((this.getVuserIp() == castOther.getVuserIp()) || (this
						.getVuserIp() != null && castOther.getVuserIp() != null && this
						.getVuserIp().equals(castOther.getVuserIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37
				* result
				+ (getDapplicationDate() == null ? 0 : this
						.getDapplicationDate().hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37
				* result
				+ (getDjoiningDate() == null ? 0 : this.getDjoiningDate()
						.hashCode());
		result = 37
				* result
				+ (getVleaveType() == null ? 0 : this.getVleaveType()
						.hashCode());
		result = 37
				* result
				+ (getDapplyFrom() == null ? 0 : this.getDapplyFrom()
						.hashCode());
		result = 37 * result
				+ (getDapplyTo() == null ? 0 : this.getDapplyTo().hashCode());
		result = 37
				* result
				+ (getVpurposeOfLeave() == null ? 0 : this.getVpurposeOfLeave()
						.hashCode());
		result = 37
				* result
				+ (getVleaveAddress() == null ? 0 : this.getVleaveAddress()
						.hashCode());
		result = 37 * result
				+ (getVmobileNo() == null ? 0 : this.getVmobileNo().hashCode());
		result = 37
				* result
				+ (getDsenctionFrom() == null ? 0 : this.getDsenctionFrom()
						.hashCode());
		result = 37
				* result
				+ (getDsenctionTo() == null ? 0 : this.getDsenctionTo()
						.hashCode());
		result = 37 * result + this.getInoOfDays();
		result = 37
				* result
				+ (getInoOfFridays() == null ? 0 : this.getInoOfFridays()
						.hashCode());
		result = 37 * result
				+ (getVremarks() == null ? 0 : this.getVremarks().hashCode());
		result = 37 * result
				+ (getIapprove() == null ? 0 : this.getIapprove().hashCode());
		result = 37 * result
				+ (getVuserId() == null ? 0 : this.getVuserId().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		result = 37 * result
				+ (getVuserIp() == null ? 0 : this.getVuserIp().hashCode());
		return result;
	}

}
