package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbFinishedProductInfoId generated by hbm2java
 */
public class TbFinishedProductInfoId implements java.io.Serializable {

	private int iautoId;
	private String vproductId;
	private String vproductName;
	private String vcategoryId;
	private String vcategoryName;
	private String vsubCategoryId;
	private String vsubCategoryName;
	private String vbrandId;
	private String vbrandName;
	private String vdesignId;
	private String vdesignName;
	private String vcolorId;
	private String vcolorName;
	private String vsizeId;
	private String vsizeName;
	private String vunitName;
	private String imageLocation;
	private BigDecimal mdealerPrice;
	private BigDecimal mtradePrice;
	private Date dfinishedDate;
	private String vledgerId;
	private String userId;
	private String userIp;
	private Date entryTime;

	public TbFinishedProductInfoId() {
	}

	public TbFinishedProductInfoId(int iautoId, String imageLocation) {
		this.iautoId = iautoId;
		this.imageLocation = imageLocation;
	}

	public TbFinishedProductInfoId(int iautoId, String vproductId,
			String vproductName, String vcategoryId, String vcategoryName,
			String vsubCategoryId, String vsubCategoryName, String vbrandId,
			String vbrandName, String vdesignId, String vdesignName,
			String vcolorId, String vcolorName, String vsizeId,
			String vsizeName, String vunitName, String imageLocation,
			BigDecimal mdealerPrice, BigDecimal mtradePrice,
			Date dfinishedDate, String vledgerId, String userId, String userIp,
			Date entryTime) {
		this.iautoId = iautoId;
		this.vproductId = vproductId;
		this.vproductName = vproductName;
		this.vcategoryId = vcategoryId;
		this.vcategoryName = vcategoryName;
		this.vsubCategoryId = vsubCategoryId;
		this.vsubCategoryName = vsubCategoryName;
		this.vbrandId = vbrandId;
		this.vbrandName = vbrandName;
		this.vdesignId = vdesignId;
		this.vdesignName = vdesignName;
		this.vcolorId = vcolorId;
		this.vcolorName = vcolorName;
		this.vsizeId = vsizeId;
		this.vsizeName = vsizeName;
		this.vunitName = vunitName;
		this.imageLocation = imageLocation;
		this.mdealerPrice = mdealerPrice;
		this.mtradePrice = mtradePrice;
		this.dfinishedDate = dfinishedDate;
		this.vledgerId = vledgerId;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public String getVproductId() {
		return this.vproductId;
	}

	public void setVproductId(String vproductId) {
		this.vproductId = vproductId;
	}

	public String getVproductName() {
		return this.vproductName;
	}

	public void setVproductName(String vproductName) {
		this.vproductName = vproductName;
	}

	public String getVcategoryId() {
		return this.vcategoryId;
	}

	public void setVcategoryId(String vcategoryId) {
		this.vcategoryId = vcategoryId;
	}

	public String getVcategoryName() {
		return this.vcategoryName;
	}

	public void setVcategoryName(String vcategoryName) {
		this.vcategoryName = vcategoryName;
	}

	public String getVsubCategoryId() {
		return this.vsubCategoryId;
	}

	public void setVsubCategoryId(String vsubCategoryId) {
		this.vsubCategoryId = vsubCategoryId;
	}

	public String getVsubCategoryName() {
		return this.vsubCategoryName;
	}

	public void setVsubCategoryName(String vsubCategoryName) {
		this.vsubCategoryName = vsubCategoryName;
	}

	public String getVbrandId() {
		return this.vbrandId;
	}

	public void setVbrandId(String vbrandId) {
		this.vbrandId = vbrandId;
	}

	public String getVbrandName() {
		return this.vbrandName;
	}

	public void setVbrandName(String vbrandName) {
		this.vbrandName = vbrandName;
	}

	public String getVdesignId() {
		return this.vdesignId;
	}

	public void setVdesignId(String vdesignId) {
		this.vdesignId = vdesignId;
	}

	public String getVdesignName() {
		return this.vdesignName;
	}

	public void setVdesignName(String vdesignName) {
		this.vdesignName = vdesignName;
	}

	public String getVcolorId() {
		return this.vcolorId;
	}

	public void setVcolorId(String vcolorId) {
		this.vcolorId = vcolorId;
	}

	public String getVcolorName() {
		return this.vcolorName;
	}

	public void setVcolorName(String vcolorName) {
		this.vcolorName = vcolorName;
	}

	public String getVsizeId() {
		return this.vsizeId;
	}

	public void setVsizeId(String vsizeId) {
		this.vsizeId = vsizeId;
	}

	public String getVsizeName() {
		return this.vsizeName;
	}

	public void setVsizeName(String vsizeName) {
		this.vsizeName = vsizeName;
	}

	public String getVunitName() {
		return this.vunitName;
	}

	public void setVunitName(String vunitName) {
		this.vunitName = vunitName;
	}

	public String getImageLocation() {
		return this.imageLocation;
	}

	public void setImageLocation(String imageLocation) {
		this.imageLocation = imageLocation;
	}

	public BigDecimal getMdealerPrice() {
		return this.mdealerPrice;
	}

	public void setMdealerPrice(BigDecimal mdealerPrice) {
		this.mdealerPrice = mdealerPrice;
	}

	public BigDecimal getMtradePrice() {
		return this.mtradePrice;
	}

	public void setMtradePrice(BigDecimal mtradePrice) {
		this.mtradePrice = mtradePrice;
	}

	public Date getDfinishedDate() {
		return this.dfinishedDate;
	}

	public void setDfinishedDate(Date dfinishedDate) {
		this.dfinishedDate = dfinishedDate;
	}

	public String getVledgerId() {
		return this.vledgerId;
	}

	public void setVledgerId(String vledgerId) {
		this.vledgerId = vledgerId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbFinishedProductInfoId))
			return false;
		TbFinishedProductInfoId castOther = (TbFinishedProductInfoId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVproductId() == castOther.getVproductId()) || (this
						.getVproductId() != null
						&& castOther.getVproductId() != null && this
						.getVproductId().equals(castOther.getVproductId())))
				&& ((this.getVproductName() == castOther.getVproductName()) || (this
						.getVproductName() != null
						&& castOther.getVproductName() != null && this
						.getVproductName().equals(castOther.getVproductName())))
				&& ((this.getVcategoryId() == castOther.getVcategoryId()) || (this
						.getVcategoryId() != null
						&& castOther.getVcategoryId() != null && this
						.getVcategoryId().equals(castOther.getVcategoryId())))
				&& ((this.getVcategoryName() == castOther.getVcategoryName()) || (this
						.getVcategoryName() != null
						&& castOther.getVcategoryName() != null && this
						.getVcategoryName()
						.equals(castOther.getVcategoryName())))
				&& ((this.getVsubCategoryId() == castOther.getVsubCategoryId()) || (this
						.getVsubCategoryId() != null
						&& castOther.getVsubCategoryId() != null && this
						.getVsubCategoryId().equals(
								castOther.getVsubCategoryId())))
				&& ((this.getVsubCategoryName() == castOther
						.getVsubCategoryName()) || (this.getVsubCategoryName() != null
						&& castOther.getVsubCategoryName() != null && this
						.getVsubCategoryName().equals(
								castOther.getVsubCategoryName())))
				&& ((this.getVbrandId() == castOther.getVbrandId()) || (this
						.getVbrandId() != null
						&& castOther.getVbrandId() != null && this
						.getVbrandId().equals(castOther.getVbrandId())))
				&& ((this.getVbrandName() == castOther.getVbrandName()) || (this
						.getVbrandName() != null
						&& castOther.getVbrandName() != null && this
						.getVbrandName().equals(castOther.getVbrandName())))
				&& ((this.getVdesignId() == castOther.getVdesignId()) || (this
						.getVdesignId() != null
						&& castOther.getVdesignId() != null && this
						.getVdesignId().equals(castOther.getVdesignId())))
				&& ((this.getVdesignName() == castOther.getVdesignName()) || (this
						.getVdesignName() != null
						&& castOther.getVdesignName() != null && this
						.getVdesignName().equals(castOther.getVdesignName())))
				&& ((this.getVcolorId() == castOther.getVcolorId()) || (this
						.getVcolorId() != null
						&& castOther.getVcolorId() != null && this
						.getVcolorId().equals(castOther.getVcolorId())))
				&& ((this.getVcolorName() == castOther.getVcolorName()) || (this
						.getVcolorName() != null
						&& castOther.getVcolorName() != null && this
						.getVcolorName().equals(castOther.getVcolorName())))
				&& ((this.getVsizeId() == castOther.getVsizeId()) || (this
						.getVsizeId() != null && castOther.getVsizeId() != null && this
						.getVsizeId().equals(castOther.getVsizeId())))
				&& ((this.getVsizeName() == castOther.getVsizeName()) || (this
						.getVsizeName() != null
						&& castOther.getVsizeName() != null && this
						.getVsizeName().equals(castOther.getVsizeName())))
				&& ((this.getVunitName() == castOther.getVunitName()) || (this
						.getVunitName() != null
						&& castOther.getVunitName() != null && this
						.getVunitName().equals(castOther.getVunitName())))
				&& ((this.getImageLocation() == castOther.getImageLocation()) || (this
						.getImageLocation() != null
						&& castOther.getImageLocation() != null && this
						.getImageLocation()
						.equals(castOther.getImageLocation())))
				&& ((this.getMdealerPrice() == castOther.getMdealerPrice()) || (this
						.getMdealerPrice() != null
						&& castOther.getMdealerPrice() != null && this
						.getMdealerPrice().equals(castOther.getMdealerPrice())))
				&& ((this.getMtradePrice() == castOther.getMtradePrice()) || (this
						.getMtradePrice() != null
						&& castOther.getMtradePrice() != null && this
						.getMtradePrice().equals(castOther.getMtradePrice())))
				&& ((this.getDfinishedDate() == castOther.getDfinishedDate()) || (this
						.getDfinishedDate() != null
						&& castOther.getDfinishedDate() != null && this
						.getDfinishedDate()
						.equals(castOther.getDfinishedDate())))
				&& ((this.getVledgerId() == castOther.getVledgerId()) || (this
						.getVledgerId() != null
						&& castOther.getVledgerId() != null && this
						.getVledgerId().equals(castOther.getVledgerId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37
				* result
				+ (getVproductId() == null ? 0 : this.getVproductId()
						.hashCode());
		result = 37
				* result
				+ (getVproductName() == null ? 0 : this.getVproductName()
						.hashCode());
		result = 37
				* result
				+ (getVcategoryId() == null ? 0 : this.getVcategoryId()
						.hashCode());
		result = 37
				* result
				+ (getVcategoryName() == null ? 0 : this.getVcategoryName()
						.hashCode());
		result = 37
				* result
				+ (getVsubCategoryId() == null ? 0 : this.getVsubCategoryId()
						.hashCode());
		result = 37
				* result
				+ (getVsubCategoryName() == null ? 0 : this
						.getVsubCategoryName().hashCode());
		result = 37 * result
				+ (getVbrandId() == null ? 0 : this.getVbrandId().hashCode());
		result = 37
				* result
				+ (getVbrandName() == null ? 0 : this.getVbrandName()
						.hashCode());
		result = 37 * result
				+ (getVdesignId() == null ? 0 : this.getVdesignId().hashCode());
		result = 37
				* result
				+ (getVdesignName() == null ? 0 : this.getVdesignName()
						.hashCode());
		result = 37 * result
				+ (getVcolorId() == null ? 0 : this.getVcolorId().hashCode());
		result = 37
				* result
				+ (getVcolorName() == null ? 0 : this.getVcolorName()
						.hashCode());
		result = 37 * result
				+ (getVsizeId() == null ? 0 : this.getVsizeId().hashCode());
		result = 37 * result
				+ (getVsizeName() == null ? 0 : this.getVsizeName().hashCode());
		result = 37 * result
				+ (getVunitName() == null ? 0 : this.getVunitName().hashCode());
		result = 37
				* result
				+ (getImageLocation() == null ? 0 : this.getImageLocation()
						.hashCode());
		result = 37
				* result
				+ (getMdealerPrice() == null ? 0 : this.getMdealerPrice()
						.hashCode());
		result = 37
				* result
				+ (getMtradePrice() == null ? 0 : this.getMtradePrice()
						.hashCode());
		result = 37
				* result
				+ (getDfinishedDate() == null ? 0 : this.getDfinishedDate()
						.hashCode());
		result = 37 * result
				+ (getVledgerId() == null ? 0 : this.getVledgerId().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
