package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbFiscalYear generated by hbm2java
 */
public class TbFiscalYear implements java.io.Serializable {

	private int slNo;
	private int autoId;
	private Date opDate;
	private Date clDate;
	private int runningFlag;
	private boolean isClosed;
	private Integer userId;
	private String userIp;
	private Date entryTime;

	public TbFiscalYear() {
	}

	public TbFiscalYear(int slNo, int autoId, int runningFlag, boolean isClosed) {
		this.slNo = slNo;
		this.autoId = autoId;
		this.runningFlag = runningFlag;
		this.isClosed = isClosed;
	}

	public TbFiscalYear(int slNo, int autoId, Date opDate, Date clDate,
			int runningFlag, boolean isClosed, Integer userId, String userIp,
			Date entryTime) {
		this.slNo = slNo;
		this.autoId = autoId;
		this.opDate = opDate;
		this.clDate = clDate;
		this.runningFlag = runningFlag;
		this.isClosed = isClosed;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getSlNo() {
		return this.slNo;
	}

	public void setSlNo(int slNo) {
		this.slNo = slNo;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	public Date getClDate() {
		return this.clDate;
	}

	public void setClDate(Date clDate) {
		this.clDate = clDate;
	}

	public int getRunningFlag() {
		return this.runningFlag;
	}

	public void setRunningFlag(int runningFlag) {
		this.runningFlag = runningFlag;
	}

	public boolean isIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(boolean isClosed) {
		this.isClosed = isClosed;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
