package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbFiscalClosingStepStatusId generated by hbm2java
 */
public class TbFiscalClosingStepStatusId implements java.io.Serializable {

	private long slNo;
	private String stepNo;
	private boolean status;
	private String companyId;
	private boolean tbCreate;

	public TbFiscalClosingStepStatusId() {
	}

	public TbFiscalClosingStepStatusId(long slNo, String stepNo,
			boolean status, boolean tbCreate) {
		this.slNo = slNo;
		this.stepNo = stepNo;
		this.status = status;
		this.tbCreate = tbCreate;
	}

	public TbFiscalClosingStepStatusId(long slNo, String stepNo,
			boolean status, String companyId, boolean tbCreate) {
		this.slNo = slNo;
		this.stepNo = stepNo;
		this.status = status;
		this.companyId = companyId;
		this.tbCreate = tbCreate;
	}

	public long getSlNo() {
		return this.slNo;
	}

	public void setSlNo(long slNo) {
		this.slNo = slNo;
	}

	public String getStepNo() {
		return this.stepNo;
	}

	public void setStepNo(String stepNo) {
		this.stepNo = stepNo;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public boolean isTbCreate() {
		return this.tbCreate;
	}

	public void setTbCreate(boolean tbCreate) {
		this.tbCreate = tbCreate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbFiscalClosingStepStatusId))
			return false;
		TbFiscalClosingStepStatusId castOther = (TbFiscalClosingStepStatusId) other;

		return (this.getSlNo() == castOther.getSlNo())
				&& ((this.getStepNo() == castOther.getStepNo()) || (this
						.getStepNo() != null && castOther.getStepNo() != null && this
						.getStepNo().equals(castOther.getStepNo())))
				&& (this.isStatus() == castOther.isStatus())
				&& ((this.getCompanyId() == castOther.getCompanyId()) || (this
						.getCompanyId() != null
						&& castOther.getCompanyId() != null && this
						.getCompanyId().equals(castOther.getCompanyId())))
				&& (this.isTbCreate() == castOther.isTbCreate());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSlNo();
		result = 37 * result
				+ (getStepNo() == null ? 0 : this.getStepNo().hashCode());
		result = 37 * result + (this.isStatus() ? 1 : 0);
		result = 37 * result
				+ (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (this.isTbCreate() ? 1 : 0);
		return result;
	}

}
