package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbFiscalClosingStepStatus generated by hbm2java
 */
public class TbFiscalClosingStepStatus implements java.io.Serializable {

	private TbFiscalClosingStepStatusId id;

	public TbFiscalClosingStepStatus() {
	}

	public TbFiscalClosingStepStatus(TbFiscalClosingStepStatusId id) {
		this.id = id;
	}

	public TbFiscalClosingStepStatusId getId() {
		return this.id;
	}

	public void setId(TbFiscalClosingStepStatusId id) {
		this.id = id;
	}

}
