package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbHoliday generated by hbm2java
 */
public class TbHoliday implements java.io.Serializable {

	private TbHolidayId id;

	public TbHoliday() {
	}

	public TbHoliday(TbHolidayId id) {
		this.id = id;
	}

	public TbHolidayId getId() {
		return this.id;
	}

	public void setId(TbHolidayId id) {
		this.id = id;
	}

}
