package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbHolidayId generated by hbm2java
 */
public class TbHolidayId implements java.io.Serializable {

	private int slNo;
	private Date ddate;
	private String voccasion;
	private Integer userId;
	private String userIp;
	private Date entryTime;

	public TbHolidayId() {
	}

	public TbHolidayId(int slNo, Date ddate) {
		this.slNo = slNo;
		this.ddate = ddate;
	}

	public TbHolidayId(int slNo, Date ddate, String voccasion, Integer userId,
			String userIp, Date entryTime) {
		this.slNo = slNo;
		this.ddate = ddate;
		this.voccasion = voccasion;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getSlNo() {
		return this.slNo;
	}

	public void setSlNo(int slNo) {
		this.slNo = slNo;
	}

	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	public String getVoccasion() {
		return this.voccasion;
	}

	public void setVoccasion(String voccasion) {
		this.voccasion = voccasion;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbHolidayId))
			return false;
		TbHolidayId castOther = (TbHolidayId) other;

		return (this.getSlNo() == castOther.getSlNo())
				&& ((this.getDdate() == castOther.getDdate()) || (this
						.getDdate() != null && castOther.getDdate() != null && this
						.getDdate().equals(castOther.getDdate())))
				&& ((this.getVoccasion() == castOther.getVoccasion()) || (this
						.getVoccasion() != null
						&& castOther.getVoccasion() != null && this
						.getVoccasion().equals(castOther.getVoccasion())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSlNo();
		result = 37 * result
				+ (getDdate() == null ? 0 : this.getDdate().hashCode());
		result = 37 * result
				+ (getVoccasion() == null ? 0 : this.getVoccasion().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
