package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbLeaveBalanceNew generated by hbm2java
 */
public class TbLeaveBalanceNew implements java.io.Serializable {

	private TbLeaveBalanceNewId id;

	public TbLeaveBalanceNew() {
	}

	public TbLeaveBalanceNew(TbLeaveBalanceNewId id) {
		this.id = id;
	}

	public TbLeaveBalanceNewId getId() {
		return this.id;
	}

	public void setId(TbLeaveBalanceNewId id) {
		this.id = id;
	}

}
