package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbLeaveBalanceNewId generated by hbm2java
 */
public class TbLeaveBalanceNewId implements java.io.Serializable {

	private long autoId;
	private Date currentYear;
	private String vemployeeId;
	private String vsectionId;
	private Integer iclyBalance;
	private Integer islyBalance;
	private Integer ialyBalance;
	private Integer imlyBalance;
	private Integer iclOpening;
	private Integer icarryCl;
	private Integer islOpening;
	private Integer icarrySl;
	private Integer ialOpening;
	private Integer icarryAl;
	private Integer imlOpening;
	private Integer icarryMl;
	private Integer iclBalance;
	private Integer islBalance;
	private Integer ialBalance;
	private Integer imlBalance;
	private Integer iclEnjoyed;
	private Integer islEnjoyed;
	private Integer ialEnjoyed;
	private Integer imlEnjoyed;
	private Integer iflag;
	private String userName;
	private Date entryTime;
	private String userIp;

	public TbLeaveBalanceNewId() {
	}

	public TbLeaveBalanceNewId(long autoId) {
		this.autoId = autoId;
	}

	public TbLeaveBalanceNewId(long autoId, Date currentYear,
			String vemployeeId, String vsectionId, Integer iclyBalance,
			Integer islyBalance, Integer ialyBalance, Integer imlyBalance,
			Integer iclOpening, Integer icarryCl, Integer islOpening,
			Integer icarrySl, Integer ialOpening, Integer icarryAl,
			Integer imlOpening, Integer icarryMl, Integer iclBalance,
			Integer islBalance, Integer ialBalance, Integer imlBalance,
			Integer iclEnjoyed, Integer islEnjoyed, Integer ialEnjoyed,
			Integer imlEnjoyed, Integer iflag, String userName, Date entryTime,
			String userIp) {
		this.autoId = autoId;
		this.currentYear = currentYear;
		this.vemployeeId = vemployeeId;
		this.vsectionId = vsectionId;
		this.iclyBalance = iclyBalance;
		this.islyBalance = islyBalance;
		this.ialyBalance = ialyBalance;
		this.imlyBalance = imlyBalance;
		this.iclOpening = iclOpening;
		this.icarryCl = icarryCl;
		this.islOpening = islOpening;
		this.icarrySl = icarrySl;
		this.ialOpening = ialOpening;
		this.icarryAl = icarryAl;
		this.imlOpening = imlOpening;
		this.icarryMl = icarryMl;
		this.iclBalance = iclBalance;
		this.islBalance = islBalance;
		this.ialBalance = ialBalance;
		this.imlBalance = imlBalance;
		this.iclEnjoyed = iclEnjoyed;
		this.islEnjoyed = islEnjoyed;
		this.ialEnjoyed = ialEnjoyed;
		this.imlEnjoyed = imlEnjoyed;
		this.iflag = iflag;
		this.userName = userName;
		this.entryTime = entryTime;
		this.userIp = userIp;
	}

	public long getAutoId() {
		return this.autoId;
	}

	public void setAutoId(long autoId) {
		this.autoId = autoId;
	}

	public Date getCurrentYear() {
		return this.currentYear;
	}

	public void setCurrentYear(Date currentYear) {
		this.currentYear = currentYear;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public Integer getIclyBalance() {
		return this.iclyBalance;
	}

	public void setIclyBalance(Integer iclyBalance) {
		this.iclyBalance = iclyBalance;
	}

	public Integer getIslyBalance() {
		return this.islyBalance;
	}

	public void setIslyBalance(Integer islyBalance) {
		this.islyBalance = islyBalance;
	}

	public Integer getIalyBalance() {
		return this.ialyBalance;
	}

	public void setIalyBalance(Integer ialyBalance) {
		this.ialyBalance = ialyBalance;
	}

	public Integer getImlyBalance() {
		return this.imlyBalance;
	}

	public void setImlyBalance(Integer imlyBalance) {
		this.imlyBalance = imlyBalance;
	}

	public Integer getIclOpening() {
		return this.iclOpening;
	}

	public void setIclOpening(Integer iclOpening) {
		this.iclOpening = iclOpening;
	}

	public Integer getIcarryCl() {
		return this.icarryCl;
	}

	public void setIcarryCl(Integer icarryCl) {
		this.icarryCl = icarryCl;
	}

	public Integer getIslOpening() {
		return this.islOpening;
	}

	public void setIslOpening(Integer islOpening) {
		this.islOpening = islOpening;
	}

	public Integer getIcarrySl() {
		return this.icarrySl;
	}

	public void setIcarrySl(Integer icarrySl) {
		this.icarrySl = icarrySl;
	}

	public Integer getIalOpening() {
		return this.ialOpening;
	}

	public void setIalOpening(Integer ialOpening) {
		this.ialOpening = ialOpening;
	}

	public Integer getIcarryAl() {
		return this.icarryAl;
	}

	public void setIcarryAl(Integer icarryAl) {
		this.icarryAl = icarryAl;
	}

	public Integer getImlOpening() {
		return this.imlOpening;
	}

	public void setImlOpening(Integer imlOpening) {
		this.imlOpening = imlOpening;
	}

	public Integer getIcarryMl() {
		return this.icarryMl;
	}

	public void setIcarryMl(Integer icarryMl) {
		this.icarryMl = icarryMl;
	}

	public Integer getIclBalance() {
		return this.iclBalance;
	}

	public void setIclBalance(Integer iclBalance) {
		this.iclBalance = iclBalance;
	}

	public Integer getIslBalance() {
		return this.islBalance;
	}

	public void setIslBalance(Integer islBalance) {
		this.islBalance = islBalance;
	}

	public Integer getIalBalance() {
		return this.ialBalance;
	}

	public void setIalBalance(Integer ialBalance) {
		this.ialBalance = ialBalance;
	}

	public Integer getImlBalance() {
		return this.imlBalance;
	}

	public void setImlBalance(Integer imlBalance) {
		this.imlBalance = imlBalance;
	}

	public Integer getIclEnjoyed() {
		return this.iclEnjoyed;
	}

	public void setIclEnjoyed(Integer iclEnjoyed) {
		this.iclEnjoyed = iclEnjoyed;
	}

	public Integer getIslEnjoyed() {
		return this.islEnjoyed;
	}

	public void setIslEnjoyed(Integer islEnjoyed) {
		this.islEnjoyed = islEnjoyed;
	}

	public Integer getIalEnjoyed() {
		return this.ialEnjoyed;
	}

	public void setIalEnjoyed(Integer ialEnjoyed) {
		this.ialEnjoyed = ialEnjoyed;
	}

	public Integer getImlEnjoyed() {
		return this.imlEnjoyed;
	}

	public void setImlEnjoyed(Integer imlEnjoyed) {
		this.imlEnjoyed = imlEnjoyed;
	}

	public Integer getIflag() {
		return this.iflag;
	}

	public void setIflag(Integer iflag) {
		this.iflag = iflag;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLeaveBalanceNewId))
			return false;
		TbLeaveBalanceNewId castOther = (TbLeaveBalanceNewId) other;

		return (this.getAutoId() == castOther.getAutoId())
				&& ((this.getCurrentYear() == castOther.getCurrentYear()) || (this
						.getCurrentYear() != null
						&& castOther.getCurrentYear() != null && this
						.getCurrentYear().equals(castOther.getCurrentYear())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getIclyBalance() == castOther.getIclyBalance()) || (this
						.getIclyBalance() != null
						&& castOther.getIclyBalance() != null && this
						.getIclyBalance().equals(castOther.getIclyBalance())))
				&& ((this.getIslyBalance() == castOther.getIslyBalance()) || (this
						.getIslyBalance() != null
						&& castOther.getIslyBalance() != null && this
						.getIslyBalance().equals(castOther.getIslyBalance())))
				&& ((this.getIalyBalance() == castOther.getIalyBalance()) || (this
						.getIalyBalance() != null
						&& castOther.getIalyBalance() != null && this
						.getIalyBalance().equals(castOther.getIalyBalance())))
				&& ((this.getImlyBalance() == castOther.getImlyBalance()) || (this
						.getImlyBalance() != null
						&& castOther.getImlyBalance() != null && this
						.getImlyBalance().equals(castOther.getImlyBalance())))
				&& ((this.getIclOpening() == castOther.getIclOpening()) || (this
						.getIclOpening() != null
						&& castOther.getIclOpening() != null && this
						.getIclOpening().equals(castOther.getIclOpening())))
				&& ((this.getIcarryCl() == castOther.getIcarryCl()) || (this
						.getIcarryCl() != null
						&& castOther.getIcarryCl() != null && this
						.getIcarryCl().equals(castOther.getIcarryCl())))
				&& ((this.getIslOpening() == castOther.getIslOpening()) || (this
						.getIslOpening() != null
						&& castOther.getIslOpening() != null && this
						.getIslOpening().equals(castOther.getIslOpening())))
				&& ((this.getIcarrySl() == castOther.getIcarrySl()) || (this
						.getIcarrySl() != null
						&& castOther.getIcarrySl() != null && this
						.getIcarrySl().equals(castOther.getIcarrySl())))
				&& ((this.getIalOpening() == castOther.getIalOpening()) || (this
						.getIalOpening() != null
						&& castOther.getIalOpening() != null && this
						.getIalOpening().equals(castOther.getIalOpening())))
				&& ((this.getIcarryAl() == castOther.getIcarryAl()) || (this
						.getIcarryAl() != null
						&& castOther.getIcarryAl() != null && this
						.getIcarryAl().equals(castOther.getIcarryAl())))
				&& ((this.getImlOpening() == castOther.getImlOpening()) || (this
						.getImlOpening() != null
						&& castOther.getImlOpening() != null && this
						.getImlOpening().equals(castOther.getImlOpening())))
				&& ((this.getIcarryMl() == castOther.getIcarryMl()) || (this
						.getIcarryMl() != null
						&& castOther.getIcarryMl() != null && this
						.getIcarryMl().equals(castOther.getIcarryMl())))
				&& ((this.getIclBalance() == castOther.getIclBalance()) || (this
						.getIclBalance() != null
						&& castOther.getIclBalance() != null && this
						.getIclBalance().equals(castOther.getIclBalance())))
				&& ((this.getIslBalance() == castOther.getIslBalance()) || (this
						.getIslBalance() != null
						&& castOther.getIslBalance() != null && this
						.getIslBalance().equals(castOther.getIslBalance())))
				&& ((this.getIalBalance() == castOther.getIalBalance()) || (this
						.getIalBalance() != null
						&& castOther.getIalBalance() != null && this
						.getIalBalance().equals(castOther.getIalBalance())))
				&& ((this.getImlBalance() == castOther.getImlBalance()) || (this
						.getImlBalance() != null
						&& castOther.getImlBalance() != null && this
						.getImlBalance().equals(castOther.getImlBalance())))
				&& ((this.getIclEnjoyed() == castOther.getIclEnjoyed()) || (this
						.getIclEnjoyed() != null
						&& castOther.getIclEnjoyed() != null && this
						.getIclEnjoyed().equals(castOther.getIclEnjoyed())))
				&& ((this.getIslEnjoyed() == castOther.getIslEnjoyed()) || (this
						.getIslEnjoyed() != null
						&& castOther.getIslEnjoyed() != null && this
						.getIslEnjoyed().equals(castOther.getIslEnjoyed())))
				&& ((this.getIalEnjoyed() == castOther.getIalEnjoyed()) || (this
						.getIalEnjoyed() != null
						&& castOther.getIalEnjoyed() != null && this
						.getIalEnjoyed().equals(castOther.getIalEnjoyed())))
				&& ((this.getImlEnjoyed() == castOther.getImlEnjoyed()) || (this
						.getImlEnjoyed() != null
						&& castOther.getImlEnjoyed() != null && this
						.getImlEnjoyed().equals(castOther.getImlEnjoyed())))
				&& ((this.getIflag() == castOther.getIflag()) || (this
						.getIflag() != null && castOther.getIflag() != null && this
						.getIflag().equals(castOther.getIflag())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAutoId();
		result = 37
				* result
				+ (getCurrentYear() == null ? 0 : this.getCurrentYear()
						.hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getIclyBalance() == null ? 0 : this.getIclyBalance()
						.hashCode());
		result = 37
				* result
				+ (getIslyBalance() == null ? 0 : this.getIslyBalance()
						.hashCode());
		result = 37
				* result
				+ (getIalyBalance() == null ? 0 : this.getIalyBalance()
						.hashCode());
		result = 37
				* result
				+ (getImlyBalance() == null ? 0 : this.getImlyBalance()
						.hashCode());
		result = 37
				* result
				+ (getIclOpening() == null ? 0 : this.getIclOpening()
						.hashCode());
		result = 37 * result
				+ (getIcarryCl() == null ? 0 : this.getIcarryCl().hashCode());
		result = 37
				* result
				+ (getIslOpening() == null ? 0 : this.getIslOpening()
						.hashCode());
		result = 37 * result
				+ (getIcarrySl() == null ? 0 : this.getIcarrySl().hashCode());
		result = 37
				* result
				+ (getIalOpening() == null ? 0 : this.getIalOpening()
						.hashCode());
		result = 37 * result
				+ (getIcarryAl() == null ? 0 : this.getIcarryAl().hashCode());
		result = 37
				* result
				+ (getImlOpening() == null ? 0 : this.getImlOpening()
						.hashCode());
		result = 37 * result
				+ (getIcarryMl() == null ? 0 : this.getIcarryMl().hashCode());
		result = 37
				* result
				+ (getIclBalance() == null ? 0 : this.getIclBalance()
						.hashCode());
		result = 37
				* result
				+ (getIslBalance() == null ? 0 : this.getIslBalance()
						.hashCode());
		result = 37
				* result
				+ (getIalBalance() == null ? 0 : this.getIalBalance()
						.hashCode());
		result = 37
				* result
				+ (getImlBalance() == null ? 0 : this.getImlBalance()
						.hashCode());
		result = 37
				* result
				+ (getIclEnjoyed() == null ? 0 : this.getIclEnjoyed()
						.hashCode());
		result = 37
				* result
				+ (getIslEnjoyed() == null ? 0 : this.getIslEnjoyed()
						.hashCode());
		result = 37
				* result
				+ (getIalEnjoyed() == null ? 0 : this.getIalEnjoyed()
						.hashCode());
		result = 37
				* result
				+ (getImlEnjoyed() == null ? 0 : this.getImlEnjoyed()
						.hashCode());
		result = 37 * result
				+ (getIflag() == null ? 0 : this.getIflag().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		return result;
	}

}
