package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbLeaveType generated by hbm2java
 */
public class TbLeaveType implements java.io.Serializable {

	private TbLeaveTypeId id;

	public TbLeaveType() {
	}

	public TbLeaveType(TbLeaveTypeId id) {
		this.id = id;
	}

	public TbLeaveTypeId getId() {
		return this.id;
	}

	public void setId(TbLeaveTypeId id) {
		this.id = id;
	}

}
