package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbLeaveTypeId generated by hbm2java
 */
public class TbLeaveTypeId implements java.io.Serializable {

	private int autoId;
	private int ileaveTypeId;
	private String vleaveTypeName;
	private String vuserName;
	private Date ddateTime;
	private String vpcip;

	public TbLeaveTypeId() {
	}

	public TbLeaveTypeId(int autoId, int ileaveTypeId, String vleaveTypeName,
			String vuserName, Date ddateTime, String vpcip) {
		this.autoId = autoId;
		this.ileaveTypeId = ileaveTypeId;
		this.vleaveTypeName = vleaveTypeName;
		this.vuserName = vuserName;
		this.ddateTime = ddateTime;
		this.vpcip = vpcip;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public int getIleaveTypeId() {
		return this.ileaveTypeId;
	}

	public void setIleaveTypeId(int ileaveTypeId) {
		this.ileaveTypeId = ileaveTypeId;
	}

	public String getVleaveTypeName() {
		return this.vleaveTypeName;
	}

	public void setVleaveTypeName(String vleaveTypeName) {
		this.vleaveTypeName = vleaveTypeName;
	}

	public String getVuserName() {
		return this.vuserName;
	}

	public void setVuserName(String vuserName) {
		this.vuserName = vuserName;
	}

	public Date getDdateTime() {
		return this.ddateTime;
	}

	public void setDdateTime(Date ddateTime) {
		this.ddateTime = ddateTime;
	}

	public String getVpcip() {
		return this.vpcip;
	}

	public void setVpcip(String vpcip) {
		this.vpcip = vpcip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLeaveTypeId))
			return false;
		TbLeaveTypeId castOther = (TbLeaveTypeId) other;

		return (this.getAutoId() == castOther.getAutoId())
				&& (this.getIleaveTypeId() == castOther.getIleaveTypeId())
				&& ((this.getVleaveTypeName() == castOther.getVleaveTypeName()) || (this
						.getVleaveTypeName() != null
						&& castOther.getVleaveTypeName() != null && this
						.getVleaveTypeName().equals(
								castOther.getVleaveTypeName())))
				&& ((this.getVuserName() == castOther.getVuserName()) || (this
						.getVuserName() != null
						&& castOther.getVuserName() != null && this
						.getVuserName().equals(castOther.getVuserName())))
				&& ((this.getDdateTime() == castOther.getDdateTime()) || (this
						.getDdateTime() != null
						&& castOther.getDdateTime() != null && this
						.getDdateTime().equals(castOther.getDdateTime())))
				&& ((this.getVpcip() == castOther.getVpcip()) || (this
						.getVpcip() != null && castOther.getVpcip() != null && this
						.getVpcip().equals(castOther.getVpcip())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAutoId();
		result = 37 * result + this.getIleaveTypeId();
		result = 37
				* result
				+ (getVleaveTypeName() == null ? 0 : this.getVleaveTypeName()
						.hashCode());
		result = 37 * result
				+ (getVuserName() == null ? 0 : this.getVuserName().hashCode());
		result = 37 * result
				+ (getDdateTime() == null ? 0 : this.getDdateTime().hashCode());
		result = 37 * result
				+ (getVpcip() == null ? 0 : this.getVpcip().hashCode());
		return result;
	}

}
