package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbLoanApplication generated by hbm2java
 */
public class TbLoanApplication implements java.io.Serializable {

	private TbLoanApplicationId id;

	public TbLoanApplication() {
	}

	public TbLoanApplication(TbLoanApplicationId id) {
		this.id = id;
	}

	public TbLoanApplicationId getId() {
		return this.id;
	}

	public void setId(TbLoanApplicationId id) {
		this.id = id;
	}

}
