package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbLoanApplicationId generated by hbm2java
 */
public class TbLoanApplicationId implements java.io.Serializable {

	private int iautoId;
	private String vloanNo;
	private Date dapplicationDate;
	private String vemployeeId;
	private String vsectionId;
	private String vdesignationId;
	private Date djoiningDate;
	private BigDecimal mgrossSalary;
	private String vloanType;
	private BigDecimal mloanAmount;
	private BigDecimal minterestRate;
	private BigDecimal minterestAmount;
	private BigDecimal mgrossAmount;
	private String vloanPurpose;
	private String minstallmentNo;
	private BigDecimal mamountPerInstall;
	private Date dpaymentStart;
	private String vadjustType;
	private Date dsanctionDate;
	private BigDecimal msanctionAmount;
	private Integer isanctionStatus;
	private Integer iloanStatus;
	private BigDecimal mloanBalance;
	private String vuserId;
	private String vuserIp;
	private Date dentryTime;

	public TbLoanApplicationId() {
	}

	public TbLoanApplicationId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbLoanApplicationId(int iautoId, String vloanNo,
			Date dapplicationDate, String vemployeeId, String vsectionId,
			String vdesignationId, Date djoiningDate, BigDecimal mgrossSalary,
			String vloanType, BigDecimal mloanAmount, BigDecimal minterestRate,
			BigDecimal minterestAmount, BigDecimal mgrossAmount,
			String vloanPurpose, String minstallmentNo,
			BigDecimal mamountPerInstall, Date dpaymentStart,
			String vadjustType, Date dsanctionDate, BigDecimal msanctionAmount,
			Integer isanctionStatus, Integer iloanStatus,
			BigDecimal mloanBalance, String vuserId, String vuserIp,
			Date dentryTime) {
		this.iautoId = iautoId;
		this.vloanNo = vloanNo;
		this.dapplicationDate = dapplicationDate;
		this.vemployeeId = vemployeeId;
		this.vsectionId = vsectionId;
		this.vdesignationId = vdesignationId;
		this.djoiningDate = djoiningDate;
		this.mgrossSalary = mgrossSalary;
		this.vloanType = vloanType;
		this.mloanAmount = mloanAmount;
		this.minterestRate = minterestRate;
		this.minterestAmount = minterestAmount;
		this.mgrossAmount = mgrossAmount;
		this.vloanPurpose = vloanPurpose;
		this.minstallmentNo = minstallmentNo;
		this.mamountPerInstall = mamountPerInstall;
		this.dpaymentStart = dpaymentStart;
		this.vadjustType = vadjustType;
		this.dsanctionDate = dsanctionDate;
		this.msanctionAmount = msanctionAmount;
		this.isanctionStatus = isanctionStatus;
		this.iloanStatus = iloanStatus;
		this.mloanBalance = mloanBalance;
		this.vuserId = vuserId;
		this.vuserIp = vuserIp;
		this.dentryTime = dentryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public String getVloanNo() {
		return this.vloanNo;
	}

	public void setVloanNo(String vloanNo) {
		this.vloanNo = vloanNo;
	}

	public Date getDapplicationDate() {
		return this.dapplicationDate;
	}

	public void setDapplicationDate(Date dapplicationDate) {
		this.dapplicationDate = dapplicationDate;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public Date getDjoiningDate() {
		return this.djoiningDate;
	}

	public void setDjoiningDate(Date djoiningDate) {
		this.djoiningDate = djoiningDate;
	}

	public BigDecimal getMgrossSalary() {
		return this.mgrossSalary;
	}

	public void setMgrossSalary(BigDecimal mgrossSalary) {
		this.mgrossSalary = mgrossSalary;
	}

	public String getVloanType() {
		return this.vloanType;
	}

	public void setVloanType(String vloanType) {
		this.vloanType = vloanType;
	}

	public BigDecimal getMloanAmount() {
		return this.mloanAmount;
	}

	public void setMloanAmount(BigDecimal mloanAmount) {
		this.mloanAmount = mloanAmount;
	}

	public BigDecimal getMinterestRate() {
		return this.minterestRate;
	}

	public void setMinterestRate(BigDecimal minterestRate) {
		this.minterestRate = minterestRate;
	}

	public BigDecimal getMinterestAmount() {
		return this.minterestAmount;
	}

	public void setMinterestAmount(BigDecimal minterestAmount) {
		this.minterestAmount = minterestAmount;
	}

	public BigDecimal getMgrossAmount() {
		return this.mgrossAmount;
	}

	public void setMgrossAmount(BigDecimal mgrossAmount) {
		this.mgrossAmount = mgrossAmount;
	}

	public String getVloanPurpose() {
		return this.vloanPurpose;
	}

	public void setVloanPurpose(String vloanPurpose) {
		this.vloanPurpose = vloanPurpose;
	}

	public String getMinstallmentNo() {
		return this.minstallmentNo;
	}

	public void setMinstallmentNo(String minstallmentNo) {
		this.minstallmentNo = minstallmentNo;
	}

	public BigDecimal getMamountPerInstall() {
		return this.mamountPerInstall;
	}

	public void setMamountPerInstall(BigDecimal mamountPerInstall) {
		this.mamountPerInstall = mamountPerInstall;
	}

	public Date getDpaymentStart() {
		return this.dpaymentStart;
	}

	public void setDpaymentStart(Date dpaymentStart) {
		this.dpaymentStart = dpaymentStart;
	}

	public String getVadjustType() {
		return this.vadjustType;
	}

	public void setVadjustType(String vadjustType) {
		this.vadjustType = vadjustType;
	}

	public Date getDsanctionDate() {
		return this.dsanctionDate;
	}

	public void setDsanctionDate(Date dsanctionDate) {
		this.dsanctionDate = dsanctionDate;
	}

	public BigDecimal getMsanctionAmount() {
		return this.msanctionAmount;
	}

	public void setMsanctionAmount(BigDecimal msanctionAmount) {
		this.msanctionAmount = msanctionAmount;
	}

	public Integer getIsanctionStatus() {
		return this.isanctionStatus;
	}

	public void setIsanctionStatus(Integer isanctionStatus) {
		this.isanctionStatus = isanctionStatus;
	}

	public Integer getIloanStatus() {
		return this.iloanStatus;
	}

	public void setIloanStatus(Integer iloanStatus) {
		this.iloanStatus = iloanStatus;
	}

	public BigDecimal getMloanBalance() {
		return this.mloanBalance;
	}

	public void setMloanBalance(BigDecimal mloanBalance) {
		this.mloanBalance = mloanBalance;
	}

	public String getVuserId() {
		return this.vuserId;
	}

	public void setVuserId(String vuserId) {
		this.vuserId = vuserId;
	}

	public String getVuserIp() {
		return this.vuserIp;
	}

	public void setVuserIp(String vuserIp) {
		this.vuserIp = vuserIp;
	}

	public Date getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(Date dentryTime) {
		this.dentryTime = dentryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLoanApplicationId))
			return false;
		TbLoanApplicationId castOther = (TbLoanApplicationId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVloanNo() == castOther.getVloanNo()) || (this
						.getVloanNo() != null && castOther.getVloanNo() != null && this
						.getVloanNo().equals(castOther.getVloanNo())))
				&& ((this.getDapplicationDate() == castOther
						.getDapplicationDate()) || (this.getDapplicationDate() != null
						&& castOther.getDapplicationDate() != null && this
						.getDapplicationDate().equals(
								castOther.getDapplicationDate())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getDjoiningDate() == castOther.getDjoiningDate()) || (this
						.getDjoiningDate() != null
						&& castOther.getDjoiningDate() != null && this
						.getDjoiningDate().equals(castOther.getDjoiningDate())))
				&& ((this.getMgrossSalary() == castOther.getMgrossSalary()) || (this
						.getMgrossSalary() != null
						&& castOther.getMgrossSalary() != null && this
						.getMgrossSalary().equals(castOther.getMgrossSalary())))
				&& ((this.getVloanType() == castOther.getVloanType()) || (this
						.getVloanType() != null
						&& castOther.getVloanType() != null && this
						.getVloanType().equals(castOther.getVloanType())))
				&& ((this.getMloanAmount() == castOther.getMloanAmount()) || (this
						.getMloanAmount() != null
						&& castOther.getMloanAmount() != null && this
						.getMloanAmount().equals(castOther.getMloanAmount())))
				&& ((this.getMinterestRate() == castOther.getMinterestRate()) || (this
						.getMinterestRate() != null
						&& castOther.getMinterestRate() != null && this
						.getMinterestRate()
						.equals(castOther.getMinterestRate())))
				&& ((this.getMinterestAmount() == castOther
						.getMinterestAmount()) || (this.getMinterestAmount() != null
						&& castOther.getMinterestAmount() != null && this
						.getMinterestAmount().equals(
								castOther.getMinterestAmount())))
				&& ((this.getMgrossAmount() == castOther.getMgrossAmount()) || (this
						.getMgrossAmount() != null
						&& castOther.getMgrossAmount() != null && this
						.getMgrossAmount().equals(castOther.getMgrossAmount())))
				&& ((this.getVloanPurpose() == castOther.getVloanPurpose()) || (this
						.getVloanPurpose() != null
						&& castOther.getVloanPurpose() != null && this
						.getVloanPurpose().equals(castOther.getVloanPurpose())))
				&& ((this.getMinstallmentNo() == castOther.getMinstallmentNo()) || (this
						.getMinstallmentNo() != null
						&& castOther.getMinstallmentNo() != null && this
						.getMinstallmentNo().equals(
								castOther.getMinstallmentNo())))
				&& ((this.getMamountPerInstall() == castOther
						.getMamountPerInstall()) || (this
						.getMamountPerInstall() != null
						&& castOther.getMamountPerInstall() != null && this
						.getMamountPerInstall().equals(
								castOther.getMamountPerInstall())))
				&& ((this.getDpaymentStart() == castOther.getDpaymentStart()) || (this
						.getDpaymentStart() != null
						&& castOther.getDpaymentStart() != null && this
						.getDpaymentStart()
						.equals(castOther.getDpaymentStart())))
				&& ((this.getVadjustType() == castOther.getVadjustType()) || (this
						.getVadjustType() != null
						&& castOther.getVadjustType() != null && this
						.getVadjustType().equals(castOther.getVadjustType())))
				&& ((this.getDsanctionDate() == castOther.getDsanctionDate()) || (this
						.getDsanctionDate() != null
						&& castOther.getDsanctionDate() != null && this
						.getDsanctionDate()
						.equals(castOther.getDsanctionDate())))
				&& ((this.getMsanctionAmount() == castOther
						.getMsanctionAmount()) || (this.getMsanctionAmount() != null
						&& castOther.getMsanctionAmount() != null && this
						.getMsanctionAmount().equals(
								castOther.getMsanctionAmount())))
				&& ((this.getIsanctionStatus() == castOther
						.getIsanctionStatus()) || (this.getIsanctionStatus() != null
						&& castOther.getIsanctionStatus() != null && this
						.getIsanctionStatus().equals(
								castOther.getIsanctionStatus())))
				&& ((this.getIloanStatus() == castOther.getIloanStatus()) || (this
						.getIloanStatus() != null
						&& castOther.getIloanStatus() != null && this
						.getIloanStatus().equals(castOther.getIloanStatus())))
				&& ((this.getMloanBalance() == castOther.getMloanBalance()) || (this
						.getMloanBalance() != null
						&& castOther.getMloanBalance() != null && this
						.getMloanBalance().equals(castOther.getMloanBalance())))
				&& ((this.getVuserId() == castOther.getVuserId()) || (this
						.getVuserId() != null && castOther.getVuserId() != null && this
						.getVuserId().equals(castOther.getVuserId())))
				&& ((this.getVuserIp() == castOther.getVuserIp()) || (this
						.getVuserIp() != null && castOther.getVuserIp() != null && this
						.getVuserIp().equals(castOther.getVuserIp())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result
				+ (getVloanNo() == null ? 0 : this.getVloanNo().hashCode());
		result = 37
				* result
				+ (getDapplicationDate() == null ? 0 : this
						.getDapplicationDate().hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37
				* result
				+ (getDjoiningDate() == null ? 0 : this.getDjoiningDate()
						.hashCode());
		result = 37
				* result
				+ (getMgrossSalary() == null ? 0 : this.getMgrossSalary()
						.hashCode());
		result = 37 * result
				+ (getVloanType() == null ? 0 : this.getVloanType().hashCode());
		result = 37
				* result
				+ (getMloanAmount() == null ? 0 : this.getMloanAmount()
						.hashCode());
		result = 37
				* result
				+ (getMinterestRate() == null ? 0 : this.getMinterestRate()
						.hashCode());
		result = 37
				* result
				+ (getMinterestAmount() == null ? 0 : this.getMinterestAmount()
						.hashCode());
		result = 37
				* result
				+ (getMgrossAmount() == null ? 0 : this.getMgrossAmount()
						.hashCode());
		result = 37
				* result
				+ (getVloanPurpose() == null ? 0 : this.getVloanPurpose()
						.hashCode());
		result = 37
				* result
				+ (getMinstallmentNo() == null ? 0 : this.getMinstallmentNo()
						.hashCode());
		result = 37
				* result
				+ (getMamountPerInstall() == null ? 0 : this
						.getMamountPerInstall().hashCode());
		result = 37
				* result
				+ (getDpaymentStart() == null ? 0 : this.getDpaymentStart()
						.hashCode());
		result = 37
				* result
				+ (getVadjustType() == null ? 0 : this.getVadjustType()
						.hashCode());
		result = 37
				* result
				+ (getDsanctionDate() == null ? 0 : this.getDsanctionDate()
						.hashCode());
		result = 37
				* result
				+ (getMsanctionAmount() == null ? 0 : this.getMsanctionAmount()
						.hashCode());
		result = 37
				* result
				+ (getIsanctionStatus() == null ? 0 : this.getIsanctionStatus()
						.hashCode());
		result = 37
				* result
				+ (getIloanStatus() == null ? 0 : this.getIloanStatus()
						.hashCode());
		result = 37
				* result
				+ (getMloanBalance() == null ? 0 : this.getMloanBalance()
						.hashCode());
		result = 37 * result
				+ (getVuserId() == null ? 0 : this.getVuserId().hashCode());
		result = 37 * result
				+ (getVuserIp() == null ? 0 : this.getVuserIp().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		return result;
	}

}
