package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbLoginDetails generated by hbm2java
 */
public class TbLoginDetails implements java.io.Serializable {

	private TbLoginDetailsId id;

	public TbLoginDetails() {
	}

	public TbLoginDetails(TbLoginDetailsId id) {
		this.id = id;
	}

	public TbLoginDetailsId getId() {
		return this.id;
	}

	public void setId(TbLoginDetailsId id) {
		this.id = id;
	}

}
