package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbMonthlySalaryDetails generated by hbm2java
 */
public class TbMonthlySalaryDetails implements java.io.Serializable {

	private TbMonthlySalaryDetailsId id;

	public TbMonthlySalaryDetails() {
	}

	public TbMonthlySalaryDetails(TbMonthlySalaryDetailsId id) {
		this.id = id;
	}

	public TbMonthlySalaryDetailsId getId() {
		return this.id;
	}

	public void setId(TbMonthlySalaryDetailsId id) {
		this.id = id;
	}

}
