package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbMonthlySalaryDetailsId generated by hbm2java
 */
public class TbMonthlySalaryDetailsId implements java.io.Serializable {

	private int iautoId;
	private int igenerateId;
	private Date dgenerateDate;
	private String vsectionId;
	private String vemployeeId;
	private String idesignationId;
	private Date dsalaryOfMonth;
	private Integer isalaryYear;
	private Integer isalaryMonth;
	private String vsalaryMonth;
	private Integer itotalDays;
	private Integer inoOfFridays;
	private Integer inoOfHolidays;
	private Integer ileaveDay;
	private Integer itourDay;
	private Integer ioffDay;
	private Integer iabsentDay;
	private Integer inoOfWorkingDays;
	private Integer ipresentDays;
	private BigDecimal mbasic;
	private BigDecimal mhouseRent;
	private BigDecimal mmedicalAllowance;
	private BigDecimal mconveyance;
	private BigDecimal mspecial;
	private BigDecimal motherAllowance;
	private BigDecimal mprovidentFund;
	private BigDecimal mkfund;
	private String votHour;
	private BigDecimal motAmount;
	private BigDecimal mfestivalBonusAmt;
	private BigDecimal mbonusPercentOnBasic;
	private BigDecimal mbonusPercentOnGross;
	private BigDecimal mabsentAmount;
	private BigDecimal madvanceSalary;
	private String vloanTranId;
	private String vloanNo;
	private BigDecimal mloanAmount;
	private BigDecimal mloanDeduction;
	private BigDecimal mrevenueStamp;
	private BigDecimal mbonusRevenueStamp;
	private String vbankId;
	private String vbankBranchId;
	private String vaccountNo;
	private String vuserId;
	private String vuserIp;
	private Date dentryTime;
	private BigDecimal otrate;

	public TbMonthlySalaryDetailsId() {
	}

	public TbMonthlySalaryDetailsId(int iautoId, int igenerateId) {
		this.iautoId = iautoId;
		this.igenerateId = igenerateId;
	}

	public TbMonthlySalaryDetailsId(int iautoId, int igenerateId,
			Date dgenerateDate, String vsectionId, String vemployeeId,
			String idesignationId, Date dsalaryOfMonth, Integer isalaryYear,
			Integer isalaryMonth, String vsalaryMonth, Integer itotalDays,
			Integer inoOfFridays, Integer inoOfHolidays, Integer ileaveDay,
			Integer itourDay, Integer ioffDay, Integer iabsentDay,
			Integer inoOfWorkingDays, Integer ipresentDays, BigDecimal mbasic,
			BigDecimal mhouseRent, BigDecimal mmedicalAllowance,
			BigDecimal mconveyance, BigDecimal mspecial,
			BigDecimal motherAllowance, BigDecimal mprovidentFund,
			BigDecimal mkfund, String votHour, BigDecimal motAmount,
			BigDecimal mfestivalBonusAmt, BigDecimal mbonusPercentOnBasic,
			BigDecimal mbonusPercentOnGross, BigDecimal mabsentAmount,
			BigDecimal madvanceSalary, String vloanTranId, String vloanNo,
			BigDecimal mloanAmount, BigDecimal mloanDeduction,
			BigDecimal mrevenueStamp, BigDecimal mbonusRevenueStamp,
			String vbankId, String vbankBranchId, String vaccountNo,
			String vuserId, String vuserIp, Date dentryTime, BigDecimal otrate) {
		this.iautoId = iautoId;
		this.igenerateId = igenerateId;
		this.dgenerateDate = dgenerateDate;
		this.vsectionId = vsectionId;
		this.vemployeeId = vemployeeId;
		this.idesignationId = idesignationId;
		this.dsalaryOfMonth = dsalaryOfMonth;
		this.isalaryYear = isalaryYear;
		this.isalaryMonth = isalaryMonth;
		this.vsalaryMonth = vsalaryMonth;
		this.itotalDays = itotalDays;
		this.inoOfFridays = inoOfFridays;
		this.inoOfHolidays = inoOfHolidays;
		this.ileaveDay = ileaveDay;
		this.itourDay = itourDay;
		this.ioffDay = ioffDay;
		this.iabsentDay = iabsentDay;
		this.inoOfWorkingDays = inoOfWorkingDays;
		this.ipresentDays = ipresentDays;
		this.mbasic = mbasic;
		this.mhouseRent = mhouseRent;
		this.mmedicalAllowance = mmedicalAllowance;
		this.mconveyance = mconveyance;
		this.mspecial = mspecial;
		this.motherAllowance = motherAllowance;
		this.mprovidentFund = mprovidentFund;
		this.mkfund = mkfund;
		this.votHour = votHour;
		this.motAmount = motAmount;
		this.mfestivalBonusAmt = mfestivalBonusAmt;
		this.mbonusPercentOnBasic = mbonusPercentOnBasic;
		this.mbonusPercentOnGross = mbonusPercentOnGross;
		this.mabsentAmount = mabsentAmount;
		this.madvanceSalary = madvanceSalary;
		this.vloanTranId = vloanTranId;
		this.vloanNo = vloanNo;
		this.mloanAmount = mloanAmount;
		this.mloanDeduction = mloanDeduction;
		this.mrevenueStamp = mrevenueStamp;
		this.mbonusRevenueStamp = mbonusRevenueStamp;
		this.vbankId = vbankId;
		this.vbankBranchId = vbankBranchId;
		this.vaccountNo = vaccountNo;
		this.vuserId = vuserId;
		this.vuserIp = vuserIp;
		this.dentryTime = dentryTime;
		this.otrate = otrate;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public int getIgenerateId() {
		return this.igenerateId;
	}

	public void setIgenerateId(int igenerateId) {
		this.igenerateId = igenerateId;
	}

	public Date getDgenerateDate() {
		return this.dgenerateDate;
	}

	public void setDgenerateDate(Date dgenerateDate) {
		this.dgenerateDate = dgenerateDate;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getIdesignationId() {
		return this.idesignationId;
	}

	public void setIdesignationId(String idesignationId) {
		this.idesignationId = idesignationId;
	}

	public Date getDsalaryOfMonth() {
		return this.dsalaryOfMonth;
	}

	public void setDsalaryOfMonth(Date dsalaryOfMonth) {
		this.dsalaryOfMonth = dsalaryOfMonth;
	}

	public Integer getIsalaryYear() {
		return this.isalaryYear;
	}

	public void setIsalaryYear(Integer isalaryYear) {
		this.isalaryYear = isalaryYear;
	}

	public Integer getIsalaryMonth() {
		return this.isalaryMonth;
	}

	public void setIsalaryMonth(Integer isalaryMonth) {
		this.isalaryMonth = isalaryMonth;
	}

	public String getVsalaryMonth() {
		return this.vsalaryMonth;
	}

	public void setVsalaryMonth(String vsalaryMonth) {
		this.vsalaryMonth = vsalaryMonth;
	}

	public Integer getItotalDays() {
		return this.itotalDays;
	}

	public void setItotalDays(Integer itotalDays) {
		this.itotalDays = itotalDays;
	}

	public Integer getInoOfFridays() {
		return this.inoOfFridays;
	}

	public void setInoOfFridays(Integer inoOfFridays) {
		this.inoOfFridays = inoOfFridays;
	}

	public Integer getInoOfHolidays() {
		return this.inoOfHolidays;
	}

	public void setInoOfHolidays(Integer inoOfHolidays) {
		this.inoOfHolidays = inoOfHolidays;
	}

	public Integer getIleaveDay() {
		return this.ileaveDay;
	}

	public void setIleaveDay(Integer ileaveDay) {
		this.ileaveDay = ileaveDay;
	}

	public Integer getItourDay() {
		return this.itourDay;
	}

	public void setItourDay(Integer itourDay) {
		this.itourDay = itourDay;
	}

	public Integer getIoffDay() {
		return this.ioffDay;
	}

	public void setIoffDay(Integer ioffDay) {
		this.ioffDay = ioffDay;
	}

	public Integer getIabsentDay() {
		return this.iabsentDay;
	}

	public void setIabsentDay(Integer iabsentDay) {
		this.iabsentDay = iabsentDay;
	}

	public Integer getInoOfWorkingDays() {
		return this.inoOfWorkingDays;
	}

	public void setInoOfWorkingDays(Integer inoOfWorkingDays) {
		this.inoOfWorkingDays = inoOfWorkingDays;
	}

	public Integer getIpresentDays() {
		return this.ipresentDays;
	}

	public void setIpresentDays(Integer ipresentDays) {
		this.ipresentDays = ipresentDays;
	}

	public BigDecimal getMbasic() {
		return this.mbasic;
	}

	public void setMbasic(BigDecimal mbasic) {
		this.mbasic = mbasic;
	}

	public BigDecimal getMhouseRent() {
		return this.mhouseRent;
	}

	public void setMhouseRent(BigDecimal mhouseRent) {
		this.mhouseRent = mhouseRent;
	}

	public BigDecimal getMmedicalAllowance() {
		return this.mmedicalAllowance;
	}

	public void setMmedicalAllowance(BigDecimal mmedicalAllowance) {
		this.mmedicalAllowance = mmedicalAllowance;
	}

	public BigDecimal getMconveyance() {
		return this.mconveyance;
	}

	public void setMconveyance(BigDecimal mconveyance) {
		this.mconveyance = mconveyance;
	}

	public BigDecimal getMspecial() {
		return this.mspecial;
	}

	public void setMspecial(BigDecimal mspecial) {
		this.mspecial = mspecial;
	}

	public BigDecimal getMotherAllowance() {
		return this.motherAllowance;
	}

	public void setMotherAllowance(BigDecimal motherAllowance) {
		this.motherAllowance = motherAllowance;
	}

	public BigDecimal getMprovidentFund() {
		return this.mprovidentFund;
	}

	public void setMprovidentFund(BigDecimal mprovidentFund) {
		this.mprovidentFund = mprovidentFund;
	}

	public BigDecimal getMkfund() {
		return this.mkfund;
	}

	public void setMkfund(BigDecimal mkfund) {
		this.mkfund = mkfund;
	}

	public String getVotHour() {
		return this.votHour;
	}

	public void setVotHour(String votHour) {
		this.votHour = votHour;
	}

	public BigDecimal getMotAmount() {
		return this.motAmount;
	}

	public void setMotAmount(BigDecimal motAmount) {
		this.motAmount = motAmount;
	}

	public BigDecimal getMfestivalBonusAmt() {
		return this.mfestivalBonusAmt;
	}

	public void setMfestivalBonusAmt(BigDecimal mfestivalBonusAmt) {
		this.mfestivalBonusAmt = mfestivalBonusAmt;
	}

	public BigDecimal getMbonusPercentOnBasic() {
		return this.mbonusPercentOnBasic;
	}

	public void setMbonusPercentOnBasic(BigDecimal mbonusPercentOnBasic) {
		this.mbonusPercentOnBasic = mbonusPercentOnBasic;
	}

	public BigDecimal getMbonusPercentOnGross() {
		return this.mbonusPercentOnGross;
	}

	public void setMbonusPercentOnGross(BigDecimal mbonusPercentOnGross) {
		this.mbonusPercentOnGross = mbonusPercentOnGross;
	}

	public BigDecimal getMabsentAmount() {
		return this.mabsentAmount;
	}

	public void setMabsentAmount(BigDecimal mabsentAmount) {
		this.mabsentAmount = mabsentAmount;
	}

	public BigDecimal getMadvanceSalary() {
		return this.madvanceSalary;
	}

	public void setMadvanceSalary(BigDecimal madvanceSalary) {
		this.madvanceSalary = madvanceSalary;
	}

	public String getVloanTranId() {
		return this.vloanTranId;
	}

	public void setVloanTranId(String vloanTranId) {
		this.vloanTranId = vloanTranId;
	}

	public String getVloanNo() {
		return this.vloanNo;
	}

	public void setVloanNo(String vloanNo) {
		this.vloanNo = vloanNo;
	}

	public BigDecimal getMloanAmount() {
		return this.mloanAmount;
	}

	public void setMloanAmount(BigDecimal mloanAmount) {
		this.mloanAmount = mloanAmount;
	}

	public BigDecimal getMloanDeduction() {
		return this.mloanDeduction;
	}

	public void setMloanDeduction(BigDecimal mloanDeduction) {
		this.mloanDeduction = mloanDeduction;
	}

	public BigDecimal getMrevenueStamp() {
		return this.mrevenueStamp;
	}

	public void setMrevenueStamp(BigDecimal mrevenueStamp) {
		this.mrevenueStamp = mrevenueStamp;
	}

	public BigDecimal getMbonusRevenueStamp() {
		return this.mbonusRevenueStamp;
	}

	public void setMbonusRevenueStamp(BigDecimal mbonusRevenueStamp) {
		this.mbonusRevenueStamp = mbonusRevenueStamp;
	}

	public String getVbankId() {
		return this.vbankId;
	}

	public void setVbankId(String vbankId) {
		this.vbankId = vbankId;
	}

	public String getVbankBranchId() {
		return this.vbankBranchId;
	}

	public void setVbankBranchId(String vbankBranchId) {
		this.vbankBranchId = vbankBranchId;
	}

	public String getVaccountNo() {
		return this.vaccountNo;
	}

	public void setVaccountNo(String vaccountNo) {
		this.vaccountNo = vaccountNo;
	}

	public String getVuserId() {
		return this.vuserId;
	}

	public void setVuserId(String vuserId) {
		this.vuserId = vuserId;
	}

	public String getVuserIp() {
		return this.vuserIp;
	}

	public void setVuserIp(String vuserIp) {
		this.vuserIp = vuserIp;
	}

	public Date getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(Date dentryTime) {
		this.dentryTime = dentryTime;
	}

	public BigDecimal getOtrate() {
		return this.otrate;
	}

	public void setOtrate(BigDecimal otrate) {
		this.otrate = otrate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbMonthlySalaryDetailsId))
			return false;
		TbMonthlySalaryDetailsId castOther = (TbMonthlySalaryDetailsId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& (this.getIgenerateId() == castOther.getIgenerateId())
				&& ((this.getDgenerateDate() == castOther.getDgenerateDate()) || (this
						.getDgenerateDate() != null
						&& castOther.getDgenerateDate() != null && this
						.getDgenerateDate()
						.equals(castOther.getDgenerateDate())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getIdesignationId() == castOther.getIdesignationId()) || (this
						.getIdesignationId() != null
						&& castOther.getIdesignationId() != null && this
						.getIdesignationId().equals(
								castOther.getIdesignationId())))
				&& ((this.getDsalaryOfMonth() == castOther.getDsalaryOfMonth()) || (this
						.getDsalaryOfMonth() != null
						&& castOther.getDsalaryOfMonth() != null && this
						.getDsalaryOfMonth().equals(
								castOther.getDsalaryOfMonth())))
				&& ((this.getIsalaryYear() == castOther.getIsalaryYear()) || (this
						.getIsalaryYear() != null
						&& castOther.getIsalaryYear() != null && this
						.getIsalaryYear().equals(castOther.getIsalaryYear())))
				&& ((this.getIsalaryMonth() == castOther.getIsalaryMonth()) || (this
						.getIsalaryMonth() != null
						&& castOther.getIsalaryMonth() != null && this
						.getIsalaryMonth().equals(castOther.getIsalaryMonth())))
				&& ((this.getVsalaryMonth() == castOther.getVsalaryMonth()) || (this
						.getVsalaryMonth() != null
						&& castOther.getVsalaryMonth() != null && this
						.getVsalaryMonth().equals(castOther.getVsalaryMonth())))
				&& ((this.getItotalDays() == castOther.getItotalDays()) || (this
						.getItotalDays() != null
						&& castOther.getItotalDays() != null && this
						.getItotalDays().equals(castOther.getItotalDays())))
				&& ((this.getInoOfFridays() == castOther.getInoOfFridays()) || (this
						.getInoOfFridays() != null
						&& castOther.getInoOfFridays() != null && this
						.getInoOfFridays().equals(castOther.getInoOfFridays())))
				&& ((this.getInoOfHolidays() == castOther.getInoOfHolidays()) || (this
						.getInoOfHolidays() != null
						&& castOther.getInoOfHolidays() != null && this
						.getInoOfHolidays()
						.equals(castOther.getInoOfHolidays())))
				&& ((this.getIleaveDay() == castOther.getIleaveDay()) || (this
						.getIleaveDay() != null
						&& castOther.getIleaveDay() != null && this
						.getIleaveDay().equals(castOther.getIleaveDay())))
				&& ((this.getItourDay() == castOther.getItourDay()) || (this
						.getItourDay() != null
						&& castOther.getItourDay() != null && this
						.getItourDay().equals(castOther.getItourDay())))
				&& ((this.getIoffDay() == castOther.getIoffDay()) || (this
						.getIoffDay() != null && castOther.getIoffDay() != null && this
						.getIoffDay().equals(castOther.getIoffDay())))
				&& ((this.getIabsentDay() == castOther.getIabsentDay()) || (this
						.getIabsentDay() != null
						&& castOther.getIabsentDay() != null && this
						.getIabsentDay().equals(castOther.getIabsentDay())))
				&& ((this.getInoOfWorkingDays() == castOther
						.getInoOfWorkingDays()) || (this.getInoOfWorkingDays() != null
						&& castOther.getInoOfWorkingDays() != null && this
						.getInoOfWorkingDays().equals(
								castOther.getInoOfWorkingDays())))
				&& ((this.getIpresentDays() == castOther.getIpresentDays()) || (this
						.getIpresentDays() != null
						&& castOther.getIpresentDays() != null && this
						.getIpresentDays().equals(castOther.getIpresentDays())))
				&& ((this.getMbasic() == castOther.getMbasic()) || (this
						.getMbasic() != null && castOther.getMbasic() != null && this
						.getMbasic().equals(castOther.getMbasic())))
				&& ((this.getMhouseRent() == castOther.getMhouseRent()) || (this
						.getMhouseRent() != null
						&& castOther.getMhouseRent() != null && this
						.getMhouseRent().equals(castOther.getMhouseRent())))
				&& ((this.getMmedicalAllowance() == castOther
						.getMmedicalAllowance()) || (this
						.getMmedicalAllowance() != null
						&& castOther.getMmedicalAllowance() != null && this
						.getMmedicalAllowance().equals(
								castOther.getMmedicalAllowance())))
				&& ((this.getMconveyance() == castOther.getMconveyance()) || (this
						.getMconveyance() != null
						&& castOther.getMconveyance() != null && this
						.getMconveyance().equals(castOther.getMconveyance())))
				&& ((this.getMspecial() == castOther.getMspecial()) || (this
						.getMspecial() != null
						&& castOther.getMspecial() != null && this
						.getMspecial().equals(castOther.getMspecial())))
				&& ((this.getMotherAllowance() == castOther
						.getMotherAllowance()) || (this.getMotherAllowance() != null
						&& castOther.getMotherAllowance() != null && this
						.getMotherAllowance().equals(
								castOther.getMotherAllowance())))
				&& ((this.getMprovidentFund() == castOther.getMprovidentFund()) || (this
						.getMprovidentFund() != null
						&& castOther.getMprovidentFund() != null && this
						.getMprovidentFund().equals(
								castOther.getMprovidentFund())))
				&& ((this.getMkfund() == castOther.getMkfund()) || (this
						.getMkfund() != null && castOther.getMkfund() != null && this
						.getMkfund().equals(castOther.getMkfund())))
				&& ((this.getVotHour() == castOther.getVotHour()) || (this
						.getVotHour() != null && castOther.getVotHour() != null && this
						.getVotHour().equals(castOther.getVotHour())))
				&& ((this.getMotAmount() == castOther.getMotAmount()) || (this
						.getMotAmount() != null
						&& castOther.getMotAmount() != null && this
						.getMotAmount().equals(castOther.getMotAmount())))
				&& ((this.getMfestivalBonusAmt() == castOther
						.getMfestivalBonusAmt()) || (this
						.getMfestivalBonusAmt() != null
						&& castOther.getMfestivalBonusAmt() != null && this
						.getMfestivalBonusAmt().equals(
								castOther.getMfestivalBonusAmt())))
				&& ((this.getMbonusPercentOnBasic() == castOther
						.getMbonusPercentOnBasic()) || (this
						.getMbonusPercentOnBasic() != null
						&& castOther.getMbonusPercentOnBasic() != null && this
						.getMbonusPercentOnBasic().equals(
								castOther.getMbonusPercentOnBasic())))
				&& ((this.getMbonusPercentOnGross() == castOther
						.getMbonusPercentOnGross()) || (this
						.getMbonusPercentOnGross() != null
						&& castOther.getMbonusPercentOnGross() != null && this
						.getMbonusPercentOnGross().equals(
								castOther.getMbonusPercentOnGross())))
				&& ((this.getMabsentAmount() == castOther.getMabsentAmount()) || (this
						.getMabsentAmount() != null
						&& castOther.getMabsentAmount() != null && this
						.getMabsentAmount()
						.equals(castOther.getMabsentAmount())))
				&& ((this.getMadvanceSalary() == castOther.getMadvanceSalary()) || (this
						.getMadvanceSalary() != null
						&& castOther.getMadvanceSalary() != null && this
						.getMadvanceSalary().equals(
								castOther.getMadvanceSalary())))
				&& ((this.getVloanTranId() == castOther.getVloanTranId()) || (this
						.getVloanTranId() != null
						&& castOther.getVloanTranId() != null && this
						.getVloanTranId().equals(castOther.getVloanTranId())))
				&& ((this.getVloanNo() == castOther.getVloanNo()) || (this
						.getVloanNo() != null && castOther.getVloanNo() != null && this
						.getVloanNo().equals(castOther.getVloanNo())))
				&& ((this.getMloanAmount() == castOther.getMloanAmount()) || (this
						.getMloanAmount() != null
						&& castOther.getMloanAmount() != null && this
						.getMloanAmount().equals(castOther.getMloanAmount())))
				&& ((this.getMloanDeduction() == castOther.getMloanDeduction()) || (this
						.getMloanDeduction() != null
						&& castOther.getMloanDeduction() != null && this
						.getMloanDeduction().equals(
								castOther.getMloanDeduction())))
				&& ((this.getMrevenueStamp() == castOther.getMrevenueStamp()) || (this
						.getMrevenueStamp() != null
						&& castOther.getMrevenueStamp() != null && this
						.getMrevenueStamp()
						.equals(castOther.getMrevenueStamp())))
				&& ((this.getMbonusRevenueStamp() == castOther
						.getMbonusRevenueStamp()) || (this
						.getMbonusRevenueStamp() != null
						&& castOther.getMbonusRevenueStamp() != null && this
						.getMbonusRevenueStamp().equals(
								castOther.getMbonusRevenueStamp())))
				&& ((this.getVbankId() == castOther.getVbankId()) || (this
						.getVbankId() != null && castOther.getVbankId() != null && this
						.getVbankId().equals(castOther.getVbankId())))
				&& ((this.getVbankBranchId() == castOther.getVbankBranchId()) || (this
						.getVbankBranchId() != null
						&& castOther.getVbankBranchId() != null && this
						.getVbankBranchId()
						.equals(castOther.getVbankBranchId())))
				&& ((this.getVaccountNo() == castOther.getVaccountNo()) || (this
						.getVaccountNo() != null
						&& castOther.getVaccountNo() != null && this
						.getVaccountNo().equals(castOther.getVaccountNo())))
				&& ((this.getVuserId() == castOther.getVuserId()) || (this
						.getVuserId() != null && castOther.getVuserId() != null && this
						.getVuserId().equals(castOther.getVuserId())))
				&& ((this.getVuserIp() == castOther.getVuserIp()) || (this
						.getVuserIp() != null && castOther.getVuserIp() != null && this
						.getVuserIp().equals(castOther.getVuserIp())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())))
				&& ((this.getOtrate() == castOther.getOtrate()) || (this
						.getOtrate() != null && castOther.getOtrate() != null && this
						.getOtrate().equals(castOther.getOtrate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result + this.getIgenerateId();
		result = 37
				* result
				+ (getDgenerateDate() == null ? 0 : this.getDgenerateDate()
						.hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getIdesignationId() == null ? 0 : this.getIdesignationId()
						.hashCode());
		result = 37
				* result
				+ (getDsalaryOfMonth() == null ? 0 : this.getDsalaryOfMonth()
						.hashCode());
		result = 37
				* result
				+ (getIsalaryYear() == null ? 0 : this.getIsalaryYear()
						.hashCode());
		result = 37
				* result
				+ (getIsalaryMonth() == null ? 0 : this.getIsalaryMonth()
						.hashCode());
		result = 37
				* result
				+ (getVsalaryMonth() == null ? 0 : this.getVsalaryMonth()
						.hashCode());
		result = 37
				* result
				+ (getItotalDays() == null ? 0 : this.getItotalDays()
						.hashCode());
		result = 37
				* result
				+ (getInoOfFridays() == null ? 0 : this.getInoOfFridays()
						.hashCode());
		result = 37
				* result
				+ (getInoOfHolidays() == null ? 0 : this.getInoOfHolidays()
						.hashCode());
		result = 37 * result
				+ (getIleaveDay() == null ? 0 : this.getIleaveDay().hashCode());
		result = 37 * result
				+ (getItourDay() == null ? 0 : this.getItourDay().hashCode());
		result = 37 * result
				+ (getIoffDay() == null ? 0 : this.getIoffDay().hashCode());
		result = 37
				* result
				+ (getIabsentDay() == null ? 0 : this.getIabsentDay()
						.hashCode());
		result = 37
				* result
				+ (getInoOfWorkingDays() == null ? 0 : this
						.getInoOfWorkingDays().hashCode());
		result = 37
				* result
				+ (getIpresentDays() == null ? 0 : this.getIpresentDays()
						.hashCode());
		result = 37 * result
				+ (getMbasic() == null ? 0 : this.getMbasic().hashCode());
		result = 37
				* result
				+ (getMhouseRent() == null ? 0 : this.getMhouseRent()
						.hashCode());
		result = 37
				* result
				+ (getMmedicalAllowance() == null ? 0 : this
						.getMmedicalAllowance().hashCode());
		result = 37
				* result
				+ (getMconveyance() == null ? 0 : this.getMconveyance()
						.hashCode());
		result = 37 * result
				+ (getMspecial() == null ? 0 : this.getMspecial().hashCode());
		result = 37
				* result
				+ (getMotherAllowance() == null ? 0 : this.getMotherAllowance()
						.hashCode());
		result = 37
				* result
				+ (getMprovidentFund() == null ? 0 : this.getMprovidentFund()
						.hashCode());
		result = 37 * result
				+ (getMkfund() == null ? 0 : this.getMkfund().hashCode());
		result = 37 * result
				+ (getVotHour() == null ? 0 : this.getVotHour().hashCode());
		result = 37 * result
				+ (getMotAmount() == null ? 0 : this.getMotAmount().hashCode());
		result = 37
				* result
				+ (getMfestivalBonusAmt() == null ? 0 : this
						.getMfestivalBonusAmt().hashCode());
		result = 37
				* result
				+ (getMbonusPercentOnBasic() == null ? 0 : this
						.getMbonusPercentOnBasic().hashCode());
		result = 37
				* result
				+ (getMbonusPercentOnGross() == null ? 0 : this
						.getMbonusPercentOnGross().hashCode());
		result = 37
				* result
				+ (getMabsentAmount() == null ? 0 : this.getMabsentAmount()
						.hashCode());
		result = 37
				* result
				+ (getMadvanceSalary() == null ? 0 : this.getMadvanceSalary()
						.hashCode());
		result = 37
				* result
				+ (getVloanTranId() == null ? 0 : this.getVloanTranId()
						.hashCode());
		result = 37 * result
				+ (getVloanNo() == null ? 0 : this.getVloanNo().hashCode());
		result = 37
				* result
				+ (getMloanAmount() == null ? 0 : this.getMloanAmount()
						.hashCode());
		result = 37
				* result
				+ (getMloanDeduction() == null ? 0 : this.getMloanDeduction()
						.hashCode());
		result = 37
				* result
				+ (getMrevenueStamp() == null ? 0 : this.getMrevenueStamp()
						.hashCode());
		result = 37
				* result
				+ (getMbonusRevenueStamp() == null ? 0 : this
						.getMbonusRevenueStamp().hashCode());
		result = 37 * result
				+ (getVbankId() == null ? 0 : this.getVbankId().hashCode());
		result = 37
				* result
				+ (getVbankBranchId() == null ? 0 : this.getVbankBranchId()
						.hashCode());
		result = 37
				* result
				+ (getVaccountNo() == null ? 0 : this.getVaccountNo()
						.hashCode());
		result = 37 * result
				+ (getVuserId() == null ? 0 : this.getVuserId().hashCode());
		result = 37 * result
				+ (getVuserIp() == null ? 0 : this.getVuserIp().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		result = 37 * result
				+ (getOtrate() == null ? 0 : this.getOtrate().hashCode());
		return result;
	}

}
