package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbOtEntry generated by hbm2java
 */
public class TbOtEntry implements java.io.Serializable {

	private TbOtEntryId id;

	public TbOtEntry() {
	}

	public TbOtEntry(TbOtEntryId id) {
		this.id = id;
	}

	public TbOtEntryId getId() {
		return this.id;
	}

	public void setId(TbOtEntryId id) {
		this.id = id;
	}

}
