package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbOtEntryId generated by hbm2java
 */
public class TbOtEntryId implements java.io.Serializable {

	private int iautoId;
	private Date dotDate;
	private String vsectionId;
	private String vemployeeId;
	private String vemployeeName;
	private String employeeCode;
	private Integer ifingerId;
	private String vproximityId;
	private String vdesignationId;
	private BigDecimal mbasic;
	private BigDecimal motRate;
	private String iotHours;
	private BigDecimal motAmount;
	private String vuserIp;
	private String vuserId;
	private Date dentryTime;

	public TbOtEntryId() {
	}

	public TbOtEntryId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TbOtEntryId(int iautoId, Date dotDate, String vsectionId,
			String vemployeeId, String vemployeeName, String employeeCode,
			Integer ifingerId, String vproximityId, String vdesignationId,
			BigDecimal mbasic, BigDecimal motRate, String iotHours,
			BigDecimal motAmount, String vuserIp, String vuserId,
			Date dentryTime) {
		this.iautoId = iautoId;
		this.dotDate = dotDate;
		this.vsectionId = vsectionId;
		this.vemployeeId = vemployeeId;
		this.vemployeeName = vemployeeName;
		this.employeeCode = employeeCode;
		this.ifingerId = ifingerId;
		this.vproximityId = vproximityId;
		this.vdesignationId = vdesignationId;
		this.mbasic = mbasic;
		this.motRate = motRate;
		this.iotHours = iotHours;
		this.motAmount = motAmount;
		this.vuserIp = vuserIp;
		this.vuserId = vuserId;
		this.dentryTime = dentryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public Date getDotDate() {
		return this.dotDate;
	}

	public void setDotDate(Date dotDate) {
		this.dotDate = dotDate;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVemployeeName() {
		return this.vemployeeName;
	}

	public void setVemployeeName(String vemployeeName) {
		this.vemployeeName = vemployeeName;
	}

	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public Integer getIfingerId() {
		return this.ifingerId;
	}

	public void setIfingerId(Integer ifingerId) {
		this.ifingerId = ifingerId;
	}

	public String getVproximityId() {
		return this.vproximityId;
	}

	public void setVproximityId(String vproximityId) {
		this.vproximityId = vproximityId;
	}

	public String getVdesignationId() {
		return this.vdesignationId;
	}

	public void setVdesignationId(String vdesignationId) {
		this.vdesignationId = vdesignationId;
	}

	public BigDecimal getMbasic() {
		return this.mbasic;
	}

	public void setMbasic(BigDecimal mbasic) {
		this.mbasic = mbasic;
	}

	public BigDecimal getMotRate() {
		return this.motRate;
	}

	public void setMotRate(BigDecimal motRate) {
		this.motRate = motRate;
	}

	public String getIotHours() {
		return this.iotHours;
	}

	public void setIotHours(String iotHours) {
		this.iotHours = iotHours;
	}

	public BigDecimal getMotAmount() {
		return this.motAmount;
	}

	public void setMotAmount(BigDecimal motAmount) {
		this.motAmount = motAmount;
	}

	public String getVuserIp() {
		return this.vuserIp;
	}

	public void setVuserIp(String vuserIp) {
		this.vuserIp = vuserIp;
	}

	public String getVuserId() {
		return this.vuserId;
	}

	public void setVuserId(String vuserId) {
		this.vuserId = vuserId;
	}

	public Date getDentryTime() {
		return this.dentryTime;
	}

	public void setDentryTime(Date dentryTime) {
		this.dentryTime = dentryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbOtEntryId))
			return false;
		TbOtEntryId castOther = (TbOtEntryId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getDotDate() == castOther.getDotDate()) || (this
						.getDotDate() != null && castOther.getDotDate() != null && this
						.getDotDate().equals(castOther.getDotDate())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVemployeeName() == castOther.getVemployeeName()) || (this
						.getVemployeeName() != null
						&& castOther.getVemployeeName() != null && this
						.getVemployeeName()
						.equals(castOther.getVemployeeName())))
				&& ((this.getEmployeeCode() == castOther.getEmployeeCode()) || (this
						.getEmployeeCode() != null
						&& castOther.getEmployeeCode() != null && this
						.getEmployeeCode().equals(castOther.getEmployeeCode())))
				&& ((this.getIfingerId() == castOther.getIfingerId()) || (this
						.getIfingerId() != null
						&& castOther.getIfingerId() != null && this
						.getIfingerId().equals(castOther.getIfingerId())))
				&& ((this.getVproximityId() == castOther.getVproximityId()) || (this
						.getVproximityId() != null
						&& castOther.getVproximityId() != null && this
						.getVproximityId().equals(castOther.getVproximityId())))
				&& ((this.getVdesignationId() == castOther.getVdesignationId()) || (this
						.getVdesignationId() != null
						&& castOther.getVdesignationId() != null && this
						.getVdesignationId().equals(
								castOther.getVdesignationId())))
				&& ((this.getMbasic() == castOther.getMbasic()) || (this
						.getMbasic() != null && castOther.getMbasic() != null && this
						.getMbasic().equals(castOther.getMbasic())))
				&& ((this.getMotRate() == castOther.getMotRate()) || (this
						.getMotRate() != null && castOther.getMotRate() != null && this
						.getMotRate().equals(castOther.getMotRate())))
				&& ((this.getIotHours() == castOther.getIotHours()) || (this
						.getIotHours() != null
						&& castOther.getIotHours() != null && this
						.getIotHours().equals(castOther.getIotHours())))
				&& ((this.getMotAmount() == castOther.getMotAmount()) || (this
						.getMotAmount() != null
						&& castOther.getMotAmount() != null && this
						.getMotAmount().equals(castOther.getMotAmount())))
				&& ((this.getVuserIp() == castOther.getVuserIp()) || (this
						.getVuserIp() != null && castOther.getVuserIp() != null && this
						.getVuserIp().equals(castOther.getVuserIp())))
				&& ((this.getVuserId() == castOther.getVuserId()) || (this
						.getVuserId() != null && castOther.getVuserId() != null && this
						.getVuserId().equals(castOther.getVuserId())))
				&& ((this.getDentryTime() == castOther.getDentryTime()) || (this
						.getDentryTime() != null
						&& castOther.getDentryTime() != null && this
						.getDentryTime().equals(castOther.getDentryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result
				+ (getDotDate() == null ? 0 : this.getDotDate().hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37
				* result
				+ (getVemployeeName() == null ? 0 : this.getVemployeeName()
						.hashCode());
		result = 37
				* result
				+ (getEmployeeCode() == null ? 0 : this.getEmployeeCode()
						.hashCode());
		result = 37 * result
				+ (getIfingerId() == null ? 0 : this.getIfingerId().hashCode());
		result = 37
				* result
				+ (getVproximityId() == null ? 0 : this.getVproximityId()
						.hashCode());
		result = 37
				* result
				+ (getVdesignationId() == null ? 0 : this.getVdesignationId()
						.hashCode());
		result = 37 * result
				+ (getMbasic() == null ? 0 : this.getMbasic().hashCode());
		result = 37 * result
				+ (getMotRate() == null ? 0 : this.getMotRate().hashCode());
		result = 37 * result
				+ (getIotHours() == null ? 0 : this.getIotHours().hashCode());
		result = 37 * result
				+ (getMotAmount() == null ? 0 : this.getMotAmount().hashCode());
		result = 37 * result
				+ (getVuserIp() == null ? 0 : this.getVuserIp().hashCode());
		result = 37 * result
				+ (getVuserId() == null ? 0 : this.getVuserId().hashCode());
		result = 37
				* result
				+ (getDentryTime() == null ? 0 : this.getDentryTime()
						.hashCode());
		return result;
	}

}
