package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbSectionInfoId generated by hbm2java
 */
public class TbSectionInfoId implements java.io.Serializable {

	private int autoId;
	private String sectionName;
	private String address;
	private String userName;
	private String userIp;
	private Date entryDate;

	public TbSectionInfoId() {
	}

	public TbSectionInfoId(int autoId) {
		this.autoId = autoId;
	}

	public TbSectionInfoId(int autoId, String sectionName, String address,
			String userName, String userIp, Date entryDate) {
		this.autoId = autoId;
		this.sectionName = sectionName;
		this.address = address;
		this.userName = userName;
		this.userIp = userIp;
		this.entryDate = entryDate;
	}

	public int getAutoId() {
		return this.autoId;
	}

	public void setAutoId(int autoId) {
		this.autoId = autoId;
	}

	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbSectionInfoId))
			return false;
		TbSectionInfoId castOther = (TbSectionInfoId) other;

		return (this.getAutoId() == castOther.getAutoId())
				&& ((this.getSectionName() == castOther.getSectionName()) || (this
						.getSectionName() != null
						&& castOther.getSectionName() != null && this
						.getSectionName().equals(castOther.getSectionName())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null && castOther.getAddress() != null && this
						.getAddress().equals(castOther.getAddress())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this
						.getEntryDate() != null
						&& castOther.getEntryDate() != null && this
						.getEntryDate().equals(castOther.getEntryDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAutoId();
		result = 37
				* result
				+ (getSectionName() == null ? 0 : this.getSectionName()
						.hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		return result;
	}

}
