package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbSectionInfo generated by hbm2java
 */
public class TbSectionInfo implements java.io.Serializable {

	private TbSectionInfoId id;

	public TbSectionInfo() {
	}

	public TbSectionInfo(TbSectionInfoId id) {
		this.id = id;
	}

	public TbSectionInfoId getId() {
		return this.id;
	}

	public void setId(TbSectionInfoId id) {
		this.id = id;
	}

}
