package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbshiftInformation generated by hbm2java
 */
public class TbshiftInformation implements java.io.Serializable {

	private TbshiftInformationId id;

	public TbshiftInformation() {
	}

	public TbshiftInformation(TbshiftInformationId id) {
		this.id = id;
	}

	public TbshiftInformationId getId() {
		return this.id;
	}

	public void setId(TbshiftInformationId id) {
		this.id = id;
	}

}
