package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbshiftInformationId generated by hbm2java
 */
public class TbshiftInformationId implements java.io.Serializable {

	private int iautoId;
	private int vshiftId;
	private String vshiftName;
	private String vdescription;
	private Date tshiftStart;
	private Date tshiftEnd;
	private Date tlateIn;
	private Date tearlyOut;
	private Date toverTimeStart;
	private Date toverTimeEnd;
	private String userId;
	private String userIp;
	private Date entryTime;

	public TbshiftInformationId() {
	}

	public TbshiftInformationId(int iautoId, int vshiftId, String vshiftName,
			String vdescription, Date tshiftStart, Date tshiftEnd,
			Date tlateIn, Date tearlyOut, Date toverTimeStart,
			Date toverTimeEnd, String userId, String userIp) {
		this.iautoId = iautoId;
		this.vshiftId = vshiftId;
		this.vshiftName = vshiftName;
		this.vdescription = vdescription;
		this.tshiftStart = tshiftStart;
		this.tshiftEnd = tshiftEnd;
		this.tlateIn = tlateIn;
		this.tearlyOut = tearlyOut;
		this.toverTimeStart = toverTimeStart;
		this.toverTimeEnd = toverTimeEnd;
		this.userId = userId;
		this.userIp = userIp;
	}

	public TbshiftInformationId(int iautoId, int vshiftId, String vshiftName,
			String vdescription, Date tshiftStart, Date tshiftEnd,
			Date tlateIn, Date tearlyOut, Date toverTimeStart,
			Date toverTimeEnd, String userId, String userIp, Date entryTime) {
		this.iautoId = iautoId;
		this.vshiftId = vshiftId;
		this.vshiftName = vshiftName;
		this.vdescription = vdescription;
		this.tshiftStart = tshiftStart;
		this.tshiftEnd = tshiftEnd;
		this.tlateIn = tlateIn;
		this.tearlyOut = tearlyOut;
		this.toverTimeStart = toverTimeStart;
		this.toverTimeEnd = toverTimeEnd;
		this.userId = userId;
		this.userIp = userIp;
		this.entryTime = entryTime;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public int getVshiftId() {
		return this.vshiftId;
	}

	public void setVshiftId(int vshiftId) {
		this.vshiftId = vshiftId;
	}

	public String getVshiftName() {
		return this.vshiftName;
	}

	public void setVshiftName(String vshiftName) {
		this.vshiftName = vshiftName;
	}

	public String getVdescription() {
		return this.vdescription;
	}

	public void setVdescription(String vdescription) {
		this.vdescription = vdescription;
	}

	public Date getTshiftStart() {
		return this.tshiftStart;
	}

	public void setTshiftStart(Date tshiftStart) {
		this.tshiftStart = tshiftStart;
	}

	public Date getTshiftEnd() {
		return this.tshiftEnd;
	}

	public void setTshiftEnd(Date tshiftEnd) {
		this.tshiftEnd = tshiftEnd;
	}

	public Date getTlateIn() {
		return this.tlateIn;
	}

	public void setTlateIn(Date tlateIn) {
		this.tlateIn = tlateIn;
	}

	public Date getTearlyOut() {
		return this.tearlyOut;
	}

	public void setTearlyOut(Date tearlyOut) {
		this.tearlyOut = tearlyOut;
	}

	public Date getToverTimeStart() {
		return this.toverTimeStart;
	}

	public void setToverTimeStart(Date toverTimeStart) {
		this.toverTimeStart = toverTimeStart;
	}

	public Date getToverTimeEnd() {
		return this.toverTimeEnd;
	}

	public void setToverTimeEnd(Date toverTimeEnd) {
		this.toverTimeEnd = toverTimeEnd;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbshiftInformationId))
			return false;
		TbshiftInformationId castOther = (TbshiftInformationId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& (this.getVshiftId() == castOther.getVshiftId())
				&& ((this.getVshiftName() == castOther.getVshiftName()) || (this
						.getVshiftName() != null
						&& castOther.getVshiftName() != null && this
						.getVshiftName().equals(castOther.getVshiftName())))
				&& ((this.getVdescription() == castOther.getVdescription()) || (this
						.getVdescription() != null
						&& castOther.getVdescription() != null && this
						.getVdescription().equals(castOther.getVdescription())))
				&& ((this.getTshiftStart() == castOther.getTshiftStart()) || (this
						.getTshiftStart() != null
						&& castOther.getTshiftStart() != null && this
						.getTshiftStart().equals(castOther.getTshiftStart())))
				&& ((this.getTshiftEnd() == castOther.getTshiftEnd()) || (this
						.getTshiftEnd() != null
						&& castOther.getTshiftEnd() != null && this
						.getTshiftEnd().equals(castOther.getTshiftEnd())))
				&& ((this.getTlateIn() == castOther.getTlateIn()) || (this
						.getTlateIn() != null && castOther.getTlateIn() != null && this
						.getTlateIn().equals(castOther.getTlateIn())))
				&& ((this.getTearlyOut() == castOther.getTearlyOut()) || (this
						.getTearlyOut() != null
						&& castOther.getTearlyOut() != null && this
						.getTearlyOut().equals(castOther.getTearlyOut())))
				&& ((this.getToverTimeStart() == castOther.getToverTimeStart()) || (this
						.getToverTimeStart() != null
						&& castOther.getToverTimeStart() != null && this
						.getToverTimeStart().equals(
								castOther.getToverTimeStart())))
				&& ((this.getToverTimeEnd() == castOther.getToverTimeEnd()) || (this
						.getToverTimeEnd() != null
						&& castOther.getToverTimeEnd() != null && this
						.getToverTimeEnd().equals(castOther.getToverTimeEnd())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this
						.getEntryTime() != null
						&& castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37 * result + this.getVshiftId();
		result = 37
				* result
				+ (getVshiftName() == null ? 0 : this.getVshiftName()
						.hashCode());
		result = 37
				* result
				+ (getVdescription() == null ? 0 : this.getVdescription()
						.hashCode());
		result = 37
				* result
				+ (getTshiftStart() == null ? 0 : this.getTshiftStart()
						.hashCode());
		result = 37 * result
				+ (getTshiftEnd() == null ? 0 : this.getTshiftEnd().hashCode());
		result = 37 * result
				+ (getTlateIn() == null ? 0 : this.getTlateIn().hashCode());
		result = 37 * result
				+ (getTearlyOut() == null ? 0 : this.getTearlyOut().hashCode());
		result = 37
				* result
				+ (getToverTimeStart() == null ? 0 : this.getToverTimeStart()
						.hashCode());
		result = 37
				* result
				+ (getToverTimeEnd() == null ? 0 : this.getToverTimeEnd()
						.hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result
				+ (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
