package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbSupplierInfo generated by hbm2java
 */
public class TbSupplierInfo implements java.io.Serializable {

	private TbSupplierInfoId id;

	public TbSupplierInfo() {
	}

	public TbSupplierInfo(TbSupplierInfoId id) {
		this.id = id;
	}

	public TbSupplierInfoId getId() {
		return this.id;
	}

	public void setId(TbSupplierInfoId id) {
		this.id = id;
	}

}
