package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbUdLoginDetailsId generated by hbm2java
 */
public class TbUdLoginDetailsId implements java.io.Serializable {

	private String userId;
	private String moduleId;
	private String moduleName;
	private String uid;
	private String uip;
	private String entrytime;
	private String flag;

	public TbUdLoginDetailsId() {
	}

	public TbUdLoginDetailsId(String userId, String moduleId,
			String moduleName, String uid, String uip, String entrytime,
			String flag) {
		this.userId = userId;
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.uid = uid;
		this.uip = uip;
		this.entrytime = entrytime;
		this.flag = flag;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getUip() {
		return this.uip;
	}

	public void setUip(String uip) {
		this.uip = uip;
	}

	public String getEntrytime() {
		return this.entrytime;
	}

	public void setEntrytime(String entrytime) {
		this.entrytime = entrytime;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbUdLoginDetailsId))
			return false;
		TbUdLoginDetailsId castOther = (TbUdLoginDetailsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getModuleId() == castOther.getModuleId()) || (this
						.getModuleId() != null
						&& castOther.getModuleId() != null && this
						.getModuleId().equals(castOther.getModuleId())))
				&& ((this.getModuleName() == castOther.getModuleName()) || (this
						.getModuleName() != null
						&& castOther.getModuleName() != null && this
						.getModuleName().equals(castOther.getModuleName())))
				&& ((this.getUid() == castOther.getUid()) || (this.getUid() != null
						&& castOther.getUid() != null && this.getUid().equals(
						castOther.getUid())))
				&& ((this.getUip() == castOther.getUip()) || (this.getUip() != null
						&& castOther.getUip() != null && this.getUip().equals(
						castOther.getUip())))
				&& ((this.getEntrytime() == castOther.getEntrytime()) || (this
						.getEntrytime() != null
						&& castOther.getEntrytime() != null && this
						.getEntrytime().equals(castOther.getEntrytime())))
				&& ((this.getFlag() == castOther.getFlag()) || (this.getFlag() != null
						&& castOther.getFlag() != null && this.getFlag()
						.equals(castOther.getFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getModuleId() == null ? 0 : this.getModuleId().hashCode());
		result = 37
				* result
				+ (getModuleName() == null ? 0 : this.getModuleName()
						.hashCode());
		result = 37 * result
				+ (getUid() == null ? 0 : this.getUid().hashCode());
		result = 37 * result
				+ (getUip() == null ? 0 : this.getUip().hashCode());
		result = 37 * result
				+ (getEntrytime() == null ? 0 : this.getEntrytime().hashCode());
		result = 37 * result
				+ (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}

}
