package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbUdemployeeAttendance generated by hbm2java
 */
public class TbUdemployeeAttendance implements java.io.Serializable {

	private TbUdemployeeAttendanceId id;

	public TbUdemployeeAttendance() {
	}

	public TbUdemployeeAttendance(TbUdemployeeAttendanceId id) {
		this.id = id;
	}

	public TbUdemployeeAttendanceId getId() {
		return this.id;
	}

	public void setId(TbUdemployeeAttendanceId id) {
		this.id = id;
	}

}
