package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbUdLoginDetails generated by hbm2java
 */
public class TbUdLoginDetails implements java.io.Serializable {

	private TbUdLoginDetailsId id;

	public TbUdLoginDetails() {
	}

	public TbUdLoginDetails(TbUdLoginDetailsId id) {
		this.id = id;
	}

	public TbUdLoginDetailsId getId() {
		return this.id;
	}

	public void setId(TbUdLoginDetailsId id) {
		this.id = id;
	}

}
