package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbUdLogin generated by hbm2java
 */
public class TbUdLogin implements java.io.Serializable {

	private TbUdLoginId id;

	public TbUdLogin() {
	}

	public TbUdLogin(TbUdLoginId id) {
		this.id = id;
	}

	public TbUdLoginId getId() {
		return this.id;
	}

	public void setId(TbUdLoginId id) {
		this.id = id;
	}

}
