package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbUdAuthentication generated by hbm2java
 */
public class TbUdAuthentication implements java.io.Serializable {

	private TbUdAuthenticationId id;

	public TbUdAuthentication() {
	}

	public TbUdAuthentication(TbUdAuthenticationId id) {
		this.id = id;
	}

	public TbUdAuthenticationId getId() {
		return this.id;
	}

	public void setId(TbUdAuthenticationId id) {
		this.id = id;
	}

}
