package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbUdLoginId generated by hbm2java
 */
public class TbUdLoginId implements java.io.Serializable {

	private int userId;
	private String name;
	private String pass;
	private Date createTime;
	private Integer createBy;
	private Integer isAdmin;
	private Integer isInsertable;
	private Integer isUpdateable;
	private Integer isDeleteable;
	private Integer isActive;
	private Integer isSuperAdmin;
	private String employeeId;
	private String uid;
	private String uip;
	private Date entrytime;
	private String flag;

	public TbUdLoginId() {
	}

	public TbUdLoginId(int userId, String name) {
		this.userId = userId;
		this.name = name;
	}

	public TbUdLoginId(int userId, String name, String pass, Date createTime,
			Integer createBy, Integer isAdmin, Integer isInsertable,
			Integer isUpdateable, Integer isDeleteable, Integer isActive,
			Integer isSuperAdmin, String employeeId, String uid, String uip,
			Date entrytime, String flag) {
		this.userId = userId;
		this.name = name;
		this.pass = pass;
		this.createTime = createTime;
		this.createBy = createBy;
		this.isAdmin = isAdmin;
		this.isInsertable = isInsertable;
		this.isUpdateable = isUpdateable;
		this.isDeleteable = isDeleteable;
		this.isActive = isActive;
		this.isSuperAdmin = isSuperAdmin;
		this.employeeId = employeeId;
		this.uid = uid;
		this.uip = uip;
		this.entrytime = entrytime;
		this.flag = flag;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public Integer getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}

	public Integer getIsInsertable() {
		return this.isInsertable;
	}

	public void setIsInsertable(Integer isInsertable) {
		this.isInsertable = isInsertable;
	}

	public Integer getIsUpdateable() {
		return this.isUpdateable;
	}

	public void setIsUpdateable(Integer isUpdateable) {
		this.isUpdateable = isUpdateable;
	}

	public Integer getIsDeleteable() {
		return this.isDeleteable;
	}

	public void setIsDeleteable(Integer isDeleteable) {
		this.isDeleteable = isDeleteable;
	}

	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	public Integer getIsSuperAdmin() {
		return this.isSuperAdmin;
	}

	public void setIsSuperAdmin(Integer isSuperAdmin) {
		this.isSuperAdmin = isSuperAdmin;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getUip() {
		return this.uip;
	}

	public void setUip(String uip) {
		this.uip = uip;
	}

	public Date getEntrytime() {
		return this.entrytime;
	}

	public void setEntrytime(Date entrytime) {
		this.entrytime = entrytime;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbUdLoginId))
			return false;
		TbUdLoginId castOther = (TbUdLoginId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getPass() == castOther.getPass()) || (this.getPass() != null
						&& castOther.getPass() != null && this.getPass()
						.equals(castOther.getPass())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this
						.getCreateTime() != null
						&& castOther.getCreateTime() != null && this
						.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& ((this.getIsAdmin() == castOther.getIsAdmin()) || (this
						.getIsAdmin() != null && castOther.getIsAdmin() != null && this
						.getIsAdmin().equals(castOther.getIsAdmin())))
				&& ((this.getIsInsertable() == castOther.getIsInsertable()) || (this
						.getIsInsertable() != null
						&& castOther.getIsInsertable() != null && this
						.getIsInsertable().equals(castOther.getIsInsertable())))
				&& ((this.getIsUpdateable() == castOther.getIsUpdateable()) || (this
						.getIsUpdateable() != null
						&& castOther.getIsUpdateable() != null && this
						.getIsUpdateable().equals(castOther.getIsUpdateable())))
				&& ((this.getIsDeleteable() == castOther.getIsDeleteable()) || (this
						.getIsDeleteable() != null
						&& castOther.getIsDeleteable() != null && this
						.getIsDeleteable().equals(castOther.getIsDeleteable())))
				&& ((this.getIsActive() == castOther.getIsActive()) || (this
						.getIsActive() != null
						&& castOther.getIsActive() != null && this
						.getIsActive().equals(castOther.getIsActive())))
				&& ((this.getIsSuperAdmin() == castOther.getIsSuperAdmin()) || (this
						.getIsSuperAdmin() != null
						&& castOther.getIsSuperAdmin() != null && this
						.getIsSuperAdmin().equals(castOther.getIsSuperAdmin())))
				&& ((this.getEmployeeId() == castOther.getEmployeeId()) || (this
						.getEmployeeId() != null
						&& castOther.getEmployeeId() != null && this
						.getEmployeeId().equals(castOther.getEmployeeId())))
				&& ((this.getUid() == castOther.getUid()) || (this.getUid() != null
						&& castOther.getUid() != null && this.getUid().equals(
						castOther.getUid())))
				&& ((this.getUip() == castOther.getUip()) || (this.getUip() != null
						&& castOther.getUip() != null && this.getUip().equals(
						castOther.getUip())))
				&& ((this.getEntrytime() == castOther.getEntrytime()) || (this
						.getEntrytime() != null
						&& castOther.getEntrytime() != null && this
						.getEntrytime().equals(castOther.getEntrytime())))
				&& ((this.getFlag() == castOther.getFlag()) || (this.getFlag() != null
						&& castOther.getFlag() != null && this.getFlag()
						.equals(castOther.getFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getPass() == null ? 0 : this.getPass().hashCode());
		result = 37
				* result
				+ (getCreateTime() == null ? 0 : this.getCreateTime()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37 * result
				+ (getIsAdmin() == null ? 0 : this.getIsAdmin().hashCode());
		result = 37
				* result
				+ (getIsInsertable() == null ? 0 : this.getIsInsertable()
						.hashCode());
		result = 37
				* result
				+ (getIsUpdateable() == null ? 0 : this.getIsUpdateable()
						.hashCode());
		result = 37
				* result
				+ (getIsDeleteable() == null ? 0 : this.getIsDeleteable()
						.hashCode());
		result = 37 * result
				+ (getIsActive() == null ? 0 : this.getIsActive().hashCode());
		result = 37
				* result
				+ (getIsSuperAdmin() == null ? 0 : this.getIsSuperAdmin()
						.hashCode());
		result = 37
				* result
				+ (getEmployeeId() == null ? 0 : this.getEmployeeId()
						.hashCode());
		result = 37 * result
				+ (getUid() == null ? 0 : this.getUid().hashCode());
		result = 37 * result
				+ (getUip() == null ? 0 : this.getUip().hashCode());
		result = 37 * result
				+ (getEntrytime() == null ? 0 : this.getEntrytime().hashCode());
		result = 37 * result
				+ (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}

}
