package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbUdAuthenticationId generated by hbm2java
 */
public class TbUdAuthenticationId implements java.io.Serializable {

	private Integer userId;
	private String menuId;
	private Date insertTime;
	private Integer createBy;
	private int sl;
	private String menuCaption;
	private String uid;
	private String uip;
	private Date entrytime;
	private String flag;

	public TbUdAuthenticationId() {
	}

	public TbUdAuthenticationId(int sl) {
		this.sl = sl;
	}

	public TbUdAuthenticationId(Integer userId, String menuId, Date insertTime,
			Integer createBy, int sl, String menuCaption, String uid,
			String uip, Date entrytime, String flag) {
		this.userId = userId;
		this.menuId = menuId;
		this.insertTime = insertTime;
		this.createBy = createBy;
		this.sl = sl;
		this.menuCaption = menuCaption;
		this.uid = uid;
		this.uip = uip;
		this.entrytime = entrytime;
		this.flag = flag;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public int getSl() {
		return this.sl;
	}

	public void setSl(int sl) {
		this.sl = sl;
	}

	public String getMenuCaption() {
		return this.menuCaption;
	}

	public void setMenuCaption(String menuCaption) {
		this.menuCaption = menuCaption;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getUip() {
		return this.uip;
	}

	public void setUip(String uip) {
		this.uip = uip;
	}

	public Date getEntrytime() {
		return this.entrytime;
	}

	public void setEntrytime(Date entrytime) {
		this.entrytime = entrytime;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbUdAuthenticationId))
			return false;
		TbUdAuthenticationId castOther = (TbUdAuthenticationId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getMenuId() == castOther.getMenuId()) || (this
						.getMenuId() != null && castOther.getMenuId() != null && this
						.getMenuId().equals(castOther.getMenuId())))
				&& ((this.getInsertTime() == castOther.getInsertTime()) || (this
						.getInsertTime() != null
						&& castOther.getInsertTime() != null && this
						.getInsertTime().equals(castOther.getInsertTime())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& (this.getSl() == castOther.getSl())
				&& ((this.getMenuCaption() == castOther.getMenuCaption()) || (this
						.getMenuCaption() != null
						&& castOther.getMenuCaption() != null && this
						.getMenuCaption().equals(castOther.getMenuCaption())))
				&& ((this.getUid() == castOther.getUid()) || (this.getUid() != null
						&& castOther.getUid() != null && this.getUid().equals(
						castOther.getUid())))
				&& ((this.getUip() == castOther.getUip()) || (this.getUip() != null
						&& castOther.getUip() != null && this.getUip().equals(
						castOther.getUip())))
				&& ((this.getEntrytime() == castOther.getEntrytime()) || (this
						.getEntrytime() != null
						&& castOther.getEntrytime() != null && this
						.getEntrytime().equals(castOther.getEntrytime())))
				&& ((this.getFlag() == castOther.getFlag()) || (this.getFlag() != null
						&& castOther.getFlag() != null && this.getFlag()
						.equals(castOther.getFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		result = 37
				* result
				+ (getInsertTime() == null ? 0 : this.getInsertTime()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37 * result + this.getSl();
		result = 37
				* result
				+ (getMenuCaption() == null ? 0 : this.getMenuCaption()
						.hashCode());
		result = 37 * result
				+ (getUid() == null ? 0 : this.getUid().hashCode());
		result = 37 * result
				+ (getUip() == null ? 0 : this.getUip().hashCode());
		result = 37 * result
				+ (getEntrytime() == null ? 0 : this.getEntrytime().hashCode());
		result = 37 * result
				+ (getFlag() == null ? 0 : this.getFlag().hashCode());
		return result;
	}

}
