package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TemEmployeeInfo generated by hbm2java
 */
public class TemEmployeeInfo implements java.io.Serializable {

	private TemEmployeeInfoId id;

	public TemEmployeeInfo() {
	}

	public TemEmployeeInfo(TemEmployeeInfoId id) {
		this.id = id;
	}

	public TemEmployeeInfoId getId() {
		return this.id;
	}

	public void setId(TemEmployeeInfoId id) {
		this.id = id;
	}

}
