package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TemEmployeeInfoId generated by hbm2java
 */
public class TemEmployeeInfoId implements java.io.Serializable {

	private String employeeCode;
	private BigDecimal basic;
	private BigDecimal hr;
	private BigDecimal allow;
	private Date joiningDate;

	public TemEmployeeInfoId() {
	}

	public TemEmployeeInfoId(String employeeCode, BigDecimal basic,
			BigDecimal hr, BigDecimal allow, Date joiningDate) {
		this.employeeCode = employeeCode;
		this.basic = basic;
		this.hr = hr;
		this.allow = allow;
		this.joiningDate = joiningDate;
	}

	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public BigDecimal getBasic() {
		return this.basic;
	}

	public void setBasic(BigDecimal basic) {
		this.basic = basic;
	}

	public BigDecimal getHr() {
		return this.hr;
	}

	public void setHr(BigDecimal hr) {
		this.hr = hr;
	}

	public BigDecimal getAllow() {
		return this.allow;
	}

	public void setAllow(BigDecimal allow) {
		this.allow = allow;
	}

	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TemEmployeeInfoId))
			return false;
		TemEmployeeInfoId castOther = (TemEmployeeInfoId) other;

		return ((this.getEmployeeCode() == castOther.getEmployeeCode()) || (this
				.getEmployeeCode() != null
				&& castOther.getEmployeeCode() != null && this
				.getEmployeeCode().equals(castOther.getEmployeeCode())))
				&& ((this.getBasic() == castOther.getBasic()) || (this
						.getBasic() != null && castOther.getBasic() != null && this
						.getBasic().equals(castOther.getBasic())))
				&& ((this.getHr() == castOther.getHr()) || (this.getHr() != null
						&& castOther.getHr() != null && this.getHr().equals(
						castOther.getHr())))
				&& ((this.getAllow() == castOther.getAllow()) || (this
						.getAllow() != null && castOther.getAllow() != null && this
						.getAllow().equals(castOther.getAllow())))
				&& ((this.getJoiningDate() == castOther.getJoiningDate()) || (this
						.getJoiningDate() != null
						&& castOther.getJoiningDate() != null && this
						.getJoiningDate().equals(castOther.getJoiningDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEmployeeCode() == null ? 0 : this.getEmployeeCode()
						.hashCode());
		result = 37 * result
				+ (getBasic() == null ? 0 : this.getBasic().hashCode());
		result = 37 * result + (getHr() == null ? 0 : this.getHr().hashCode());
		result = 37 * result
				+ (getAllow() == null ? 0 : this.getAllow().hashCode());
		result = 37
				* result
				+ (getJoiningDate() == null ? 0 : this.getJoiningDate()
						.hashCode());
		return result;
	}

}
