package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TempShift generated by hbm2java
 */
public class TempShift implements java.io.Serializable {

	private TempShiftId id;

	public TempShift() {
	}

	public TempShift(TempShiftId id) {
		this.id = id;
	}

	public TempShiftId getId() {
		return this.id;
	}

	public void setId(TempShiftId id) {
		this.id = id;
	}

}
