package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TempShiftId generated by hbm2java
 */
public class TempShiftId implements java.io.Serializable {

	private int iautoId;
	private String vemployeeId;
	private String vshiftId;

	public TempShiftId() {
	}

	public TempShiftId(int iautoId) {
		this.iautoId = iautoId;
	}

	public TempShiftId(int iautoId, String vemployeeId, String vshiftId) {
		this.iautoId = iautoId;
		this.vemployeeId = vemployeeId;
		this.vshiftId = vshiftId;
	}

	public int getIautoId() {
		return this.iautoId;
	}

	public void setIautoId(int iautoId) {
		this.iautoId = iautoId;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public String getVshiftId() {
		return this.vshiftId;
	}

	public void setVshiftId(String vshiftId) {
		this.vshiftId = vshiftId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TempShiftId))
			return false;
		TempShiftId castOther = (TempShiftId) other;

		return (this.getIautoId() == castOther.getIautoId())
				&& ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
						.getVemployeeId() != null
						&& castOther.getVemployeeId() != null && this
						.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getVshiftId() == castOther.getVshiftId()) || (this
						.getVshiftId() != null
						&& castOther.getVshiftId() != null && this
						.getVshiftId().equals(castOther.getVshiftId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIautoId();
		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37 * result
				+ (getVshiftId() == null ? 0 : this.getVshiftId().hashCode());
		return result;
	}

}
