package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpAttendence generated by hbm2java
 */
public class TmpAttendence implements java.io.Serializable {

	private TmpAttendenceId id;

	public TmpAttendence() {
	}

	public TmpAttendence(TmpAttendenceId id) {
		this.id = id;
	}

	public TmpAttendenceId getId() {
		return this.id;
	}

	public void setId(TmpAttendenceId id) {
		this.id = id;
	}

}
