package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VwRptEmployeeifoId generated by hbm2java
 */
public class VwRptEmployeeifoId implements java.io.Serializable {

	private String vemployeeId;
	private Integer ifingerId;
	private String vemployeeName;
	private String vreligion;
	private String vcontact;
	private String vemail;
	private String vgender;
	private Date ddateOfBirth;
	private String vnationality;
	private Date dapplicationDate;
	private Date dinterviewDate;
	private Date djoiningDate;
	private Date dconfirmationDate;
	private String vsectionId;
	private String vfatherName;
	private String vmotherName;
	private String vpermanentAddress;
	private String vmailingAddress;
	private String vmeritalStatus;
	private String votherQualification;
	private String vcomputerSkill;
	private String vproximityId;
	private Date dmarriageDate;
	private String designationName;
	private String imageLocation;
	private String sectionName;

	public VwRptEmployeeifoId() {
	}

	public VwRptEmployeeifoId(String vemployeeId, String designationName) {
		this.vemployeeId = vemployeeId;
		this.designationName = designationName;
	}

	public VwRptEmployeeifoId(String vemployeeId, Integer ifingerId,
			String vemployeeName, String vreligion, String vcontact,
			String vemail, String vgender, Date ddateOfBirth,
			String vnationality, Date dapplicationDate, Date dinterviewDate,
			Date djoiningDate, Date dconfirmationDate, String vsectionId,
			String vfatherName, String vmotherName, String vpermanentAddress,
			String vmailingAddress, String vmeritalStatus,
			String votherQualification, String vcomputerSkill,
			String vproximityId, Date dmarriageDate, String designationName,
			String imageLocation, String sectionName) {
		this.vemployeeId = vemployeeId;
		this.ifingerId = ifingerId;
		this.vemployeeName = vemployeeName;
		this.vreligion = vreligion;
		this.vcontact = vcontact;
		this.vemail = vemail;
		this.vgender = vgender;
		this.ddateOfBirth = ddateOfBirth;
		this.vnationality = vnationality;
		this.dapplicationDate = dapplicationDate;
		this.dinterviewDate = dinterviewDate;
		this.djoiningDate = djoiningDate;
		this.dconfirmationDate = dconfirmationDate;
		this.vsectionId = vsectionId;
		this.vfatherName = vfatherName;
		this.vmotherName = vmotherName;
		this.vpermanentAddress = vpermanentAddress;
		this.vmailingAddress = vmailingAddress;
		this.vmeritalStatus = vmeritalStatus;
		this.votherQualification = votherQualification;
		this.vcomputerSkill = vcomputerSkill;
		this.vproximityId = vproximityId;
		this.dmarriageDate = dmarriageDate;
		this.designationName = designationName;
		this.imageLocation = imageLocation;
		this.sectionName = sectionName;
	}

	public String getVemployeeId() {
		return this.vemployeeId;
	}

	public void setVemployeeId(String vemployeeId) {
		this.vemployeeId = vemployeeId;
	}

	public Integer getIfingerId() {
		return this.ifingerId;
	}

	public void setIfingerId(Integer ifingerId) {
		this.ifingerId = ifingerId;
	}

	public String getVemployeeName() {
		return this.vemployeeName;
	}

	public void setVemployeeName(String vemployeeName) {
		this.vemployeeName = vemployeeName;
	}

	public String getVreligion() {
		return this.vreligion;
	}

	public void setVreligion(String vreligion) {
		this.vreligion = vreligion;
	}

	public String getVcontact() {
		return this.vcontact;
	}

	public void setVcontact(String vcontact) {
		this.vcontact = vcontact;
	}

	public String getVemail() {
		return this.vemail;
	}

	public void setVemail(String vemail) {
		this.vemail = vemail;
	}

	public String getVgender() {
		return this.vgender;
	}

	public void setVgender(String vgender) {
		this.vgender = vgender;
	}

	public Date getDdateOfBirth() {
		return this.ddateOfBirth;
	}

	public void setDdateOfBirth(Date ddateOfBirth) {
		this.ddateOfBirth = ddateOfBirth;
	}

	public String getVnationality() {
		return this.vnationality;
	}

	public void setVnationality(String vnationality) {
		this.vnationality = vnationality;
	}

	public Date getDapplicationDate() {
		return this.dapplicationDate;
	}

	public void setDapplicationDate(Date dapplicationDate) {
		this.dapplicationDate = dapplicationDate;
	}

	public Date getDinterviewDate() {
		return this.dinterviewDate;
	}

	public void setDinterviewDate(Date dinterviewDate) {
		this.dinterviewDate = dinterviewDate;
	}

	public Date getDjoiningDate() {
		return this.djoiningDate;
	}

	public void setDjoiningDate(Date djoiningDate) {
		this.djoiningDate = djoiningDate;
	}

	public Date getDconfirmationDate() {
		return this.dconfirmationDate;
	}

	public void setDconfirmationDate(Date dconfirmationDate) {
		this.dconfirmationDate = dconfirmationDate;
	}

	public String getVsectionId() {
		return this.vsectionId;
	}

	public void setVsectionId(String vsectionId) {
		this.vsectionId = vsectionId;
	}

	public String getVfatherName() {
		return this.vfatherName;
	}

	public void setVfatherName(String vfatherName) {
		this.vfatherName = vfatherName;
	}

	public String getVmotherName() {
		return this.vmotherName;
	}

	public void setVmotherName(String vmotherName) {
		this.vmotherName = vmotherName;
	}

	public String getVpermanentAddress() {
		return this.vpermanentAddress;
	}

	public void setVpermanentAddress(String vpermanentAddress) {
		this.vpermanentAddress = vpermanentAddress;
	}

	public String getVmailingAddress() {
		return this.vmailingAddress;
	}

	public void setVmailingAddress(String vmailingAddress) {
		this.vmailingAddress = vmailingAddress;
	}

	public String getVmeritalStatus() {
		return this.vmeritalStatus;
	}

	public void setVmeritalStatus(String vmeritalStatus) {
		this.vmeritalStatus = vmeritalStatus;
	}

	public String getVotherQualification() {
		return this.votherQualification;
	}

	public void setVotherQualification(String votherQualification) {
		this.votherQualification = votherQualification;
	}

	public String getVcomputerSkill() {
		return this.vcomputerSkill;
	}

	public void setVcomputerSkill(String vcomputerSkill) {
		this.vcomputerSkill = vcomputerSkill;
	}

	public String getVproximityId() {
		return this.vproximityId;
	}

	public void setVproximityId(String vproximityId) {
		this.vproximityId = vproximityId;
	}

	public Date getDmarriageDate() {
		return this.dmarriageDate;
	}

	public void setDmarriageDate(Date dmarriageDate) {
		this.dmarriageDate = dmarriageDate;
	}

	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public String getImageLocation() {
		return this.imageLocation;
	}

	public void setImageLocation(String imageLocation) {
		this.imageLocation = imageLocation;
	}

	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwRptEmployeeifoId))
			return false;
		VwRptEmployeeifoId castOther = (VwRptEmployeeifoId) other;

		return ((this.getVemployeeId() == castOther.getVemployeeId()) || (this
				.getVemployeeId() != null && castOther.getVemployeeId() != null && this
				.getVemployeeId().equals(castOther.getVemployeeId())))
				&& ((this.getIfingerId() == castOther.getIfingerId()) || (this
						.getIfingerId() != null
						&& castOther.getIfingerId() != null && this
						.getIfingerId().equals(castOther.getIfingerId())))
				&& ((this.getVemployeeName() == castOther.getVemployeeName()) || (this
						.getVemployeeName() != null
						&& castOther.getVemployeeName() != null && this
						.getVemployeeName()
						.equals(castOther.getVemployeeName())))
				&& ((this.getVreligion() == castOther.getVreligion()) || (this
						.getVreligion() != null
						&& castOther.getVreligion() != null && this
						.getVreligion().equals(castOther.getVreligion())))
				&& ((this.getVcontact() == castOther.getVcontact()) || (this
						.getVcontact() != null
						&& castOther.getVcontact() != null && this
						.getVcontact().equals(castOther.getVcontact())))
				&& ((this.getVemail() == castOther.getVemail()) || (this
						.getVemail() != null && castOther.getVemail() != null && this
						.getVemail().equals(castOther.getVemail())))
				&& ((this.getVgender() == castOther.getVgender()) || (this
						.getVgender() != null && castOther.getVgender() != null && this
						.getVgender().equals(castOther.getVgender())))
				&& ((this.getDdateOfBirth() == castOther.getDdateOfBirth()) || (this
						.getDdateOfBirth() != null
						&& castOther.getDdateOfBirth() != null && this
						.getDdateOfBirth().equals(castOther.getDdateOfBirth())))
				&& ((this.getVnationality() == castOther.getVnationality()) || (this
						.getVnationality() != null
						&& castOther.getVnationality() != null && this
						.getVnationality().equals(castOther.getVnationality())))
				&& ((this.getDapplicationDate() == castOther
						.getDapplicationDate()) || (this.getDapplicationDate() != null
						&& castOther.getDapplicationDate() != null && this
						.getDapplicationDate().equals(
								castOther.getDapplicationDate())))
				&& ((this.getDinterviewDate() == castOther.getDinterviewDate()) || (this
						.getDinterviewDate() != null
						&& castOther.getDinterviewDate() != null && this
						.getDinterviewDate().equals(
								castOther.getDinterviewDate())))
				&& ((this.getDjoiningDate() == castOther.getDjoiningDate()) || (this
						.getDjoiningDate() != null
						&& castOther.getDjoiningDate() != null && this
						.getDjoiningDate().equals(castOther.getDjoiningDate())))
				&& ((this.getDconfirmationDate() == castOther
						.getDconfirmationDate()) || (this
						.getDconfirmationDate() != null
						&& castOther.getDconfirmationDate() != null && this
						.getDconfirmationDate().equals(
								castOther.getDconfirmationDate())))
				&& ((this.getVsectionId() == castOther.getVsectionId()) || (this
						.getVsectionId() != null
						&& castOther.getVsectionId() != null && this
						.getVsectionId().equals(castOther.getVsectionId())))
				&& ((this.getVfatherName() == castOther.getVfatherName()) || (this
						.getVfatherName() != null
						&& castOther.getVfatherName() != null && this
						.getVfatherName().equals(castOther.getVfatherName())))
				&& ((this.getVmotherName() == castOther.getVmotherName()) || (this
						.getVmotherName() != null
						&& castOther.getVmotherName() != null && this
						.getVmotherName().equals(castOther.getVmotherName())))
				&& ((this.getVpermanentAddress() == castOther
						.getVpermanentAddress()) || (this
						.getVpermanentAddress() != null
						&& castOther.getVpermanentAddress() != null && this
						.getVpermanentAddress().equals(
								castOther.getVpermanentAddress())))
				&& ((this.getVmailingAddress() == castOther
						.getVmailingAddress()) || (this.getVmailingAddress() != null
						&& castOther.getVmailingAddress() != null && this
						.getVmailingAddress().equals(
								castOther.getVmailingAddress())))
				&& ((this.getVmeritalStatus() == castOther.getVmeritalStatus()) || (this
						.getVmeritalStatus() != null
						&& castOther.getVmeritalStatus() != null && this
						.getVmeritalStatus().equals(
								castOther.getVmeritalStatus())))
				&& ((this.getVotherQualification() == castOther
						.getVotherQualification()) || (this
						.getVotherQualification() != null
						&& castOther.getVotherQualification() != null && this
						.getVotherQualification().equals(
								castOther.getVotherQualification())))
				&& ((this.getVcomputerSkill() == castOther.getVcomputerSkill()) || (this
						.getVcomputerSkill() != null
						&& castOther.getVcomputerSkill() != null && this
						.getVcomputerSkill().equals(
								castOther.getVcomputerSkill())))
				&& ((this.getVproximityId() == castOther.getVproximityId()) || (this
						.getVproximityId() != null
						&& castOther.getVproximityId() != null && this
						.getVproximityId().equals(castOther.getVproximityId())))
				&& ((this.getDmarriageDate() == castOther.getDmarriageDate()) || (this
						.getDmarriageDate() != null
						&& castOther.getDmarriageDate() != null && this
						.getDmarriageDate()
						.equals(castOther.getDmarriageDate())))
				&& ((this.getDesignationName() == castOther
						.getDesignationName()) || (this.getDesignationName() != null
						&& castOther.getDesignationName() != null && this
						.getDesignationName().equals(
								castOther.getDesignationName())))
				&& ((this.getImageLocation() == castOther.getImageLocation()) || (this
						.getImageLocation() != null
						&& castOther.getImageLocation() != null && this
						.getImageLocation()
						.equals(castOther.getImageLocation())))
				&& ((this.getSectionName() == castOther.getSectionName()) || (this
						.getSectionName() != null
						&& castOther.getSectionName() != null && this
						.getSectionName().equals(castOther.getSectionName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getVemployeeId() == null ? 0 : this.getVemployeeId()
						.hashCode());
		result = 37 * result
				+ (getIfingerId() == null ? 0 : this.getIfingerId().hashCode());
		result = 37
				* result
				+ (getVemployeeName() == null ? 0 : this.getVemployeeName()
						.hashCode());
		result = 37 * result
				+ (getVreligion() == null ? 0 : this.getVreligion().hashCode());
		result = 37 * result
				+ (getVcontact() == null ? 0 : this.getVcontact().hashCode());
		result = 37 * result
				+ (getVemail() == null ? 0 : this.getVemail().hashCode());
		result = 37 * result
				+ (getVgender() == null ? 0 : this.getVgender().hashCode());
		result = 37
				* result
				+ (getDdateOfBirth() == null ? 0 : this.getDdateOfBirth()
						.hashCode());
		result = 37
				* result
				+ (getVnationality() == null ? 0 : this.getVnationality()
						.hashCode());
		result = 37
				* result
				+ (getDapplicationDate() == null ? 0 : this
						.getDapplicationDate().hashCode());
		result = 37
				* result
				+ (getDinterviewDate() == null ? 0 : this.getDinterviewDate()
						.hashCode());
		result = 37
				* result
				+ (getDjoiningDate() == null ? 0 : this.getDjoiningDate()
						.hashCode());
		result = 37
				* result
				+ (getDconfirmationDate() == null ? 0 : this
						.getDconfirmationDate().hashCode());
		result = 37
				* result
				+ (getVsectionId() == null ? 0 : this.getVsectionId()
						.hashCode());
		result = 37
				* result
				+ (getVfatherName() == null ? 0 : this.getVfatherName()
						.hashCode());
		result = 37
				* result
				+ (getVmotherName() == null ? 0 : this.getVmotherName()
						.hashCode());
		result = 37
				* result
				+ (getVpermanentAddress() == null ? 0 : this
						.getVpermanentAddress().hashCode());
		result = 37
				* result
				+ (getVmailingAddress() == null ? 0 : this.getVmailingAddress()
						.hashCode());
		result = 37
				* result
				+ (getVmeritalStatus() == null ? 0 : this.getVmeritalStatus()
						.hashCode());
		result = 37
				* result
				+ (getVotherQualification() == null ? 0 : this
						.getVotherQualification().hashCode());
		result = 37
				* result
				+ (getVcomputerSkill() == null ? 0 : this.getVcomputerSkill()
						.hashCode());
		result = 37
				* result
				+ (getVproximityId() == null ? 0 : this.getVproximityId()
						.hashCode());
		result = 37
				* result
				+ (getDmarriageDate() == null ? 0 : this.getDmarriageDate()
						.hashCode());
		result = 37
				* result
				+ (getDesignationName() == null ? 0 : this.getDesignationName()
						.hashCode());
		result = 37
				* result
				+ (getImageLocation() == null ? 0 : this.getImageLocation()
						.hashCode());
		result = 37
				* result
				+ (getSectionName() == null ? 0 : this.getSectionName()
						.hashCode());
		return result;
	}

}
