package database.hibernate;

// Generated Jul 31, 2016 4:54:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * VwRptEmployeeifo generated by hbm2java
 */
public class VwRptEmployeeifo implements java.io.Serializable {

	private VwRptEmployeeifoId id;

	public VwRptEmployeeifo() {
	}

	public VwRptEmployeeifo(VwRptEmployeeifoId id) {
		this.id = id;
	}

	public VwRptEmployeeifoId getId() {
		return this.id;
	}

	public void setId(VwRptEmployeeifoId id) {
		this.id = id;
	}

}
